### ISSUE TITLE
Gaps protection on Amstrad CPC issue

### ISSUE THREAD

**Issue by Turk182es** [keirf/FlashFloppy#104]
Hi all,

All DSK with GAPS protection doesn't work on Amstrad CPC6128. Any idea ?

Regards

**Comment by keirf** [comment]
Attach an example here. If you have any technical knowledge of the format and what needs to be done to handle this case, let me know that too. Else I will inspect the image you send me to work it out.

By the way, if you convert these images to HFE, do they work?

**Comment by Turk182es** [comment]
Hi all,

Just update with the new firmware 0.19a and all work fine.

Thank you guys!
