### ISSUE TITLE
Couldn't get 2 button gotek working

### ISSUE THREAD

**Issue by Shiny0815** [keirf/FlashFloppy#112]
Freshly flashed a 2-button gotek-device to actual firmware using the provided FF_Gotek-v0.9.19a.dfu.

When I put a usb-stick (tested two) into it, providing some amstrad dsk's the display shows the filename of the first dsk in line 1 and in line two 000/001 EJECTED and directly before EJECTED blinks a *. When I press any button, nothing happens.

I attached the content of my stick.

Any idea?

[FF.zip](https://github.com/keirf/FlashFloppy/files/2014788/FF.zip)

**Comment by keirf** [comment]
You have a jumper at position JA on your Gotek. Remove it.

If you do not have a jumper there: you have a solder short there which needs to be repaired.
