### ISSUE TITLE
Strange rotary encoder behaviour

### ISSUE THREAD

**Issue by tkurbad** [keirf/FlashFloppy#119]
Hi,

I bought this rotary encoder https://www.ebay.de/itm/152484035297, removed the pullup resistors from the back of the board and connected it according to the scheme given in the wiki.

Now, strangely, while directional controls and functionality in general are okay, when I set ```rotary = simple``` in FF.CFG, only every second notch of the rotary counts up or down the list of images by one entry. If I put ```rotary = gray```, every second directory entry is left out.

Did I wire something incorrectly or did I just get a somewhat exotic kind of encoder?

Thank you in advance,
Torsten

**Comment by keirf** [comment]
It's not unheard of I'm afraid, I had at least one other report that sounded similar. We never really resolved it and the fix was to buy a different encoder. Maybe buy ones with a (mostly) blue plastic base. It was ones with a green plastic base which were previously reported not working.
