### ISSUE TITLE
Larger Rotary circuit diagram

### ISSUE THREAD

**Issue by smartroad** [keirf/FlashFloppy#12]
Hi!

Loving the firmware. Is there a larger version of the image for the rotary encoder? I can't read the size of the resistors 😞 I am assuming they are 1K but just in case I am wrong!

https://github.com/keirf/FlashFloppy/blob/master/doc/assets/rotenc.jpg

Cheers!

**Comment by keirf** [comment]
You do not need pullups they are just part of the Ky040 module schematic. In fact the pullups can make the encoder inputs unreliable so you are better without them.

I will update the documentation to mention the resistors and that they should be ignored.

**Comment by fook42** [comment]
i will send a new picture... with the additional connection for the Push-Button (Button #3) .. and the +3.3V - Line.. okay?

**Comment by keirf** [comment]
Yes sounds good thanks. I am going to move the docs to the Github wiki by the way, but that won't change anything much, just moves docs and assets out of the source repository into *.wiki.git repo instead.

**Comment by fook42** [comment]
here is my proposal: 
![gotek_new_kl](https://user-images.githubusercontent.com/28691557/30886970-a247c50a-a319-11e7-91f8-2ec5f81d72b3.jpg)

**Comment by smartroad** [comment]
That's great much more readable thanks!

**Comment by keirf** [comment]
There are a couple of regressions compared with the original image:
1. Pin B is no longer labelled
2. The colour codes are no longer repeated at the encoder pins themselves. Clearer if you add a short span of colour by each pin: A=red,B=blue,C=brown,switch1=green,switch2=brown

Please can you make these fixes and I will then commit the picture to the new wiki pages.

Cheers!

**Comment by fook42** [comment]
you're right, Keir... i took your advice and made the changes... the labeling of the encoder is not of any use i guess, so i removed it completely.
![gotek_new_kl](https://user-images.githubusercontent.com/28691557/30925482-4d6c697a-a3b2-11e7-82ce-515cd939f4a5.jpg)

**Comment by keirf** [comment]
Sorry, I think the A/C/B labelling at least is useful as it matches up with those pin names in the instructions. Could you add them back?

Apart from that -- looks super good, much better than my own pics ;)

**Comment by fook42** [comment]
next update...
![gotek_new1](https://user-images.githubusercontent.com/28691557/30927197-01ae001a-a3b8-11e7-8222-b001e5caa55d.jpg)

**Comment by keirf** [comment]
Can't argue with that! Thanks.
