### ISSUE TITLE
Option to display first three alphanumeric letters of disk name in 7 segment

### ISSUE THREAD

**Issue by Xnyle** [keirf/FlashFloppy#124]
Title says it all, it would be cool to have the disk names in the 7segment display in normal mode.
First 3 alphanumeric letter or even cooler, scrolling.

Is that possible?

**Comment by keirf** [comment]
Not very satisfactorily as it is a simple 7-seg display (no diagonal elements which make alpha characters clearer to read). So for example some letters (k, m, z, ...) can't be represented at all.

If you want a better display, OLED displays are cheap and can be glued in place of the old 88 display fairly easily.
