### ISSUE TITLE
Drive disconnected/Floppy ejected during navigation (rotary)

### ISSUE THREAD

**Issue by edd72** [keirf/FlashFloppy#129]
Hi

I'm using the last version (0.9.19a) with a Gotek plugged on an Amstrad CPC 6128 (external).

My options are:
autoselect-file-secs = 0
autoselect-folder-secs = 0
nav-mode = native
twobutton-action = rotary
rotary = gray

When I mount a dsk and then navigate (with my rotary encoder) it seems that the drive become unplugged or the floppy is ejected (same behaviour).

Is it possible to keep the drive mounted/floppy inserted and navigate at the same time?
(I thought that will be the behaviour with the options I set)

Thank you for the very good job.

**Comment by keirf** [comment]
While navigating the firmware does not have the resources (RAM, CPU) to continue full drive emulation, so the disk is ejected. This behaviour will not change.
