### ISSUE TITLE
lastest-release-link

### ISSUE THREAD

**Issue by fook42** [keirf/FlashFloppy#13]
not a real issue, but a question;
is it possible to have a "lastest-release.zip" or something like this that points to the most recent release?

i'm linking to your page/to the lastest release from our forum (a1k) and currently i've to update the link sometimes more than once a day ;-)

**Comment by keirf** [comment]
I will put a Releases page on the wiki, which will always have latest release link at the top. Stay tuned.

**Comment by keirf** [comment]
Done, this is the link: https://github.com/keirf/FlashFloppy/wiki/Downloads
