### ISSUE TITLE
RX50 DSK-Image

### ISSUE THREAD

**Issue by pdp11user** [keirf/FlashFloppy#131]
Hello Keirf,
I am wondering why in version v0.9.18a DEC RX50-emulation worked perfectly, but not anymore in the new v0.9.21a. The RX50 Format is:
 { 10, 1, 30, 1, 2, 1, 0, _C(80), _R(300) }, /* 400k (#2) */
Please be so kind and give it a thought.
Thanks for your attention. I’m looking forward to your reply.

**Comment by keirf** [comment]
It is because the format gets overridden by the more usual 40 cyl double sided 10 spt format which has same image size. Would you like me to add a `host=rx50` FF.CFG option for you?

**Comment by keirf** [comment]
Or `host=dec` or `host=dec-rx50`...

**Comment by pdp11user** [comment]
Thank you for your fast respose.
I also use the RX33-format which is the same as the PC 1.2 MB.
Is it possible that I can use both Disk-formats with the same FF.CFG?

**Comment by pdp11user** [comment]
host=dec for RX50 and RX33 would be the ultimate.

**Comment by keirf** [comment]
PC 1.2MB is 360rpm that's OK? Yes I will do `host=dec` and attach here for testing.

**Comment by pdp11user** [comment]
Yes, 360rpm for RX33.
Great!! Thank you, that's most kind of you!

**Comment by keirf** [comment]
Please try the following firmware with `host = dec` in your FF.CFG. Should work with RX33 and RX50.

[ff_131_1.zip](https://github.com/keirf/FlashFloppy/files/2108841/ff_131_1.zip)

**Comment by pdp11user** [comment]
Hello Keirf,
it runs like a charm!  You are ingenious!
In my view the "DEC-World" must gain knowledge about the existence of your excellent FlashFloppy.
I appreciate your kindness and helpfulness.

**Comment by keirf** [comment]
Thanks. This will be rolled into this week's release. By the way support for rx01 and rx02 is also a possibility.

**Comment by pdp11user** [comment]
Of course, but these 8"-FDDs need adapter-cables for connecting the 3.5" GOTEK.
As regards me, I only use Q-Bus RQDX3-controllers for RX50, RX33 and MFM-HDDs.
Now, if someone is interested in 8"-FDD emulation, I*m sure, he will contact you.

--------------------------------------------
On Sun, 6/17/18, Keir Fraser <notifications@github.com> wrote:

 Subject: Re: [keirf/FlashFloppy] RX50 DSK-Image (#131)
 To: "keirf/FlashFloppy" <FlashFloppy@noreply.github.com>
 Cc: "pdp11user" <g.zugarek@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Sunday, June 17, 2018, 8:34 PM
 
 Thanks. This will be rolled into
 this week's release. By the way support for rx01 and
 rx02 is also a possibility.
 
 —
 You are
 receiving this because you authored the thread.
 Reply
 to this email directly, view
 it on GitHub, or mute
 the thread.
