### ISSUE TITLE
Commodore 64 1581 .d81 disk image support?

### ISSUE THREAD

**Issue by fzdravko** [keirf/FlashFloppy#132]
Any chance for Commodore 1581 .d81 disk image support?

Thanks.

**Comment by keirf** [comment]
Tentative yes but depends as I thought 1581 had a custom serial interface to the c64 and the Gotek would not really be physically compatible?

**Comment by fzdravko** [comment]
Yes, it has custom serial interface for connection with c64, but internally 1581 have plain 3.5" floppy drive and connection to it (like amiga...). 

P.S.
I also have usb HxC Floppy emulator and it is working with 1581.

**Comment by keirf** [comment]
Oh I'm thinking of 1541 with custom formats and different internal drive interface. Do you have documentation for the d81 image and physical track format?

**Comment by fzdravko** [comment]
No, I don't, but I found this
https://ist.uwaterloo.ca/~schepers/formats/D81.TXT

Also on HxC forum there is a mention that D81 in nothing special:
http://torlus.com/floppy/forum/viewtopic.php?t=531

**Comment by keirf** [comment]
Okay please try the following firmware:

[ff_132_1.zip](https://github.com/keirf/FlashFloppy/files/2118219/ff_132_1.zip)

**Comment by fzdravko** [comment]
I tried it but it doesn't work. Just says "file not found".

**Comment by tomse** [comment]
Now that the issue is up, I guess the GOTEK isn't powerful enough to actually act as a 1581/1541/1571 drive which can directly be attached to the IEC port.?
instead of having a shugart/pc interface port with the 34pin connector, i.e. pins 1-5 can be used as the serial/iec interface instead.

**Comment by Squirrel61** [comment]
@tomse I guess you're talking about sd2iec or similar solutions? In other words, it has already been made. So it's perfectly doable, but a waste of @keirf 's precious time. And besides, I think it would be an "either-or" solution, because I guess it will be impossible to have the Gotek support both the IEC bus and the normal floppydrive bus at the same time. I'm already wondering with al the additions @keirf is making, when the Gotek will be out of flash memory.

**Comment by tomse** [comment]
@Squirrel61 yes similar to the sd2iec, but where sd2iec isn't 100% compatible, far from it, a cheap and better solution could lie in a gotek. Yes there is also 1541 Ultimate which is close to 100% compatible this one doesn't support d81 files though.

If it's a waste of Keir's time only he can judge that.

**Comment by fzdravko** [comment]
@keirf Yes, it's connected right.

**Comment by keirf** [comment]
And jumpered right? I don't know whether you need a jumper at JC (selects PC style interface rather than Shugart). Also S0 vs S1 for drive select. Do you see the green Gotek led flash on drive activity? Do you see the track number change as the drive heads are driven by the host?

**Comment by fzdravko** [comment]
I didn't change any jumpers, will try that later. When 1581 and gotek are on and image file selected, when I restart c64 (turn off/ turn on) tracks go to 0 and then to 39:1. When command for dir is issued, error "file not found" is immediately shown, it doesn't even try to read.

I will try with different jumper config later today.

**Comment by keirf** [comment]
Actually I suspect the jumper configuration is fine, interface is Shugart which is the default (no jumper at JC). Also probably drive-select 0 is correct, so jumper at S0 only. I guess this is what you already have. Now I am suspecting the track layout within the image is different than what I expect. Let me check that,,,

**Comment by pdp11user** [comment]
The 
![ibmdrive for 1581](https://user-images.githubusercontent.com/40324621/41660567-4f6d972c-7494-11e8-85f7-ab9e7100455b.jpg)
Commodore 1581 controller needs ready at pin 34 and drive-select  0:

interface =shugart / jc = open
DS 0

Hope that helps!

**Comment by keirf** [comment]
Okay, looks like side ordering is flipped in a D81 image. Here is a new firmware to test:

[ff_132_2.zip](https://github.com/keirf/FlashFloppy/files/2119476/ff_132_2.zip)

**Comment by fzdravko** [comment]
It's working now.

Thank you!!!

**Comment by gilmod714** [comment]
it would be really nice to have FF connect directly to IEC bus .. here's a scenario: you have VICE emulator running on the PC and zoom-floppy USB adapter (IEC) adapter .. you want to attach physical floppy drives (any shugrat/PC type) 3.5 / 5.25  and run original c64 disks .. btw : vice can connect to a real c64 drive using zoom-floppy/or DIY promicro clone
