### ISSUE TITLE
Ensoniq ASR-10 "Disk Drive Not Ready"  / Errors when using FF in ASR-10 with .HFE (Solved)

### ISSUE THREAD

**Issue by DOSputin** [keirf/FlashFloppy#139]
Using known good .HFE images
Using a GOTEK flashed FF device with latest firmware as of this writing.

ASR-10 will boot it's OS from and .HFE image,  via the GOTEK FF.

OS Disk is ejected.  (two-button press)

An .HFE file is selected.  

The ASR-10 Load sequence is initiated.  
ASR-10 Reports "Disk Drive Not Ready"  or intermittently "Disk Not Formatted" 

`included FF.CFG (.TXT is for GitHub upload compat.)`
[FF.CFG.TXT](https://github.com/keirf/FlashFloppy/files/2182963/FF.CFG.TXT)

**Comment by DOSputin** [comment]
A known good .HFE file for analysis 
[44KHZCOMP.hfe.zip](https://github.com/keirf/FlashFloppy/files/2182967/44KHZCOMP.hfe.zip)

**Comment by keirf** [comment]
https://github.com/keirf/FlashFloppy/wiki/Host-Platforms#ensoniq

You need to change the interface= line in FF.CFG:
`interface = ibmpc-hdout`

**Comment by DOSputin** [comment]
Oh shit.   RTFM!  🤦🏻‍♂️

**Comment by DOSputin** [comment]
I'll leave this here, instead of starting a new issue:
Last few weeks been using a Gotek FlashFloppy, with Ensoniq ASR-10.  loading disk images works well.

Saving not so much. Have **not** been able to reliably save any work.  

Starting from a fresh blank ASR-10 HFE from the pack of disk images that Jeff (HxC2001) provided via his site.

The process goes as follows.

- Sample something and create a new instrument.  

- Save the instrument data the first time to the blank .hfe, ASR-10 reports back `"DISK OPERATION SUCCESSFUL"` 

After this point things go sour.. 

Trying to save changes to an existing file, or any other disk operation the ASR-10 reports back: `"DISK NOT FORMATTED"  `

After a successful save, trying to immediately load this data back to the ASR-10 into a new instrument slot will cause various errors, such as intermittently reports: `"DISK HARDWARE ERROR"` `"DISK DATA CORRUPTED"`, or `"DISK NOT FORMATTED"  `

Any ideas?

**Comment by keirf** [comment]
It would be helpful to attach one of the bad HFE images here. But in any case you are better off using `host=ensoniq` in FF.CFG and use IMG files (blank ones are just empty files of the correct formatted capacity).

**Comment by keirf** [comment]
In fact are they HD HFE images? They are barely reliable for read on FlashFloppy at the moment let alone write (which is slower). Must use IMG.

**Comment by DOSputin** [comment]
Here is an example blank HFE, after formatting upon the ASR-10, and attempting to write data.
The subsequent error message from the ASR-10 was `"DISK HARDWARE ERROR"`
Also maybe worth noting, FlashFloppy device hung @ track 43
[ASR-10-BLank_01.hfe.zip](https://github.com/keirf/FlashFloppy/files/2241924/ASR-10-BLank_01.hfe.zip)

**Comment by DOSputin** [comment]
Thanks for the info.
Was simply experimenting with  the `track-change` setting.  
> You are still better off with IMG files.
In the current circumstance,  working in collaboration with other musicians whom have ASR samplers with hardware configurations that only accept .HFE image types makes support for that file type important.

**Comment by Tornado-Xtov** [comment]
Hi there !

I pretty have the same issue :

I am a french user of an Ensoniq TS-12 keyboard. I bought it with a Gotek already installed but it didn’t work at all.

I just flashed it correctly (I think), following the step-by-step tutorial, with USB programming.

The LED display now says F-F. But when I insert my USB drive, it displays the error code E34 (with or without files available at the root of the USB drive). I am stuck with it ! And my TS displays « Disk drive not ready » whatever command I try from the front panel.

The jumper on the rear of the gotek is on S0 only.
The USB drive was formatted in FAT-32.

The essential FF settings are as follow (everything else is default).

interface = ibmpc-hdout

host = ensoniq

pin02 = auto
pin34 = auto

Any help would be appreciated ! Thanks to the communauty.

Christophe

**Comment by tenuke** [comment]
Do you have valid images on the usb?

https://github.com/keirf/FlashFloppy/wiki/Error-Messages

Tornado-Xtov <notifications@github.com> kirjoitti la 12. tammikuuta 2019
klo 15.35:

**Comment by Tornado-Xtov** [comment]
Yes, I have original Ensoniq Images.

The point is that when I also insert my USB thumb in the drive without any files on it, the Ensoniq TS-12 displays the error message "disk drive not ready".

I've tried with or without files on it, and the same placing the FF files in a subfolder named FF/

**Comment by keirf** [comment]
I don't recognise these file extensions and they are not supported by FlashFloppy. Can they be converted to HFE by HxC tools?

**Comment by Tornado-Xtov** [comment]
These are proprietary Ensoniq file format for ASR & TS series.
I don't how to convert them. Maybe could you provide a link ?

**Comment by keirf** [comment]
I have no idea myself. You may have to research if anyone else has had success with these images for FlashFloppy or HxC drives.

**Comment by Tornado-Xtov** [comment]
I also have these files in system exclusive format. So logically I should be able to make the drive work with no files on the USB thumb, right ? I.E. I can use the SAVE command from the front panel of my Ensoniq to effectively save the files on the USB thumb.

**Comment by Tornado-Xtov** [comment]
I still have the E34 error with no files on the USB thumb. So it's not a file issue.

**Comment by keirf** [comment]
FlashFloppy only works by mounting disk images stored as files on the USB drive. So you must have at least one supported disk image type on the drive.

**Comment by Tornado-Xtov** [comment]
OK I ask on the Ensoniq Facebook forums to find other users having the same issues. Do you think you could make these file extensions supported by FlashFloppy ?

**Comment by keirf** [comment]
Ok ok I did some checking.

Firstly, HxC software does support these images. So you could download that (search for HxCFloppyEmulator software) and run it on Windows or Mac. It will let you load an EDE/EDT/EDA/etc images, and then export it as HFE (specifically HFEv2). These should then load and work on FlashFloppy.

Also, it does look like these images could be supported directly by FlashFloppy. I will reopen this ticket to track it.

**Comment by Tornado-Xtov** [comment]
Ho Thank you so much Keir ! I give it a try.

**Comment by keirf** [comment]
To help could you send/attach some images of the various types (EDA, EDT, EDE, etc). Or point me at a site where I can download some?

**Comment by Tornado-Xtov** [comment]
EDE files are Samples for Ensoniq EPS Samplers, they are compatible with ASR samplers and TS series.
EDA files are Samples for Ensoniq ASR Samplers, they are compatible with TS series, but not with EPS.
EDT files are TS series only. Not compatible with ASR or EPS samplers.

Hope this helps !
[Archive.zip](https://github.com/keirf/FlashFloppy/files/2752194/Archive.zip)

**Comment by Tornado-Xtov** [comment]
It works !!!! After being converted in HFEv2.

A big Thank You Keir ! You Rock !!

**Comment by keirf** [comment]
Ok and let's see if I can do direct support too :)

**Comment by keirf** [comment]
Unfortunately the Ensoniq image formats are compressed -- they have a bitmap of blocks in use, and only those sectors are present in the image file. This is not easy to support in firmware.

Your best bet is to convert to HFE or IMG using HxC software. IMG is best for HD (1.6MB) disk images. For IMG support you will need `host = ensoniq` in FF.CFG.

**Comment by keirf** [comment]
Two more things though:

1. I could support EDx to IMG conversion with a Python script if that is handy to anyone.

2. Could you try IMG files (you can create them using HxC software just as you did HFE files)? You need `host = ensoniq` in your FF.CFG. I am particularly interested in performance compared with HFE images -- do reads and writes take measurably longer?

**Comment by Tornado-Xtov** [comment]
I am not at home at the moment, not before next week-end, I give it a try. That being said, the conversion process is very fast to my taste, and the read/write process on the host is as slow as I remember with my former Ensoniq ;-) and this is no problem for me (it’s still pretty fast !).

**Comment by Acustico80** [comment]
Hello!
I'm not here and I need help to understand some things!
First of all, I want to inform you that I am not a programmer, however I am curious and I am curious about these technologies!
Last night, I was able to install the HxC firmware on my gotek through ST-microeletronics. Price me it was ok! However when I turn it on on my Ensoniq TS-12, the LED digits indicate F-F. I have already connected a pendrive with some HFE files, however sometimes I can see them on the Ensoniq display, but other times it says "disk not formatted", and I cannot understand what to do to transport the data so that the ensoniq can read and let it be heard the sounds! I appreciate help! Thank you.

**Comment by ASL407** [comment]
Hello, I am having the same (or a very similar) issue with my ASR-10 Keyboard and Floppy emulator. Installed Gotek floppy emulator that came with an FF.CFG file on the usb, ASR-10 Keyboard is able to boot OS just fine, but when I navigate to any other disk images and attempt to load the instrument, I get "Disk Drive Not Ready".

I've tried all the solutions shared above and am still having no luck. I've tried several things with moving jumpers around on the board as well, but I'm getting the sense this isn't a hardware issue.

the text contained within my FF.CFG file is attached. Can provide an example of one of the HFEs that came pre-loaded on the usb stick if helpful.

[FF.CFG.TXT](https://github.com/user-attachments/files/27327440/FF.CFG.TXT)

Would really appreciate any ideas, please let me know if I should make a new issue about this instead. Thank you all!

**Comment by parveezawan808-source** [comment]
insert disk problem
