### ISSUE TITLE
Shugart floppy drive interface mode

### ISSUE THREAD

**Issue by ClementycWong** [keirf/FlashFloppy#143]
Hi,
         My Old NEC system using Shugart ( i guess P34-RDY) and the floppy drive support both 1.2M and 1.44M. I try for the 1.2M (77 ,8 ,1024) which is working fine(Dos mode), but when i try the 1.44M (80 ,18, 512) Dos disk, which is not working.
          Is there any way, so i can use the Shugart mode with 1.44M disk?
Have a nice day
thanks

**Comment by keirf** [comment]
What exact size are the 1.44 image files and what filename suffix do you use? How does FlashFloppy react? Eg does it seem to mount them, or give you an error code?

**Comment by ClementycWong** [comment]
Actually, I create a empty drives both (1.44M and 1.25M using DSKA0000,DSKA0001) and put the basic dos function files (autoexec, config, and so on.........). Using Flashfloppy, the 1.2M drive can transfer files normally(full capacity). But 1.44M drive can only transfer around 500 to 700K. and show error "unable to read floppy disk".  
thanks

**Comment by keirf** [comment]
Try another USB stick?

**Comment by ClementycWong** [comment]
Try two USB sticks, same problem.

**Comment by keirf** [comment]
Do you have an FF.CFG file?

By the way default geometry for 1.2m files is 15 sectors, 360 rpm.

**Comment by ClementycWong** [comment]
yes, I have FF.CFG file. using Shugart mode. 
1.23M files is 8 sectors, 1024 bytes 360rpm. 
1.44M file is 18 sectors, 512 bytes....... a default geometry.
The system look like using NEC-PC98 format ( 3 mode floppy drive for PC) but the hardware connection using Shugart mode as Pin34- RDY signal.
thanks

**Comment by keirf** [comment]
Does the 1.44M image fail in the same place every time, or is the error random?

**Comment by ClementycWong** [comment]
yes, fail in the same place every time.
 I did try the host=pc98 , but nothing change.  
Another interesting things is when i was using interface=JC , pins S1 and JC were shorted. The IBM PC format the 1.44 disks (with bad sector).
But when i used the interface= ibmpc, everything fine. 
Sure, if i get the debug build, i can try for it. 
Thanks a lot , have a nice day.

**Comment by keirf** [comment]
Are you using IMG or FDI image files?

**Comment by ClementycWong** [comment]
I created a blank disk and saved files to it.( Dos Mode).  Just as a PC floppy drives.

**Comment by keirf** [comment]
What I mean is, FlashFloppy mounts disk images stored on your USB stick fat filesystem. What are the names of the image files on your USB stick? If they are fdi files can you please zip them and attach them to this ticket.

**Comment by keirf** [comment]
Any update?

**Comment by ClementycWong** [comment]
I am not using the FDI files. I am using the create disk function from (HXC)  for both 1.44M and 1.23M disks and copying files to them. 
Sorry for the late information.

**Comment by ClementycWong** [comment]
[1.44M,1.23M files.zip](https://github.com/keirf/FlashFloppy/files/2208462/1.44M.1.23M.files.zip)
Attached files.

**Comment by keirf** [comment]
Ok the problem is you are using HFE images. At 2M unformatted capacity these only work marginally on FlashFloppy as yet (will improve in future, but not yet).

However you have a better option -- you can use IMG files! You can create these in HxC by choosing IMG when you "Export". However for simplicity I have also attached a pair of blank IMG files here. They are literally just blank files of the correct size :) They will need to be formatted with a filesystem before you can copy files to them!

[blank.zip](https://github.com/keirf/FlashFloppy/files/2208486/blank.zip)

**Comment by ClementycWong** [comment]
Thanks for the quick reply.  I will try for it.

**Comment by keirf** [comment]
Please reopen if the issue is not resolved. I'm sure it will be.
