### ISSUE TITLE
Atari ST satan disk

### ISSUE THREAD

**Issue by nioh-blog** [keirf/FlashFloppy#147]
My Satan disk wont boot anymore after mounting gotek/ff :(

1040STFM, TOS1.02, 1MB, gotek/FF

please help me how to proper config the two devices to work together? 

thx

**Comment by keirf** [comment]
Make sure ribbon cable is right way round (could be opposite way round to original drive!) and Gotek has jumper on S0 only.

**Comment by nioh-blog** [comment]
my acsi cable was broken...
Now my satandisk and gotek/flashfloppy works perfectly! 
THX VERY MUCH GOOD WORK
