### ISSUE TITLE
Add notes to flash instructions.

### ISSUE THREAD

**Issue by alvaroalea** [keirf/FlashFloppy#15]
Hi, two coments you can include in the instructions:

If the serial-usb adaptar has voltage selection, it must be in 3.3V (for the TX/RX signal) but you need to supply 5V to the power conector.

In case you are flashing with linux and get:

Got NACK from device on command 0x43
Can't initiate chip mass erase!
Failed to erase memory

you need to disable read protection with:

stm32flash -k /dev/ttyUSB0

and optional erase the flash with

stm32flash -o /dev/ttyUSB0

Then you can flash it normaly.

**Comment by keirf** [comment]
I have added the '-k' line to the main instructions, it's harmless to run it even when it is not required (but IME it is always required for a brand-new Gotek).

The '-o' line is not needed: Read-Unprotect causes a Mass Erase. Also stm32flash explicitly Mass Erases before Writing.
