### ISSUE TITLE
Unauthorized disk ejection when writing 100k+ files

### ISSUE THREAD

**Issue by ChristopheVC** [keirf/FlashFloppy#153]
Hi,
when using FlashFloppy on an industrial equipment, everything goes well with small files. (reading & writing)
when the system tries to write large files, the system stops each time at the same %, saying there was an unauthorized ejection of the disk. It must be at around 100kB of the file.
Also formatting does not work and stops after a certain % of the total process. Again, each time the same %
I tried with img and ima files. 
Also tried different combinations in the config file. (interface, host, side-select-glitch-filter, track-change, index-suppression)

Any ideas? 
Thanks

**Comment by ChristopheVC** [comment]
I use 1.44M img files.
The system says that it has 1457664 of free space, the same amount as with floppy disks.
I made the img files with 2 different programs, but with the same result.
I used another type of USB stick, also with the same result.

If i look at the Gotek busy light, then it goes out a couple of times, but the system continues untill that point that the system says the disk was changed/ejected. 
I took a look at the file on my floppy backup and the systems stops after writing +/- 70000 bytes

I have no idea of the disk layout which is used by the host, I will try to figure that out. With floppy disks the host accepts windows formatted floppies without any problem.

**Comment by keirf** [comment]
Do you have to format windows formatted floppy disks before you can use them?

**Comment by ChristopheVC** [comment]
I can use both, pre-formatted and "re"-formatted floppy disks. Reformatted with a windows machine or with the host.

**Comment by keirf** [comment]
Then try another USB stick, clear the flash configuration (hold both buttons with no stick inserted until display changes) and try `index-suppression = no` as the only line in FF.CFG.

Interesting if this fixes the issue or even just changes the progress percentage at which write or format fails.

**Comment by ChristopheVC** [comment]
Now I get a "no disk" error

**Comment by keirf** [comment]
Have you tried a jumper at position JC at rear of the Gotek? Or same effect: `interface = ibmpc` in FF.CFG.

**Comment by ChristopheVC** [comment]
The progress % stays the same.

**Comment by keirf** [comment]
Does this system work with unmodified PC floppy drives do you know?

**Comment by keirf** [comment]
Also I'd expect changing interface to make some difference. I wonder if your FF.CFG is being picked up at all?

**Comment by ChristopheVC** [comment]
When I use no JC jumper, he seems to recognize the interface = ibmpc parameter

**Comment by ChristopheVC** [comment]
What do you mean with unmodified PC floppy drives? When I insert a brand new IBM formatted high density floppy drive, then it is recognized and usable. I do not have any unformatted floppy drives at my disposal for the moment.

**Comment by keirf** [comment]
I am talking about the drive, not the disks.

**Comment by ChristopheVC** [comment]
For the moment we are using TEAC fd-235hf floppy drives. So that are PC compatible drives.

**Comment by keirf** [comment]
So I would try jumpers on S1 and JC only. No FF.CFG file at all. And reset flash configuration by holding both buttons with no stick inserted until the display changes (led display changes to rSt).

This is a totally basic setup for FlashFloppy in PC compatible mode.

**Comment by keirf** [comment]
Could you try `interface = ibmpc-hdout` in FF.CFG? You tried more than one USB stick now with zero effect, right?

**Comment by ChristopheVC** [comment]
Now there is change.
The random stops are gone. The system stops always at 30% even after a flash configuration reset.

I tried more than one brand of USB stick with the same results.

**Comment by keirf** [comment]
I don't know it seems perhaps some nonstandard configuration is needed for pins 2 and 34. Some of the teac drives do have jumpers for configuration so it's not a given that the drive is set up just as it would be for PC. Do you have any documentation on the host system or procedures for changing the drive?

**Comment by ChristopheVC** [comment]
I will try some configurations of pin 02 & pin 34.
As far as I've tested yet, it seems to me like the voltage on pin 34 drops to 0V  for a little while at 30% writing.

I do not have detailed documentation on the drives of the host.

**Comment by keirf** [comment]
Pin 34 going low would be unexpected and bad for a PC drive as that is the dskchg signal and should only be low when no disk is inserted.

Perhaps try `pin34 = high` in FF.CFG. This would stop disk changes from working but is okay for your basic write tests I think. If pin 34 continues to go low then this signal has unexpected purpose, or there could be something electrically wrong with the host or the Gotek.

**Comment by ChristopheVC** [comment]
The host does not allow pin 34 to be high all the time. 
I noticed something else. When I insert a USB without IMAGE_A.CFG, the fault appears allmost immediatly when the host starts writing. (probably with the creation of the file)

**Comment by keirf** [comment]
Very odd behaviour if you can be sure that pin 34 changes value during writes then something is definitely up.

**Comment by keirf** [comment]
Let me know if there's more advice I can give here. Else I will close this ticket, as I'm not sure there's a bug fix or documentation-update to be gleaned here.

**Comment by ChristopheVC** [comment]
For the moment it's ok. I will do some further testing on my own.
Thanks for the advice.

**Comment by ChristopheVC** [comment]
I did some further reading on the Gotek and i think it could have something to do with the memory of the Gotek being 64kB. I guess, when the memory is full, the Gotek starts writing to the USB and looses connection with the host.

**Comment by keirf** [comment]
Certainly the Gotek can go quiet while it is writing back to USB but most hosts can deal with this okay. If it was an issue of writeback speed, you might expect changing USB stick to alter behaviour (eg % progress before failure). So it still feels like something else is afoot here.

**Comment by keirf** [comment]
I think short of getting a debug build running to collect serial logs, or getting direct access to this system myself, we'll have to park this for now. If you wish to pursue this further, or can collect more info (eg. interesting info on floppy interface signals such as pin 34 via scope or logic analyser) then feel free to reopen.

**Comment by ChristopheVC** [comment]
Hi,
I just want to share my solution.
All the USB sticks that i have tried were USB2.0. So I bought a USB3.0 stick with fast writing speed and now it finishes writing as it should.
So after all, it was due to the too slow writing speed to the USB stick.

**Comment by keirf** [comment]
Glad to hear you're sorted. Hopefully I can get performance better for a wider range of sticks post-v1.0.
