### ISSUE TITLE
Native USB

### ISSUE THREAD

**Issue by JoanMCD** [keirf/FlashFloppy#156]
Hi, is there a mode to have only one emulated Floppy Disk writing the files direct to the USB stick. I.E if the stick is formatted as 1.44 Drive. Would be usefull to exchange files by USB stick direct with a PC without the need to open an image.

**Comment by keirf** [comment]
There is a mode for direct access to the USB stick, it's used by the Amiga, CPC, ST, etc HxC file selectors. However it needs a host-system program or driver. FlashFloppy won't turn file contents of the USB stick into a virtual FAT12-formatted floppy disk, and no plans to implement that in future.
