### ISSUE TITLE
E31 when using USB stick

### ISSUE THREAD

**Issue by Atomfusion1** [keirf/FlashFloppy#160]
When Using .img files for dos on a PC or machine with the DSKA0XXX.img format you Must have the DSKA0000.img File, Can a USB stick setup be added to initial setup Wiki, Saying:

Format USB stick to Fat32: Allocation size 16 kilobytes (will NTFS work ? Fatex does not work )
The FF.CFG file just needs to be put in the root of the USB Stick 
if using DSKA0XXX.img file format ( or others ) you must have image DSKA0000.img 

Thanks

**Comment by keirf** [comment]
Update wiki Initial Setup page with USB drive formatting requirements.
