### ISSUE TITLE
FYI: photo of pullup-resistor mod

### ISSUE THREAD

**Issue by jknGH** [keirf/FlashFloppy#166]
Hi there - I wasn't sure how best to get this to you so thought I'd add this issue...

Firstly, thanks a lot for FlashFloppy! I am hoping to use it with my old Ensoniq SQ-80 Sequencer.

I have managed to program my Gotek HW but had to add the pullup resistors as mentioned in a few places. Somewhere on the wiki there was a request for a photo of this, so I have taken one of the mod I made (attached). Perhaps you would like to add it into the wiki at the appropriate place.

I used 22K0 resistors in 10K0 resistors. You will see I used thin (wire-wrapping) wire to wire the common end of the resistors to +Ve. This was mainly to be able to avoid the mounting hole nearby.

Of course, it would be better to make this mod to the USB to TTL adapter where it perhaps belongs, instead of on the Gotek. Interestingly, on my cheap adapter there are some missing SMD resistors, and having buzzed those out I think that fitting those would provide the necessary pullups. However I had the wired resistors to hand and so chose to do in on the Gotek.

As it happens, this still wasn't enough to be able to program the STM - with stm32flash I kept getting 'can't init device'. I started adding some fprintf()s to the code to see what was going on, and to learn more about the protocol ... and things started working! Perhaps there is a timing issue there, but I didn't investigate further; I only needed to program things once, hopefully.

    HTH
    Jon Nkeepassxc
![imag2254](https://user-images.githubusercontent.com/11761588/45325162-176b9780-b548-11e8-827d-ce1d9bd98409.jpg)

**Comment by keirf** [comment]
Thanks, cropped and added to wiki.
