### ISSUE TITLE
Bug or Feature-Request(?!): HXC-Mode-Image-Select-CMD

### ISSUE THREAD

**Issue by BeCube1** [keirf/FlashFloppy#170]
The HXC-Firmware has some direct-access-commands (the 04 "CMD_SELECT_IMAGE_INDEX" seems not to work?):
01: CMD_SET_LBA "This command change LBA base address and the number of sector to read/write"
02: CMD_SET_TRACK_POS "This command change the track position."
03: CMD_???: "This command enable/disable the 300RPM mode. "
04: CMD_SELECT_IMAGE_INDEX
"When the floppy emulator is in indexed mode or file selector mode this command allows to 
select the image number to load.
 parameter_0  = Image number to load (LSB) 
 parameter_1  = Image number to load (MSB) 
 The last selected/loaded image can be read in the current_index  field of the status sector."

The ff.cfg has only one line:
"nav-mode = default"

Is the 04er CMD supported?

**Comment by keirf** [comment]
It is not currently supported. Is there software that uses it? Do you want to use it?

**Comment by BeCube1** [comment]
Yes, my new Amstad MassdeviceOS:
http://www.cpcwiki.eu/forum/applications/cubeios-fat16fat32-rom-for-the-cpc's-with-xmass/
The 04er CMD i Need on the HXC-Firmware to "CD" / ChangeDir into an HFE-Image and select the active Image for the HXC/Gotek-Hardware,

**Comment by keirf** [comment]
Ok, so is your approach to dynamically create an HXCSDFE.CFG file while in LBA-modus and then drop out of LBA-modus with CMD-04?

**Comment by keirf** [comment]
Why not just write the desired slot number into the hxcsdfe.cfg file? That is what the hxc selector program (autoboot.hfe) does. It seems that is all you need, and then use the change-track-number cmd to exit lba-modus. That should work on both HxC and FF.

**Comment by BeCube1** [comment]
The HxC didnt monitored the file, so a CMD04 is necessary to switch to the Slot.
i dont know, which slot is at the moment the actual slot, which the user choosed.
And i dont't know too, if it's actual an Image inserted or not.

The LBA mode work equal on both (HxC and FF), Enter LBA, Use LBA, Exit LBA.

**Comment by keirf** [comment]
Perhaps you test an old HxC firmware version? AUTOBOOT.HFE on Atari ST and Amiga was updated last year to add a reboot-to-currently-selected-slot option. When this key is pressed, the host reboots and runs the current highlighted slot. This feature does not use the CMD-04 -- it simply writes the new slot number into HXCSDFE.CFG, seeks to track 0, and reboots.

I recall that this feature needed an HxC firmware update. I would guess that is so that the firmware correctly monitors updates to HXCSDFE.CFG.

Anyway, worst case, I suggest you both update HXCSDFE.CFG *and* execute CMD-04 (which is a no-op on FlashFloppy). That should suffice to work on both HxC and FF.

**Comment by BeCube1** [comment]
I'm using the latest HXC-Firmware (SD-Card): "29 September 2013: v1.8.2.40".
Autoboot.hfe is only the File-Selector, not the Firmware.
I think, they write the "Last loaded images (non-slot mode)" (0x200) in the "HXCSDFE.CFG"-File.
But i never have success to load this Image.

Btw, do you think it's very user-friendly, to reboot the Computer everytime, after a CD-Command? ;-)
The CMD-04 does not Support the 0x200-Image (Jeff told me)

**Comment by keirf** [comment]
Well you don't need to reboot the host computer of course. But FF will pick up on new slot if you write it into the slot_index field in HXCSDFE.CFG (ie. byte at offset 0x17). Is that sufficient?

**Comment by keirf** [comment]
Okay, so that dummy HFE file you need in the root-dir (#171)? You need to call it AUTOBOOT.HFE.

FlashFloppy only enters HxC-compatibility slot mode when you insert a USB stick with both AUTOBOOT.HFE (just needs to be any file with that name I think, even zero sized) and HXCSDFE.CFG (needs to be a valid well-formed file).

Then I think this will work...

**Comment by BeCube1** [comment]
Seems to work :-)
I'm using a 0Byte AUTOBOOT.HFE and no ff.cfg. 
HXCSDFE.CFG with "Load last loaded floppy" & "Enable Auto boot mode" = yes, all other params = No

I must do deeper tests..... (Need some time)
At the Moment "BIG THANKS" :-)

**Comment by keirf** [comment]
Pleased to hear it. I actually removed mention of 0-byte HFE from my comment as I thought it wouldn't work. Actually it's kind of a bug that it does (it falls back to the Amiga ADF handler, which is missing a zero-length-image check), but perhaps one that I will keep.

Regarding HXCSDFE.CFG, "Load last loaded floppy" is ignored by FlashFloppy. As are a lot of other options. If there are any that you need to be properly recognised by FF, let me know.

**Comment by keirf** [comment]
How about I make it work without AUTOBOOT.HFE too, and display No-Autoboot for slot 0 on LCD/OLED? Would that be nice?

**Comment by BeCube1** [comment]
You must decide.

Either i documentate to the Amstrad Guys "Place 0 Bytes AUTOBOOT.HFE" or "Place no AUTOBOOT.HFE" in root.

Actual the 0 Byte solution seems to be work.

For me it's only a difference for the documentation.

**Comment by keirf** [comment]
Could you try the following firmware? It should work with just HXCSDFE.CFG and no AUTOBOOT.HFE file at all. You should find it breaks the zero-sized AUTOBOOT.HFE workaround you're currently using (I fixed the bug in the Amiga ADF handler).

[ff_170_1.zip](https://github.com/keirf/FlashFloppy/files/2438458/ff_170_1.zip)

**Comment by BeCube1** [comment]
Cool, cool, cool, cool :-)
It seems that all are functional. So i will give one Beta-Tester my new ROM & the following informations (OK?) (at the Moment he must use the 170_2 Firmware, but when you finally release it, it has an Version >= v0.9.30a ?!):

Firmware < v0.9.30a
You must have at least one HFE-File in the Root-Directory.
The Gotek must not show you an Error on the Display.
Else the FlashFloppy-Firmware can't swith to LBA-Modus.
Else you need an 0 Byte AUTOBOOT.HFE in root

Firmware >= v0.9.30a
Nothing to pay attention to ;-)

**Comment by keirf** [comment]
Correct!

**Comment by keirf** [comment]
The changes are now committed to master and I have updated the wiki to make it clear that AUTOBOOT.HFE is no longer mandatory for HxC Compatibility mode.

**Comment by keirf** [comment]
Fixed in v0.9.30a
