### ISSUE TITLE
Alternate host HW for FlashFloppy?

### ISSUE THREAD

**Issue by staticmem** [keirf/FlashFloppy#174]
Yesterday whilst looking at what is around in the way of ST development boards I found the following board, these are common on eBay, etc.
The MCU has 1mb Flash and around 192kb of SRAM so more than enough capability.  More information in "See more product details" link.

https://www.amazon.com/Diymore-STM32F407VGT6-Cortex-M4-Discovery-Development/dp/B01M7YB5HF
Schematic here:

http://dubstylee.net/v/wp-content/uploads/2017/08/DIY-More-STM32F407VGT6.png
Any interest in porting the FF code to it?  I would think it would be fairly straight forward.

I've not looked at the Gotek schematic for a while but probably just requires and additional interface PCB with 34W connector and other connections for the display, buttons, etc.
It would at-least make it easier to interface to other I/O lines on the MCU for new features.

I'd be prepared to knock up Gerber files for an interface board if it is suitable and a design was settled on.

What do others think?

**Comment by staticmem** [comment]
It would need some open collector type drivers to interface to the 34W.  The Gotek uses some N-CHAN MOSFETs.  Some 2N7000 would probably suffice and are cheap.

**Comment by keirf** [comment]
FlashFloppy would need some changes to target the Cortex-M4. Startup code, USB stack, pin and peripheral assignments, linkage map, ... Nothing very major (except perhaps sorting out the USB stack).

**Comment by staticmem** [comment]
> FlashFloppy would need some changes to target the Cortex-M4. Startup code, USB stack, pin and peripheral assignments, linkage map, ... Nothing very major (except perhaps sorting out the USB stack). Also the M4 memory model is more relaxed, so would need to check the impact of that.

**Comment by keirf** [comment]
Question really has to be what's gained. There is capacity for new features obviously, but what might they be.

**Comment by staticmem** [comment]
Well for starters it could have several of these to fit one 3.5" drive space each sharing the same 34W interface and own USB socket, each could have own drive select lines and with it's own display if you wanted.
I know all that could be accomplished in the one MCU but the current MCU in the Gotek must be getting a bit tight on memory constraints?

I'm sure the hackers out there would like the extra flexibility it would no doubt provide.
As for what is gained, for one thing it makes it a true open source project from the HW side of things rather than using the Gotek HW which is believe is a propriety closed design.  The schematics about the place appear to have been reversed engineered?

**Comment by drdpj** [comment]
Given that we have the schematic for the gotek and several people have
rendered it into various other formats, if you're going to the effort of
producing gerbers, just build the extended gotek based on the same ARM chip
rather than trying to interface a board that's not quite compatible? It
will likely end up cheaper too.

**Comment by drdpj** [comment]
- in so far as the gotek "isn't open", there are only so many ways to
interface an arm mcu with an fdc... I don't think there's much ip in
assigning specific gpios :D

**Comment by staticmem** [comment]
In all likelihood the MCU *should* be easy enough to port over to although I have not looked into it in any detail as I just have too many things on my plate,  I do have considerable experience using STM32F106xxx MCU that is same as the Gotek but has far less RAM.  Google "floppyio microbee" (I use a different alias over there).  The purpose of that is for reading floppy disks to make disk images.

**Comment by keirf** [comment]
> Well for starters it could have several of these to fit one 3.5" drive space each sharing the same 34W interface and own USB socket, each could have own drive select lines and with it's own display if you wanted.
> I know all that could be accomplished in the one MCU but the current MCU in the Gotek must be getting a bit tight on memory constraints?

This argues for a new board design rather than a new MCU. There's no compelling reason to move to the STM32F4xx series, or away from STM32F105 at all, at the present time.

**Comment by staticmem** [comment]
> > Well for starters it could have several of these to fit one 3.5" drive space each sharing the same 34W interface and own USB socket, each could have own drive select lines and with it's own display if you wanted.
> > I know all that could be accomplished in the one MCU but the current MCU in the Gotek must be getting a bit tight on memory constraints?
> 
> This argues for a new board design rather than a new MCU. There's no compelling reason to move to the STM32F4xx series, or away from STM32F105 at all, at the present time.

Possibly not,  Have you ever soldered down 0.5mm pin pitch ICs?  If so you will know the difficulty involved if you only have hobby equipment.

Then there is all the small parts it requires around it.  It would cost more just to purchase the individual parts.  I have soldered such parts in the past (well over 10 years ago NXP ARM parts) but my eye sight was much better then.

So the option is to use pre-assembled break-out boards even if the MCU is more powerful then what might be needed.  I would have used this on my Floppyio project if they were around at the time.

So I'm not quite understanding the resistance I'm seeing in the replies here.  If anything it supports your FF project.

Anyway as stated before just my 2c worth. :-)

**Comment by keirf** [comment]
> > This argues for a new board design rather than a new MCU. There's no compelling reason to move to the STM32F4xx series, or away from STM32F105 at all, at the present time.
> 
> Possibly not, Have you ever soldered down 0.5mm pin pitch ICs? If so you will know the difficulty involved if you only have hobby equipment.
> 
> Then there is all the small parts it requires around it. It would cost more just to purchase the individual parts. I have soldered such parts in the past (well over 10 years ago NXP ARM parts) but my eye sight was much better then.
> 
> So the option is to use pre-assembled break-out boards even if the MCU is more powerful then what might be needed. I would have used this on my Floppyio project if they were around at the time.

Okay this is at least a rational argument. :) However...

> So I'm not quite understanding the resistance I'm seeing in the replies here. If anything it supports your FF project.

Porting to a different sub-family of the STM32 series would be many hours of work, and require shipping of separate binary images (ie. it complicates/confuses release packaging). That LQFP is difficult to hand solder is not reason enough for me I'm afraid.

**Comment by staticmem** [comment]
Why does it need to be closed?
