### ISSUE TITLE
Amstrad PPC640 & PPC512

### ISSUE THREAD

**Issue by tolmdyn** [keirf/FlashFloppy#176]
Not really an issue, but just something that might be worth adding to the Platforms wiki page.

Took me a bit of head scratching to figure out why FlashFloppy with an Amstrad PPC640 wasn't working properly, not recognising disk image changes.

According to the service manual the Amstrad uses a _shugart_ not _ibm_ pinout on the floppy connector, which might seem a bit counter-intuitive as it's labelled as IBM compatible. I had it set to "interface = ibmpc" in the cfg file thinking this was what it needed. 

Otherwise works perfectly when set to shugart mode in cfg file and jumper on S0.

**Comment by keirf** [comment]
Thanks I have added a mention in Host Platforms -> IBM PC.
