### ISSUE TITLE
Sam Coupe Error 'Missing Disk'

### ISSUE THREAD

**Issue by weirdocollector** [keirf/FlashFloppy#181]
Hi!

I've connected a Flash Floppy Gotek to my Sam Coupe using the Quazar Floppy Interface [https://www.samcoupe.com/hardfdc.htm](url), which is based on a 1772 controller, and it's impossible to read any .dsk image due to the 'Missing Disk' error, as the disk insertion appears to not be recognized by the Sam.

I've used a physical floppy with the same Quazar interface, and it works well.

Any idea on why this happens?

Thanks!

**Comment by keirf** [comment]
Needs a jumper at JC (rear of Gotek) possibly?

**Comment by weirdocollector** [comment]
I've tried putting a jumper on JC with the same result: Missing disk (Error 55)

**Comment by keirf** [comment]
It will almost certainly be a jumpering issue all the same. Some combination of jumper at S0 vs S1, and jumper at JC or not.

Are you also confident you have a good disk image mounted in the Gotek?

**Comment by weirdocollector** [comment]
Yes, the image is OK. I've tried it with a SAM emulator and another SD card solution for the same micro.

**Comment by weirdocollector** [comment]
Yay! Jumper on S1 (no JC) did the trick! Case closed.
