### ISSUE TITLE
Typo in Linux Command

### ISSUE THREAD

**Issue by ldkraemer** [keirf/FlashFloppy#183]
On the Wiki Page, under the Linux/Mac Header

https://github.com/keirf/FlashFloppy/wiki/Firmware-Programming

Linux / Mac

This command has a typo for the dfu-util command:
sudo sfu-util -a 0 -s :unprotect:force -D FF_Gotek-v0.10.dfu

It should be:
sudo dfu-util -a 0 -s :unprotect:force -D FF_Gotek-v0.10.dfu

Thanks.

Larry

**Comment by keirf** [comment]
Now fixed thank you.
