### ISSUE TITLE
Roland DJ-70 Strange behavior

### ISSUE THREAD

**Issue by altaygenc** [keirf/FlashFloppy#185]
I'm using FF version v0.11 with GOTEK hardware on Roland DJ-70 sampler. Here is a strange behavior:
When I "insert" the disk image, on the roland screen it says "insert disk", when i eject the disk with rotary encoder switch (which i can read EJECTED on gotek screen), the sampler can not write/format due to "write protection" that i read from the sampler screen.
In short, i can not read becouse i can not insert. i can not write/format becouse i have write protection.

I've tried, different cableing (cross plug the floppy data cable), different jumper settings, changing FF.cfg file, vs. nothing changed the behavior.
Any suggestions? Maybe the "disk ready" signal is mismatched.. maybe i need to add resistor components vs vs..

**Comment by keirf** [comment]
I have no direct experience of Roland synths I'm afraid. However see here for some relevant advice:
https://torlus.com/floppy/forum/viewtopic.php?t=916

I think you need to place jumpers at positions S0 and JC at rear of Gotek. Erase your FF.CFG and clear the cached config by holding both buttons for a few seconds *after* power up but *before* inserting your USB stick. The display will change while the cached config is being cleared.

Now hopefully insert/eject detection works properly, and you can read a system disk image. If not then perhaps you need resistors as suggested in above forum post.
