### ISSUE TITLE
Filename extensions - provide config option to allow display of extension part of filenames.

### ISSUE THREAD

**Issue by bluearcus** [keirf/FlashFloppy#187]
Sometimes a single directory has different versions of a disk with differing file extensions. Please allow the display to include this extension information if configured appropriately.

**Comment by keirf** [comment]
The extension is already displayed on line 2 during navigation.

**Comment by bluearcus** [comment]
Ah ok, missed this. It's displayed initially, then disappears at disk selection time. So with the default 2s auto-select, it's gone after that period. No problem.
