### ISSUE TITLE
FlashFloppy 720k (follow up)

### ISSUE THREAD

**Issue by DonovanPhoenix** [keirf/FlashFloppy#188]
Hello i have a Question about FlashFloppy and 720k
I'm not sure where to post these questions to so i guess i will put this here
This is a follow up on the closed thread:
https://github.com/keirf/FlashFloppy/issues/106

I see in that thread they discuss a question if the gotek SFR1M44-*** and SFRM72-*** can handle the same FlashFloppy. The answer was Yes.

The OP also asks if the FlashFloppy firmware can emulate 720k DD disks. The answer was Yes.

My question is can the FlashFloppy firmware emulate a 720k drive? like the SFRM72-***.
and how to i do that if possible

My problem is that i want to get it to run on a old machine that uses 720k DD disks exclusively. The disks are Definitely IBM compatible because they are formed (FAT) by a 1.44mb capable usb to Floppy Disk attached to a windows pc. they are formatted to a size of 720k on a 720k DD disk.

I have a SFR1M44-*** but i actually need a SFRM72-***. Since they (in the linked post) said the FlashFloppy firmware works on either because it's using the same hardware.I had a look at FF.CFG but its not clear what i should select to emulate a 720K DD drive.

lastly how do i get data onto the images on the Flash drive. what software ?

**Comment by keirf** [comment]
There is no need to manually select 720k vs 1440k emulation, the right thing happens automatically according to the size of IMG file that you mount in FlashFloppy (i.e., according to whether that IMG file is 720k or 1440k in size).

To get data onto the images on the Flash drive... well, these are IMG files, so you mount them in FlashFloppy and then access them from your connected retro PC. Or, if you want to pre-load your images with data on a modern PC, I believe you can mount IMG files in eg Windows 10 by right-clicking them in File Explorer and select "Mount". Then you can access them like a floppy disk.
