### ISSUE TITLE
PC disks 720KB (or others) support

### ISSUE THREAD

**Issue by chapas** [keirf/FlashFloppy#19]
Hi,
you are (maybe) sick of ear this but: Thanks for your awesome work on the Gotek.

720KB is possible on the Gotek right? Is it on the flashfloppy road map?

Regards

**Comment by keirf** [comment]
720kB will already work, as an IMG or HFE format image.

Don't forget to put a jumper on JC, or configure interface in FF.CFG, if connecting to an IBM-PC compatible.
