### ISSUE TITLE
Linux / Mac Firmware Programming Description misses jumper settings for Gotek

### ISSUE THREAD

**Issue by refcodes** [keirf/FlashFloppy#194]
First of all, great work! Your Firmware adds so much more value to the Gotek drives!

Though I had some "trouble" flashing the firmware on Linux with `dfu-util` when following the wiki article https://github.com/keirf/FlashFloppy/wiki/Firmware-Programming#linux--mac. After following some links in the according above Windows section I came accoss the jumer-setting on http://www.binarydevotion.com/?p=228.

I think it would help newbies like me if you could mention the jumper settings on the Linux section in the Wiki:

> "You need to connect pin 1 to 2, and 3 to 7 (across the diagonal, yes, and a standard jumper won’t reach)." (taken from http://www.binarydevotion.com/?p=228)

And also maybe the image to clarify things:

![Jumper settings for flashing the firmware on Gotek drives](http://www.binarydevotion.com/wp-content/uploads/2018/02/Gotek.png "Jumper settings for flashing the firmware on Gotek drives]")

I used wire jumpers "male-male" because there were no pins soldererd onto the Gotek board. Jumpers as such:

![Wire jumpers male-male](https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/A_few_Jumper_Wires.jpg/220px-A_few_Jumper_Wires.jpg
 "Wire jumpers male-male]")

Thanks once again for the great work! I got my Gote now up and running in an Tatung TC-01 Einstein :-)

**Comment by keirf** [comment]
Sorted, by explicit reference to the guide on binarydevotion.com.
