### ISSUE TITLE
Yamaha Electone EL-500/EL-700/EL-900 compatibility

### ISSUE THREAD

**Issue by Tim5000** [keirf/FlashFloppy#196]
I've just bought a GOTEK (3x 7 segment digits) for my Yamaha Electone EL-700 and would like to confirm the correct jumpers/configuration file (if required).

It would be good to determine the proper jumper configuration and add this to the host platforms wiki.
I haven't yet flashed it (or fitted it) so it's as-is from the seller, but I read on the Hxc page that the yamaha needs to support disk change on pin 34: https://torlus.com/floppy/forum/viewtopic.php?t=1406#p11781
However I haven't got a clue what to set
Supposedly the Gotek should work in it's default form - but I'd rather run this :) 

I believe the yamaha takes .evt and .b00 files, but maybe also supports .IMG files. I'm not entirely sure as I'm new to this.
Regards

**Comment by keirf** [comment]
You probably need `interface = ibmpc-hdout` in FF.CFG file in root of your USB stick, to set the correct usage of interface pins 2 and 34. I don't know the Yamaha disk format, with a bit of luck it uses regular PC-formatted disks and you can use IMG files?

**Comment by Tim5000** [comment]
Excellent thanks. From talking to another person with one of these instruments the disks are standard PC format and just copy the musical files on, so yes hopefully standard IMG files.
I'll leave this open until proven, and then the wiki can be updated for other users.

**Comment by keirf** [comment]
Any update on this?

**Comment by Tim5000** [comment]
FlashFloppy works in the Yamaha EL-700 :)
I still didn't get a reply on the disassembly so I just went for it tonight.
I ended up with both jumpers JC and S1 fitted - it wouldn't work without S1 fitted (as could be reasonably expected). I also set the config to `interface = ibmpc-hdout' as suggested.

In terms of image format the only one I downloaded (that should be a known good one) didn't work - I got an E31 error code for bad image format. I own the actual disk so on linux dumped it using `dd` and that worked fine. I suspect the downloaded one may have been patched using HD-COPY or some other tool because it's supposed to work in the standard Gotek. I haven't compared the two images myself but it's possible it requires the hxc compatiblity or something. I'm happy to provide them if you think there's a possiblity it's a format not supported by any of the configuration options.

**Comment by keirf** [comment]
Feel free to attach the images here and I will take a look. If you change to `interface=jc` in FF.CFG does that work too?

**Comment by Tim5000** [comment]
Apologies this took so long.
The images are attached: [yamaha-EL700-images.zip](https://github.com/keirf/FlashFloppy/files/2922260/yamaha-EL700-images.zip)
The working one is taken by me via `sudo dd if=/dev/sdb of=./<image name>.img`
The not working one I received from someone on the yamaha forum with a GOTEK (presumably running the original firmware) and presumably uses a tool to write the images to the USB stick.

I've also just tried `interface=jc` and it seems to work exactly the same for the couple of images I cycled thought.

Thanks!

**Comment by keirf** [comment]
Then I recommend stick with `interface = jc`

**Comment by keirf** [comment]
The shorter image file is simply not a valid size and also doesn't have a valid FAT so it's probably just garbage, or at least not an IMG file. You could try padding it to size using `dd` for example?:
```
# dd if=/dev/zero of=bad.img bs=1 seek=1355701 count=118859
```

**Comment by Tim5000** [comment]
No problem - I'm happy with generating my own from my disks so that's OK.

So at least you can mark this as a supported device for the Yamaha Electone EL-700 on the wiki/readme etc if you want to :)
It should be fine with the EL-900 too as is, but be careful not to mark as all electones because I know the EL-90 for instance uses a different interface. Again I'm sure it would work with them but probably needs a different config like the shuutgart.

Thanks again for the help - it's been working brilliantly for me. My only issue is I have so many images on it I need a cheatsheet of what disk is in what slot (I'll have to do the OLED mod)!
