### ISSUE TITLE
Hardware details needed

### ISSUE THREAD

**Issue by szg0000** [keirf/FlashFloppy#2]
Hi!

Can you share the schematic?
Can this firmware replace the original Gotek read-protected firmware?
Can this firmware handle bigger pendrives/images than 1.44 MB?

**Comment by keirf** [comment]
This firmware does not currently target Gotek hardware as it does not 
have a working USB stack. It functions on my own similar hardware with a 
touch screen and SD card reader.

szg0000 wrote:

**Comment by keirf** [comment]
The schematic is in the hardware branch of this repository. See pcb/MM/150, pcb/LC/150, pcb/TB/161 for schematics and layouts in Kicad format for boards based on various STM32F103 dev boards.

**Comment by lovrenco** [comment]
Long time since then @keirf ... :)
Why not develop something for Gotek since you have the knowledge for it? Gotek is still produced and available on very affordable price.

**Comment by keirf** [comment]
This firmware will be fairly easy to retarget to Gotek in due course as that is a more capable chip than STM32F103x. It will just need a USB stack to be added, probably ST's free one.

**Comment by lovrenco** [comment]
Any chance to see that firmware soon?

**Comment by keirf** [comment]
I need to knuckle down and finish the STM32F103 firmware, then I will look to retarget at Gotek. Such things are perpetually 'a few months away' as other repair work and so on keeps pushing development back.
