### ISSUE TITLE
AKAI S1100, S1000 disk issues

### ISSUE THREAD

**Issue by nickmcca** [keirf/FlashFloppy#200]
I know it's been reported previously S1100 not working correctly but even with those Pin 2 and 34 settings on S1100, still seems to have strange behaviour on AKAI S1100, S1000 

S1100 / S1000 - Gotek FF
When loading disks, seem to load _most_ of the time but displays "trying other density...."

When formatting - sampler begins the formatting process then end up with either 
"! ! DISK UNUSABLE - BAD DIRECTORY AREA ! !"
" WARNING DISK MAY BE UNRELIABLE" 

S2000 - Gotek FF 
Loading disks, doesn't detect the hfe files (or boot the OS which is stored in DSKA0000.hfe) 
Unless there is an HXCSDFE config file added to the USB stick (and added in FF config to use compat mode)  then mysteriously loads....

When formatting - won't format HD (same issue as S1100) but sometimes Low Density does work.  

Any ideas? Thankyou!

**Comment by keirf** [comment]
Are you using HFE images? Have you tried IMG image files (requires `host=akai` in FF.CFG)?

**Comment by nickmcca** [comment]
Thanks for reply -  no not yet! Will find some img files and try that.....
