### ISSUE TITLE
d-R or d-A error message

### ISSUE THREAD

**Issue by vaskag** [keirf/FlashFloppy#201]
In gotek with latest firmware (1.0), running HxC manager,  I get this 3 digit error if I have in the usb, separate folder for each letter of the alphabet. Is it because of the many folders? Is there a limitation on folders?

**Comment by keirf** [comment]
This is expected, it just shows the Gotek is in file selector mode. Display should return to normal when you exit the selector.

**Comment by vaskag** [comment]
Ok I didnt notice that it was ok. thank you
Is there a limit to how many files can exist in the usb? Because in the above scenario with 24 folders and 4000+files the hxc manager only shows 3 out of 24 folders and cannot load anything.

**Comment by keirf** [comment]
There should be no such limitation. Is this on Amiga?

**Comment by vaskag** [comment]
Amstrad cpc 6128

**Comment by keirf** [comment]
I don't know so much about the Cpc selector. I would have to test it myself. But right now I don't do my own builds of it.

**Comment by vaskag** [comment]
If I put all the files (4000+) in single folder, the manager works and loads the files. I think the problem is when inside the folder, are 24 additional folders.

**Comment by keirf** [comment]
It's probably a selector bug. The cpc selector is the only 8 bit selector and is a different code base than Amiga and ST

**Comment by vaskag** [comment]
Ok. Thank you for the feedback
