### ISSUE TITLE
Akai S2800 DD Disk issue

### ISSUE THREAD

**Issue by chrispoacher** [keirf/FlashFloppy#204]
Hi, 

I'm (almost)-happily running FF on my AKAI 28000 which has to use AKAI S-950 mode or it will not work at all.  It works fine for HD .IMG files (1600k), but when I try to load working DD .IMG files (800k) it crashes the sampler.  I tried changing the config of pin 34 to dens, which then thankfully doesn't crash the sampler when you try to load an image, but just says NO DISK, which tbh is much better than locking up the Operating System :)  

Has anyone else had this issue and solved it, it's most probably just changing the settings for PINS 02 & 34 manually in FF.CFG but I'm not educated enough in Akai floppy dynamics. ;)

The only other thing is to convert all my 800k images one by one and save them (on another Akai sampler) onto blank 1600k image files so the S2800 can read them. Doing that over 150 times will get a bit tedious tho. 

**The 800k DD images in question all work fine on the S950, S01, S2000, S3000XL, CD3000XL, S20. I will trying soon in a CD3000i which technically should have the same setup as the S2800, but then again who knows...  :)

Cheers,
Chris

**Comment by keirf** [comment]
This sort of question probably belongs on a suitable special interest forum or group. There's not a large audience here.
