### ISSUE TITLE
IMD ImageDisk support

### ISSUE THREAD

**Issue by dandoore** [keirf/FlashFloppy#205]
Any chance of having native IMD support for CP/M etc, I see it’s supported as part of the disk tools?

**Comment by keirf** [comment]
No, I have now added a full answer to the Wiki FAQ: https://github.com/keirf/FlashFloppy/wiki/Troubleshooting-FAQ#image-formats

**Comment by dandoore** [comment]
Ah, ok - many thanks for the info!
