### ISSUE TITLE
Firmware update

### ISSUE THREAD

**Issue by vaskag** [keirf/FlashFloppy#206]
In the flashfloppy-v1.0 zip we have FF-Gotek-v1.0.upd and in the reloader folder, the FF_Gotek-Reloader-v1.0.up. What is the difference between these too?

**Comment by keirf** [comment]
The Reloader file is for updating the bootloader. Not usually necessary. See the docs: https://github.com/keirf/FlashFloppy/wiki/Firmware-Update
