### ISSUE TITLE
Support for Amiga ADZ Images

### ISSUE THREAD

**Issue by aeromaxx** [keirf/FlashFloppy#208]
I'd love to see some support for ADZ images, as these are compressed with gzip/zlib and mean we can squeeze more out of smaller USB sticks, or having more games at our disposal when using USB sticks of a decent size that we happen to have lying around.

**Comment by tenuke** [comment]
Afaik gotek has no RAM for decompressing algorithms. Quality
16GB usb sticks cost like 4 dollars
Its time to bin old 512MB sticks and so :D

su 10. maaliskuuta 2019 klo 16.40 Daniel T <notifications@github.com>
kirjoitti:

**Comment by tenuke** [comment]
https://github.com/keirf/FlashFloppy/issues/195#issuecomment-451206062

**Comment by keirf** [comment]
Yes indeed, not going to happen. I should add this to the Wiki's FAQ.
