### ISSUE TITLE
Filename length limit?

### ISSUE THREAD

**Issue by BrianGilbert** [keirf/FlashFloppy#21]
I'm seeing some weird behaviours with multidisk files and filename length, is there a hard limit to filename length in the firmware?

**Comment by keirf** [comment]
Firmware will correctly handle filenames up to 256 characters. However it will only ever display up to the first 50 or so characters on an LCD/OLED display. This can be improved upon in direct navigation mode (no Autoboot) -- this ticket can track that fix.

**Comment by keirf** [comment]
This is fixed in master c/s b269d0347afb85794e0b3fc71e1fbf72114df638. Will be in next release (0.9.7a).
