### ISSUE TITLE
Feature request: Clone real floppy.

### ISSUE THREAD

**Issue by SilverGreen93** [keirf/FlashFloppy#212]
Is it possible to add the feature of converting real floppies to IMGs?
I would imagine it like this: Connect the real floppy disk drive to the floppy bus, make FlashFloppy act as a floppy controller to read (or even write) the real disk to a floppy image file on the flash drive.
It would be of great use.

**Comment by keirf** [comment]
If you are connecting to an existing floppy bus, most hosts can copy between drives?

It is not trivial to connect Gotek as a floppy controller anyway, as all its inputs would become outputs, and vice versa. It would mean remapping the floppy header pin assignments and using an adapter board or cable.

So overall it is not easy and outside project scope. I am doing another project down the road (Greaseweazle, also on Github) which will allow to connect a real drive to a PC for read/write. And I have existing tools to convert the dump format to/from IMG files, which could then be transferred to/from FlashFloppy on USB stick. This is already a possibility if you have Supercard Pro or Kryoflux, but my solution would be cheaper (when it exists ;) ).
