### ISSUE TITLE
XDF in IMG.CFG

### ISSUE THREAD

**Issue by techana** [keirf/FlashFloppy#214]
I just knew about IMG.CFG. I'll look deeper into it, but would like to know if it can be used to define XDF images for OS/2 systems?

(I'll keep this thread updated with my findings)

**Comment by keirf** [comment]
No it cannot, as XDF has different geometry on different tracks, and variable sector sizes. This cannot be represented in IMG.CFG (at least not yet) and in fact the Raw track generator in FF cannot generate such tracks (yet). Direct XDF support is planned. It will be tracked in #54 hence I will close this ticket.
