### ISSUE TITLE
sub folders wrong asc order

### ISSUE THREAD

**Issue by alexpad** [keirf/FlashFloppy#222]
Creating USB folders tree from /GAMES/A to /GAMES/Z the folders order in GAME is:

[..] **T** A B C D E ... R S U V ... Z

T folder is showed between [...] and A and not between S and U

**Comment by keirf** [comment]
Folders and files are shown in filesystem order. Any alphabetical ordering is purely coincidental. Run your USB stick through a fat sorter (many options, Google them)

**Comment by keirf** [comment]
Keeping open until I add this to the wiki faq

**Comment by alexpad** [comment]
Thank you for the trick... Do you think that this issue can be solved in a future release?

**Comment by keirf** [comment]
Yes this is tracked already by #25

**Comment by keirf** [comment]
Fixed in v2.7a
