### ISSUE TITLE
ATR - slow loading with 2.4a/XF551 board

### ISSUE THREAD

**Issue by excommie** [keirf/FlashFloppy#223]
I just tried the Gotek with 2.4a and XF551.  However, the load process is slow, it seems like it is missing the next sector?  

Please review the video I uploaded (turn on volume).

https://www.youtube.com/watch?v=_OGTVQXotDE

**Comment by keirf** [comment]
Do you know how fast it should be?

**Comment by keirf** [comment]
And how big is the ATR file?

**Comment by keirf** [comment]
Here is a firmware for you to test. It has a couple of changes:
1. Significant sector interleave to account for slow SIO transfer speeds.
2. Speeds up the bitrate (better match for XF551).

[ff_223_1.zip](https://github.com/keirf/FlashFloppy/files/3097288/ff_223_1.zip)

**Comment by excommie** [comment]
This new firmware fixes the slow loading issue.
Thank You - this is an awesome development for 8bit Ataris.

To answer you other question - 2.4a was about 50% slower than loading from a physical media with all ATR file sizes.

**Comment by keirf** [comment]
Thank you. Could you also check writes work okay too? A simple file save would do.

**Comment by keirf** [comment]
Also there may be scope for a little more speed up. I don't know if atari floppies were skewed track to track. That might be the case if flashfloppy is still 5-10% behind real floppy.

**Comment by excommie** [comment]
OK, will try writing tonight.  This is great, thanks again.

**Comment by excommie** [comment]
I loaded Dos 2.6f via the Gotek.  Then I selected another disk image on the Gotek, and formatted it.  Then I wrote the Dos files to this new virtual drive.  I then booted from this drive.  I did not encounter a single problem.  All is working without a hitch.

**Comment by keirf** [comment]
Okay thanks. Closing now. Fixed in v2.7a
