### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by 256colors** [keirf/FlashFloppy#226]
Feature request: Enable/Disable as main drive A or B
I dunno if this is possible?
I will explain my situation on my Atari1040 STE i have external drive i sometimes want to use as main drive A without conflicting with my Gotek drive

**Comment by keirf** [comment]
This is a mod to be done for a particular host system and really has nothing to do with the Gotek (it's not under Gotek control).

**Comment by 256colors** [comment]
Okay no worries thanks for your time
I'm guessing there no other away of disabling the GoTek drive without removing it physically?

**Comment by keirf** [comment]
Need a physical switch at the very least, yes.
