### ISSUE TITLE
v2.9 does not work with Acorn ADF 800K images

### ISSUE THREAD

**Issue by Joebar18** [keirf/FlashFloppy#228]
I tried v2.9 image on Acorn A3000 and all Acorn ADF images read *ERR*31* on the display. Then I tried v1.2 stable and it works fine. It seems the 800k support got broken somewhere.

**Comment by keirf** [comment]
Thanks for the report, something bogus crept in while I was adding XDF support. I will fix this and release v2.10a immediately.

**Comment by Joebar18** [comment]
Works. Thanks for the great job!
