### ISSUE TITLE
Unable to update from SD card on enhanced Gotek

### ISSUE THREAD

**Issue by salacpavel** [keirf/FlashFloppy#229]
as a title says, I have tried to follow firmware update procedure off the SD card, but seems like FF update does not scan the SD card for .upd file at all.
Another issue I have observed is that SSD1366 OLED screen is not properly initialized, when Gotek is started to update mode. The good old pre-0.15 FW garbage is displayed instead. The same display I works in normal operation mode tho.

**Comment by keirf** [comment]
Update from SD card is not yet supported. I may add it.

Update mode runs in the bootloader, which is not usually itself updated. So you probably need to update your bootloader. See instructions here: https://github.com/keirf/FlashFloppy/wiki/Firmware-Update#updating-the-bootloader

**Comment by keirf** [comment]
I've fixed the SD card thing and will make bootloader update simpler in next release v2.11a. Look out for new Bootloader Update instructions in the wiki.
