### ISSUE TITLE
OLED display size cfg option

### ISSUE THREAD

**Issue by Kyp069** [keirf/FlashFloppy#23]
I have seen a note in the sources about changes needed to use an OLED 128x64 display but as I cannot rebuild the sources I would kindly ask for a option in the config file to specify what kind of display are we going to use. Thank you very much.

**Comment by MartinDejmal** [comment]
I tried 128x64 OLED display and contents displayed on the OLED remains the same, but is streteched to fill the whole screen. 
However why use bigger display? What else should it display other than image filename and sector/track?

**Comment by fordp2002** [comment]
A feature that will probably be needed for the DFS on the BBC and will be useful for other platforms too is having multiple images at the same time for drives and in the case of DFS sides of a disc.

**Comment by Kyp069** [comment]
My OLED display shows a first _scrolling like_ line with something that appears to be corrupted characters and the rest random pixels most of them ON.

There is not a real reason to use a bigger display, just it is the one that I have :)

**Comment by keirf** [comment]
Larger display is "supported" in teh way MartinDejmal describes. I will try to do more with the extra space in future. I can leave this ticket open to track it.

**Comment by Kyp069** [comment]
This is a snapshot of what my display shows: 

![01](https://user-images.githubusercontent.com/21128002/33258685-af9a2d58-d35a-11e7-9824-48cfd11b4761.jpg)

The top line es 'moving' like it was doing some kind of scroll but text is illegible.

Perhaps I am doing something wrong?

**Comment by keirf** [comment]
@Kyp069 This is fixed in v0.9.22a, put `display-type = oled-128x64-sh1106` in FF.CFG.

**Comment by Kyp069** [comment]
I can confirm it works 👍 
Thank you for the support :D
