### ISSUE TITLE
BUILD HARDWARE  FROM PCB

### ISSUE THREAD

**Issue by mrdavoudi1** [keirf/FlashFloppy#230]
Hi
I want to build BOARD from KICAD PCB design. so have some questions.
first , does the board support USB stick and 7-seg or O-LED? means usb mini port on "taobao mini board" can use as USB STICK port for programming and image reading , and 7-seg or O-LED can connect?
second , How can I program stm32 ? does itself has bootloader and just need to update by FlashFloppy updates?

**Comment by keirf** [comment]
The custom board design is obsolete. It uses a smaller STM32 chip (STM32F103) with much less RAM. It was never properly support by FlashFloppy and I completely removed the support some months ago.
