### ISSUE TITLE
Index mode requires HFE extension

### ISSUE THREAD

**Issue by leonkiriliuk** [keirf/FlashFloppy#231]
using flash floppy in my atari ST. In index mode file extensions have to be HFE. If files are ST extension the Gotek gives an error that no files found (E34?)

**Comment by keirf** [comment]
Which version of flashfloppy are you using?

**Comment by leonkiriliuk** [comment]
I only have the 7 segment display units. I believe it’s 1.2 that I flash on all the units. That’s what the zip file calls it.

**Comment by keirf** [comment]
Ah yes, the image name check was too strict. This was already fixed in 2.x series but I have backported the fix, and now released v1.3. So please try updating to v1.3 and see what happens.

**Comment by keirf** [comment]
Fixed in v1.3. Please open a new ticket for any other issues.
