### ISSUE TITLE
better support of 128x64 OLED

### ISSUE THREAD

**Issue by fook42** [keirf/FlashFloppy#234]
having a display with 64pixel height, it would be nice to be able to configure which rows are doubled in size and not having it doubled all the time.
addition: yellow/blue displays (where only the first 16 pixels are yellow) should be supported by using a small first text-row and a large second text-row.
![big_big](https://user-images.githubusercontent.com/28691557/58625854-9f125580-82d3-11e9-979d-556023cd66c1.jpg)
![big_big_T](https://user-images.githubusercontent.com/28691557/58625890-b2bdbc00-82d3-11e9-9c68-ea00b63151ff.jpg)

-> should be:
![small_big](https://user-images.githubusercontent.com/28691557/58625883-ae919e80-82d3-11e9-8720-3218097b66be.jpg)
![small_big_T](https://user-images.githubusercontent.com/28691557/58625895-b4877f80-82d3-11e9-895e-5701374b7d68.jpg)

**Comment by fook42** [comment]
i made some changes to the current code (based on 2.11a) - can i add a branch for this and create a merge-request afterwards? or how do you like to have the code?

**Comment by keirf** [comment]
Please see https://github.com/keirf/FlashFloppy/commit/83186755a6da743b0f4dbe4bf7e230057e065354

And raise new issues as necessary.
