### ISSUE TITLE
IBM 8'' CP/M support

### ISSUE THREAD

**Issue by omikron88** [keirf/FlashFloppy#24]
Hello,

Is the original IBM standard for 8'' and CP/M supported?
I cannot remember the standard number, but it is 77 tracks, 26 sectors per tracks and 128 bytes per sectors.
It is 250kbit/s I think.

**Comment by keirf** [comment]
Should be supported with HFE images. Might also depend what the data cable pin-out is supposed to be? (eg might need an adapter cable?)
