### ISSUE TITLE
Noob Help?

### ISSUE THREAD

**Issue by TrendMend** [keirf/FlashFloppy#241]
Hey, so I am a noob at this, and I am new to dos. I setup this with my Tandy 1000 (original, not TX, HX, etc) and I don't fully understand how this works. So Let's say I have a zip file of a game, which includes a folder that has the game, I need to convert this into an IMG, correct? then do I have to configure anything, because my tandy only works with 360k drives due to a hardware limitation. Any help is appreciated. Thanks

**Comment by keirf** [comment]
Yes you need to convert to a 360k IMG file. You shouldn't need any further configuration -- probably you need jumpers at JC and S1 at the rear of the Gotek.
