### ISSUE TITLE
The procedure of connecting the SD card

### ISSUE THREAD

**Issue by koklica** [keirf/FlashFloppy#245]
Dear Keirf 
Can you help I couldn't connect the SD card?

**Comment by keirf** [comment]
It is difficult to add SD card support to standard Gotek, you need good soldering skills, and to be able to understand the brief documentation in the wiki: https://github.com/keirf/FlashFloppy/wiki/Hardware-Mods#enhanced-gotek

**Comment by koklica** [comment]
I've seen it, but I'm having trouble understanding it.

**Comment by keirf** [comment]
There is no further support I'm afraid.
