### ISSUE TITLE
ZIP file support

### ISSUE THREAD

**Issue by silelis** [keirf/FlashFloppy#246]
Hello,

I have question.

Is there possibility that firmware will support zip files. Like ADF compresed to zip? So It will unzip it and mound adf (or other floppy image) to Gotek?

**Comment by keirf** [comment]
No.

It's not practical to support this within the constraints of the firmware and there is no need to zip your retro disk images given the relatively massive capacity of even the cheapest branded USB drives. Just unzip them all!
