### ISSUE TITLE
Broken link in Wiki

### ISSUE THREAD

**Issue by joctee** [keirf/FlashFloppy#247]
The wiki page "Firmware Programming" has a link to **Nick Lines' how-to guide**:

http://www.binarydevotion.com/?p=228

This link seems broken. I found a cached version of that page on Google and created a copy that I published here:

https://docs.google.com/document/d/e/2PACX-1vS4bI_tlB_O7GGO0VV--TtMpXFpXfAZ7X9l3JpSGGUiHbCPqffTdPYSlo9C5hHeR2DGdd43jv0m-Sgu/pub

Feel free to use this one if you like.

**Comment by keirf** [comment]
I simply removed the link and rely on the Youtube video only. Thanks. :)
