### ISSUE TITLE
file order

### ISSUE THREAD

**Issue by kodak80** [keirf/FlashFloppy#25]
I am using my Gotek with OLED display in an Atari ST and loving this firmware.

The file/folder order seems to be the order copied onto the USB disk?  Would it be possible to have a FF.CFG setting to control the order that files and folders are shown?  ie. Alphabetically or the order copied onto the USB stick?

**Comment by keirf** [comment]
This is not straightforward but... maybe as a feature post 1.0. It could be done, and maybe without slowing down directory listing (too much).

I will at least leave the ticket open for now to track this.

**Comment by kodak80** [comment]
Thank you.  It was more of a nice to have so yes, appropriate that it will be a feature post 1.0 release.

**Comment by Quantum-cross** [comment]
I haven't tried it with the Gotek yet, but try http://fatsort.sourceforge.net/

I've had to use this for my PowerPak NES flash cart to be sorted properly.

**Comment by Simone2018** [comment]
I exactly need something like this in DOS or Win...

**Comment by kodak80** [comment]
As it works under Linux, I might try creating a virtual Linux machine and mount my USB stick within it.

**Comment by tenuke** [comment]
googled it for you ;)

http://www.anerty.net/software/file/DriveSort/

*http://www.compulsivecode.com/project_copyinorder.aspx
<http://www.compulsivecode.com/project_copyinorder.aspx>*
<http://www.anerty.net/software/file/DriveSort/>


2017-12-19 12:11 GMT+02:00 kodak80 <notifications@github.com>:

**Comment by Simone2018** [comment]
Thank you tenuke! I was sure that exist!

**Comment by keirf** [comment]
Fixed in v2.7a
