### ISSUE TITLE
Support for Roland 'Memo' - not urgent

### ISSUE THREAD

**Issue by roses2uk** [keirf/FlashFloppy#254]
On most (but not all) Roland sampler discs with the .OUT or .W30 extension  there is a MEMO: a short note of 5 lines each of 12 characters (user-editable) describing the types of sample(s) contained within. Not sure where it is located on the disc sectors, but probably fairly near the beginning.

Now that I have the OLED screen on my Gotek, it would be great if this MEMO could be displayed on one of the lines for easier and quicker orientation before choosing and loading.

I think I sent you a copy of a W30 disk before, but not sure if it had a MEMO on it. I can resend one which does.

But not urgent, I know you have a thousand and one other things to do (just been reading about the QD project for other Roland samplers), and to all the other readers we must bear in mind that FlashFloppy is a labour of love, and we appreciate very much Keir's work and dedication.

**Comment by keirf** [comment]
Informative image file names will have to suffice I'm afraid.
