### ISSUE TITLE
Not working F-F for 5.25 320k fdd

### ISSUE THREAD

**Issue by mrdavoudi1** [keirf/FlashFloppy#257]
Hi
I have a 5.25 ffd on 386 pc that replace it with F-F on special PC for jumberca industrial machines.
The pc and the I-PC READ AND WRITE FLOPPY very well.
But when I connect F-F to the machine machine do nothing.
I use 3.32a firmware and check the log file with it related soft.
Do I have to put some changes for rpm or gap3 or mb/se speed.
Thanks

**Comment by mrdavoudi1** [comment]
It means drive is selected,and red led also turned on  when I work on machine  but no changes in track number or side will take effect.
I change usb stick and  cable and emulator .
I prepare images with disk2fdi program and it says the 5.25 floppy is double sided with 40 track and 9 sector per track and 512 byte/sector.
Also the special dedicated IPC  that is 386 can't format  prepared 320k images but can read and write to them.
I also made images with WINIMAGE and the result is the same.
Regards

**Comment by keirf** [comment]
It should just work - the default layout for 360k images is 40 cylinder, double sided, 9 512 byte sectors per track.

Did you put jumpers in the right place on the gotek? Jumpers at both  JC and S1 locations is usually correct for PCs.

**Comment by mrdavoudi1** [comment]
I have mistake in my writing.
The images is 40 track  , "8 sec/track" and 512 byte per sector.
I test all the possible states.the drive work for first drive (S0) with non twisted cable and the green led (drive select) is turned on when drive is selcted.
Also change the interface with JC (open and close) and all the state in the FF.CFG.
5.25 drive have disk change on pin34(shugart interface).
I'm confuse.
Something is wrong.

**Comment by keirf** [comment]
Ah yes well 320k IMG is automatically detected as double sided 40 cylinder and 8 sec per track. So should be fine.

If you want ready at pin 34 and dskchg at pin 2 then you don't need jumper JC.

**Comment by mrdavoudi1** [comment]
With any one of up configurations the drive wasn't work.
No changes in track number and side number take effect.

**Comment by keirf** [comment]
Does the gotek green led ever light? Have you tried the select jumper at each of s0, s1, and mo?

**Comment by mrdavoudi1** [comment]
No.when I access the green led light.
Yes I test in s0 S1 not mo.

**Comment by mrdavoudi1** [comment]
In s0 when i acess the floppy green led is light
In s1 when I acess the floppy green led is not light.
Also in similar machine like this with 360k floppy 5.25 F-F emulator work on s0 with jc open and no configuration else.

**Comment by keirf** [comment]
Maybe the disk format is a little non standard on this system eg sector numbering? Skew? Etc

**Comment by mrdavoudi1** [comment]
But I make  image from the disk sector by sector ad track by track and use that image.
Is there any parameter you suggest to change in FF.CFG  and IMG.CFG?

**Comment by keirf** [comment]
Do you perhaps have a raw dump or HFE image of a real disk you converted?

**Comment by mrdavoudi1** [comment]
I use this tool for many years.
http://www.oldskool.org/disk2fdi/
It first detect the disk properties and then image the disk.
And I have this image.and put this image on the stick.

**Comment by keirf** [comment]
FDI images aren't supported by FlashFloppy. You need a headerless raw sector image (IMG).

**Comment by mrdavoudi1** [comment]
Not fdi image.
The tool have many ability.
The images have  no header.
The tool save the bit by bit image as .IMG FILE.
how can i send you a .IMG file?

**Comment by keirf** [comment]
Zip and attach to this ticket.

**Comment by mrdavoudi1** [comment]
I don't know From where I can attach file.

**Comment by keirf** [comment]
Accessing Github issues from a desktop web browser, you can "Attach files by dragging & dropping, selecting or pasting them."

**Comment by mrdavoudi1** [comment]
[320dsk.zip](https://github.com/keirf/FlashFloppy/files/3500783/320dsk.zip)

**Comment by keirf** [comment]
Okay, size is exactly 320k so that's fine. I assume you rename the images to have IMG file extension when you use them on FlashFloppy?

The contained filesystem is presumably an early MSDOS. I would guess maybe DOS 1.x as the usual 55AA identifier is not present at the end of the boot sector. It seems unusual to use such old disks with a 386 PC?

FlashFloppy v3.3a detects the format as C-H-S = 40-2-8, as you believe is correct.

Are you sure these disks are compatible with your 386 PC?

**Comment by mrdavoudi1** [comment]
Hi
I change the extension myself.the original file is .img
The pc is 386 with special program to work with machine.
But the image is that one I sent to you
![VideoCapture_۲۰۱۹۰۸۱۴-۱۹۱۷۱۵](https://user-images.githubusercontent.com/50794195/63031067-a5729f80-bec8-11e9-8c31-d46c3ac56a60.jpg)
![VideoCapture_۲۰۱۹۰۸۱۴-۱۹۱۷۰۸](https://user-images.githubusercontent.com/50794195/63031069-a60b3600-bec8-11e9-941a-51aeb061c01d.jpg)
![VideoCapture_۲۰۱۹۰۸۱۴-۱۹۱۶۵۹](https://user-images.githubusercontent.com/50794195/63031072-a60b3600-bec8-11e9-837e-64fc3fdbd6d9.jpg)
![VideoCapture_۲۰۱۹۰۸۱۴-۱۹۱۷۳۰](https://user-images.githubusercontent.com/50794195/63031074-a6a3cc80-bec8-11e9-9e88-ef6a51c6b4cd.jpg)
![VideoCapture_۲۰۱۹۰۸۱۴-۱۹۱۷۲۱](https://user-images.githubusercontent.com/50794195/63031075-a6a3cc80-bec8-11e9-8efc-73b5740d219f.jpg)
![۲۰۱۹۰۸۱۲_۱۲۰۹۳۲](https://user-images.githubusercontent.com/50794195/63031142-cc30d600-bec8-11e9-9d55-137a9c4a2839.jpg)
![۲۰۱۹۰۸۱۲_۱۷۵۲۵۱](https://user-images.githubusercontent.com/50794195/63031143-ccc96c80-bec8-11e9-8e1d-2bb4e6b3c31f.jpg)
![۲۰۱۹۰۸۱۲_۱۲۱۷۱۲](https://user-images.githubusercontent.com/50794195/63031144-ccc96c80-bec8-11e9-8adb-9068b9619145.jpg)
![۲۰۱۹۰۸۱۲_۱۷۵۲۴۲](https://user-images.githubusercontent.com/50794195/63031148-cd620300-bec8-11e9-9a31-4d76561bb549.jpg)

**Comment by keirf** [comment]
Garbage vol label and file names?

**Comment by keirf** [comment]
Could be a bit like #256 ?

**Comment by mrdavoudi1** [comment]
Hi.
I set the computer setup parameter for drive a to "5.25 1.2m" and  Connect F-F  to position B of cable and software can work well with the emulator.🤔
But the image size is 320k
Then connect the emulator and use the image that software build on machine and it work as well as pc.
Thanks alot.

**Comment by keirf** [comment]
What were the alternative options: 3.5/1.44m perhaps? It does seem weird... Glad it works now though!
