### ISSUE TITLE
Having "FF" subfolder as root for entire FF filesystem.

### ISSUE THREAD

**Issue by kegepet** [keirf/FlashFloppy#259]
I was under the impression that FF could be the root folder for all configuration and image files, but apparently, it's just for config files. Wouldn't it make sense for "FF" to be the root of the entire thing, so that if an FF folder is present on the flash drive, that becomes the root for everything? This way, you could use that same flash drive for other stuff, and keep things neatly organized.

**Comment by keirf** [comment]
The idea was to keep config files out of the way, and also to make them faster to search for if the root dir is large (one long scan for FF/ and then config files are quick, vs long scan for each config file).

You can't put all your images in FF/, but you can put them in any other subfolder, and FlashFloppy will remember your last-loaded image, so you need never browse outside of your chosen subfolder. Then you have a USB drive with only FF/ and ImageFolderOfYourChoice/ at the rootdir. That's as good as it'll get.
