### ISSUE TITLE
Ignore or Exclude Directory

### ISSUE THREAD

**Issue by kegepet** [keirf/FlashFloppy#263]
I was thinking that it might be useful to allow for a special ignore directory on the flash drive, which would allow you to store other non-FF related things on the drive and still keep things neatly organized. You could call it FFX, for flash floppy exclude, or FFIGNORE or similar. You get the point.

**Comment by keirf** [comment]
If you start a file or folder name with a dot it will be ignored by Flashfloppy.

**Comment by Volutar** [comment]
Nice. Isn't that documented? It should be.

**Comment by keirf** [comment]
Yes good point, it's now documented in the wiki:
https://github.com/keirf/FlashFloppy/wiki/Initial-Setup#native-mode
