### ISSUE TITLE
Gotek 922B boards and DM Diy More OLED-091 display

### ISSUE THREAD

**Issue by spavinm** [keirf/FlashFloppy#266]
I have seen on other forums that people are having problems with the DM Diy More OLED-091 display. The main reason is the display requires pullup resistors adding to the SDA and SCL lines, I used a 4K7 on each line to 5V. These devices are slow to come out of their internal reset but they seem okay on the 3.12 FF firmware. The other point to note is the operational hit rate of these devices is low at the moment, of the four I purchased two worked correctly, one worked when you moved the glass and the fourth didn't work at all.

As a precursor to getting the display going was the issue of flashing the device. The Gotek 922B board does only has 7 holes/pins behind the power connector not the 9 as shown at the top of the hardware mods page. I also noted that the working example at the bottom of the hardware mod page is a 922C board and also has just the 7 holes. For reference the only lines missing are the SWDIO and SWCLK, all others are as shown.

**Comment by keirf** [comment]
Okay, I'm not sure what actions the project needs to take:
1. Mention in Hardware Mods that some OLEDs may need pullups (to 3.3V I would say). Did you put them on the display or the Gotek? Worth a photo?
2. Mention that crap cheap Chinese displays can be crap? Yeah... It's the downside of cheap... ;)
3. I do mention variation in Gotek header pins at top of Hardware Mods. But is it confusing people at the Firmware Programming stage / wiki page? Some text needed there? Or photo?

**Comment by spavinm** [comment]
Hi

Very little in the way of action, this is more FYI. I did it as an issue as I could not find a contact form on the wiki, eventually found your email.

I checked the pins on the STM32 and they are all 5V tolerant, these displays will run on 3.3V to 5V, the pull could be to the supply used. Just a note to suggest that a non-working display may be down to this. I fitted them onto the Gotek on the basis that I use this display in other products and have fitted the pull ups to the main board. This also maintains the multidrop nature of I2C. I don't know if other makes are better, but I would not recommend the DM ones.

As to the last point, the drawing and image at the top is clear, except that I didn't have the same number of pins. I was very cautious before I connected to make sure they were what was expected. I have another one to do at some point I will get a picture done for the revB board then, the pin functions are exactly the same minus the two SW... pins.

One final point I had problems getting this to be recognised by the ST bootloader software. It took a few goes. Could be the BOOT 1 pin, I didn't chase this further as once working I was away.

Cheers
Mark
  ----- Original Message -----

**Comment by keirf** [comment]
I have added further comment to the wiki on Goteks having varying number of header pins.

I have ignored the OLED pull-up issue for now. I will add discussion if I get further reports of this issue. But for now it would probably just muddy the waters.

Thanks!
