### ISSUE TITLE
Hardware troubleshooting ?

### ISSUE THREAD

**Issue by penfold42** [keirf/FlashFloppy#268]
Happy for you to close this as off topic...

But! I’m trying to troubleshoot a gotek that I recently flashed.
At first it would only give me E34 - I know the USB key is good because it did and continues to work fine in my other gotek.

Now it does nothing - no serial output, nothing on LED or OLED display.
And get this - nothing on the 8MHz crystal. It’s like the boot sequence never gets as far as enabling the external oscillator.

The flash seems ok - writes with verify work.

Here’s the weird bit - flashing FF-OSD seems to work - serial output, config all works and the external oscillator is fine.

Looking through the code of FF and OSD I can’t see any material differences.

Any ideas on what I’m missing ?

**Comment by keirf** [comment]
Nothing obvious, the start of day is rather similar. Best bet is pick a pin, say Jumper JA (PC6). It gets set as Weak PU early in the bootloader (src/fw_update.c:main()). You could change that to pushpull HIGH and then later in startup (perhaps in src/main.c:main()) to pushpull LOW followed by an infinite-wait loop, and use that to work out how far the firmware is getting (ie. Did it get there: Is JA HIGH or LOW?). You can binary chop the search space so this doesn't usually take too long.

Oooo, you could use PB10 and then see if the red LED lights or not :) Remember to set RCC_APB2ENR_IOPBEN if you do that.
