### ISSUE TITLE
Error 34 on Gotek display installed on an Atari ST

### ISSUE THREAD

**Issue by Coxside** [keirf/FlashFloppy#272]
I'm trying to replace the floppy drive on my Atari ST with a Gotek, but have run into a problem...

When I power up the ST, the Gotek display shows the message Error 34, and leaves me hanging.  Any ideas what this means, and how to resolve this please?

TIA

Tony

**Comment by keirf** [comment]
You need to put some ST images (ie ST file extension) on your USB stick. Error 34 is no valid image files found.

**Comment by penfold42** [comment]
This may be a bug - one of my goteks gives me E34 with the 3 digit  led display but works fine with oled or OSD

**Comment by keirf** [comment]
@penfold42 That's just weird. If you can reproduce it on a second Gotek then raise a ticket.
