### ISSUE TITLE
Is there an emulation of Disk Change for Atari ST?

### ISSUE THREAD

**Issue by TzOk83** [keirf/FlashFloppy#28]
Atari ST computers were using Write Protect line to detect disk change. Is this implemented in Flash Floppy? Floppy drive reports Write Protect LOW when there is no disk in drive or when there is a write protected disk inside, and HIGH when there is a write enabled disk in. So, when write enabled disk is removed or inserted, the WP line status changes, and this triggers the TOS to call disk change routine. However, when swapped disks are both write protected, Atari ST CAN NOT detect disk change.

**Comment by keirf** [comment]
This is already implemented. There is also I guess a possibility of blipping the write protect line even when swapping between write-protected disks. Anyway as is it should already work as well as an ST with its original drive. So I will close the ticket.
