### ISSUE TITLE
Side effect of TRD>80 cyl fix

### ISSUE THREAD

**Issue by Volutar** [keirf/FlashFloppy#285]
There's a side effect of this "fix" relying on free sectors count in image. 

Now it causes \*ERR\*31\* for some images, having wrong "free sectors" value (zero in my case). First free trk/sec = 1/0 and free sectors=0. And voila - F-F doesn't recognize this image :(

Most of emulators I know simply using image file size for that matter. 655360 bytes = 2x80x16x256, 688128 bytes = 2x84x16x256, 679936 bytes =2x83x16x256 (type 0x16, 2s/80), image size 327680 means either 2x40x16x256  (type 0x17, 2s/40) or 1x80x16x256 (type 0x18, 1s/80).
Free sectors+first free sector is only necessary for image extending

_Originally posted by @Volutar in https://github.com/keirf/FlashFloppy/issues/260#issuecomment-557811750_

**Comment by keirf** [comment]
Actually let's stick to the original ticket, reopened. Then we have all context in one place.
