### ISSUE TITLE
Wiki Update for Host Platforms: Acorn Archimedes A3020

### ISSUE THREAD

**Issue by dandoore** [keirf/FlashFloppy#289]
I have found that the Archimedes A3020 (and presumably any of the HD floppy capable models post A5000) uses an IBM drive rather than a Shugart type - tip off from https://torlus.com/floppy/forum/viewtopic.php?f=19&t=562&start=30#p16503

All the other settings are fine, but this tripped me up so can the Wiki be updated to show this :)

**Comment by keirf** [comment]
Now updated to mention the need for `interface = ibmpc`. Is there anything else to mention, such as different drive-select jumper setting?

Please reopen and let me know what to add, if necessary. Thanks!

**Comment by dandoore** [comment]
Just checked, I had to move jumper to S1, so it's the same for the generic IBM-PC interface bit: 

- IBM-PC interface mode must be configured
- Strap jumper JC at the rear of the Gotek; or
- Specify via FF.CFG: interface = ibmpc
- Strap select-line jumper S1 at the rear of the Gotek
- S0, S2, MO should all be left open

**Comment by dandoore** [comment]
Bugger, I can't reopen this issue :(

**Comment by keirf** [comment]
Fixed, thanks.
