### ISSUE TITLE
Support for the HxC Mount

### ISSUE THREAD

**Issue by TzOk83** [keirf/FlashFloppy#29]
Is there any chance for the HxC Mount support?

**Comment by keirf** [comment]
I'm happy to work with someone to debug the problems.

**Comment by TzOk83** [comment]
I may try to help, but have very little programming experience on ARM/non on MC68000. So, what do you want me to check for you? I have an Atari 1040STe with 2MB RAM, and switchable TOS v.1.06D/2.06D, and Megafile 60.

P.S.
There is a problem with ST disk images with over 80 tracks and/or over 10 sectors/track.

**Comment by keirf** [comment]
Try using hxcmount and see how it fails. Hint: you may need to lie about the reported firmware version using FF.CFG option da-report-version = "V2.0.0.0" or somesuch.

If you can test and report, I can try some firmware fixes and send to you for further testing.

**Comment by TzOk83** [comment]
HxCMount mounts the image, and files are accessible, is is possible to list text files, but it fails to load any PRG. I'm trying on 0.9.7a... what happened to synced track read option? ST image with 9 sectors/80 tracks reads again in 1:06 and but fmt+write is 1:20.

**Comment by keirf** [comment]
Okay thanks, that behaviour has been reported before. I'll get back to you with a modified firmware to test.

**Comment by keirf** [comment]
I haven't forgotten you. I will try to get you a firmware for test this week, so we can put this to bed for v1.0.

**Comment by TzOk83** [comment]
As you've probably noticed, I've bought HxC license, and recently I was "playing" with it... but today my second GOTEK unit came from China, so I'm ready to test FF again.

P.S.
Jeff has criticized the idea of optimizing the performance based on a FastCopy III format, as this is quite far from the native Atari ST disk layout. So I'll prepare some file based benchmark tasks on both FC3 and native formatted disks.

**Comment by keirf** [comment]
No problem, open another ticket if you have any performance issues relative to real floppy drives or other emulators on the various formats.

**Comment by keirf** [comment]
Here is a build of the firmware hopefully fixed for HxC Mount. Please test!

[ff_hxcmount.zip](https://github.com/keirf/FlashFloppy/files/1767044/ff_hxcmount.zip)

**Comment by keirf** [comment]
Here is an updated firmware for you to try with HxC Mount:

[ff_hxcmount_2.zip](https://github.com/keirf/FlashFloppy/files/1771283/ff_hxcmount_2.zip)

**Comment by TzOk83** [comment]
It is slow (saving a simple text file takes "ages"), but it works... OLED display seems to be "frozen" only W blinks. All other is static:
hxcmount_100
008/014       T:99.0

**Comment by keirf** [comment]
Is it not expected to be slow? HxC Mount requests a 64-sector track, which is 679,200 bitcells and takes 1.36 seconds for a complete revolution (ie. to spin back round to sector 0).

Requesting more than the default 9 sectors per track is an odd design decision, especially for a small file access which will be mostly random access in traversing dirents.

Anyway, let me know if FlashFloppy is especially slow. And how slow that is. And how slow it should be!

**Comment by TzOk83** [comment]
Recently I'm very busy, and not have much time for testing. Read with HxC mount seems ok (it is slow as it is meant to be), but saving a test file containing test12345 from TEMPUS2 text editor took several seconds (I didn't measure it exactly, but I guess it was over 10 seconds).

**Comment by keirf** [comment]
That's kinda weird then. I may have to set up an ST myself, or get you to grab serial logs from FlashFloppy on a future test run, if you can.

**Comment by keirf** [comment]
In fact I urge you to open a ticket as then we can discuss the fix, which I think I know what it is ;)
