### ISSUE TITLE
Akai X7000

### ISSUE THREAD

**Issue by baritonomarchetto** [keirf/FlashFloppy#296]
Hi, I want to report that the quick disk alternate code works flawlessy with the akai X7000. Notice that the pinout is reversed.
Great work!

**Comment by keirf** [comment]
No jumper required at JC? If you can read/write with no errors without it then the answer is no :)
Hopefully only Roland requires JC.

**Comment by baritonomarchetto** [comment]
Correct: no jumper at JC

**Comment by keirf** [comment]
And by reversed do you mean that the colour sequence is reversed?

**Comment by baritonomarchetto** [comment]
The cable is a full grey cable: it has no colors at all. By looking at the printed numbers (both in the quick disk drive connector and cable connector) I measured 5V on QD pin 2, not 9. By connecting the gotek reversed (pendrive NOT connected) I broke nothing anyway (yes: I measured the voltage AFTER the first conncetion ... :) )

**Comment by keirf** [comment]
Thanks, this is all updated in the Wiki :)
