### ISSUE TITLE
Indexed mode

### ISSUE THREAD

**Issue by mrdavoudi1** [keirf/FlashFloppy#298]
Hi Keir
I read #36 but have another question.
In hxc emulator it had an indexed mode with DSKA0000.HFE filename.
In this mode if we put the name of the file DSKB0000.HFE  and s0 signal is selected the emulator work with this file instead DSKA0000
Means two drive work just by change in file name.
May it possible to put this feature in the program?

**Comment by keirf** [comment]
This is essentially a request for dual floppy support, so duplicates existing issue #36
