### ISSUE TITLE
FAT ReadOnly attribute to writeprotect disk images

### ISSUE THREAD

**Issue by jamarju** [keirf/FlashFloppy#30]
It might make sense to write protect disk images so that they don't get accidentally written over, eg. the Amiga Workbench disks. Turning on the R/O FAT attribute comes to me as the most intuitive way to do it.

**Comment by keirf** [comment]
Yes I keep meaning to act on that attribute. It's plumbed through now. I will implement in the next release.

**Comment by jamarju** [comment]
I just submitted a PR implementing this for your review. Thanks.

**Comment by keirf** [comment]
Cheers!
