### ISSUE TITLE
Zip disk drive emulation

### ISSUE THREAD

**Issue by baritonomarchetto** [keirf/FlashFloppy#303]
Hello all, 
I am writing something stupid right now, but someone had to! :)
Would it be possible to emulate a iomega zip disk drive with a gotek drive? Would it be possible to realize a FF fork (like the one for quick disks) to support those dinosaurs?
(Thanks!)

**Comment by ewanuno** [comment]
seems pretty far from flashfloppy's remit to me, what you probably want is a scsi emulator like scsi2sd  http://www.codesrc.com/mediawiki/index.php?title=SCSI2SD , ArdSCSino https://github.com/ztto/ArdSCSino-stm32, or rascsi http://retropc.net/gimons/rascsi_bm/index.html

**Comment by mdanh2002** [comment]
Just to share, I reverse-engineered the parallel port Iomega ZIP100 disk drive and successfully integrated it into DOSBox and QEMU (nibble mode and bidirectional mode). Max speed is around 50KB/sec. It works fine in MS-DOS, Windows 98, and Windows XP. I also developed a prototype on the PIC32MZ2048EFH144 which emulates a ZIP100 drive and supports disk image (on USB) up to 1GB, which work well with Book 8088 using PALMZIP drive. Max speed is around 7KB/s when running on the Book 8088. 

See my write-up here: https://www.toughdev.com/content/2026/02/pic32mz-iomega-zip100-parallel-port-emulator-part-1-dosbox-qemu-testing/ (software emulation), and https://www.toughdev.com/content/2026/03/pic32mz-iomega-zip100-parallel-port-emulator-part-2-hardware-design/ (hardware design). The Hackaday article is here: https://hackaday.com/2026/03/17/zip-drive-emulator-puts-big-disks-back-on-lpt/

I also made several demo videos here: https://youtu.be/340J7vItfPw (Software Emulation), and https://youtu.be/ZMJkRygU8kI (Prototype Board)
