### ISSUE TITLE
OLED current dir not refreshed on change to parent

### ISSUE THREAD

**Issue by penfold42** [keirf/FlashFloppy#305]
Folder name in top row is refreshed on change down, and when i get to / but never on the way up.

Folder structure is this
/games/BloodMoney/BloodMoneyD1of2

My last played game was in / so top row has "/" (good).
select games and top row now has "games" (good)
select BloodMoney and top row now has "BloodMoney" (good).
select [..]
I see the files&folders in /games but top row has "BloodMoney" (NOT! good).
It should display "games"
select [..]
I see the files&folders in / top row has "/" (good).

**Comment by keirf** [comment]
Latest 3.10a?

**Comment by keirf** [comment]
Yes I can repro this.

**Comment by penfold42** [comment]
too funny - i just pulled out the usb stick to double check id updated - yes

**Comment by keirf** [comment]
Around src/main.c:1480. Not the clearest code....

**Comment by keirf** [comment]
Can you please build and test latest master?

**Comment by penfold42** [comment]
sure - will do right now - need a distraction from my GAL nightmares....

**Comment by penfold42** [comment]
yep - looks good to me

**Comment by keirf** [comment]
Cheers!
