### ISSUE TITLE
What is FlashFloppy

### ISSUE THREAD

**Issue by bmuessig** [keirf/FlashFloppy#306]
I have been linked to this repository in a thread concerning removable flash storage for measurement equipment that uses floppy disks. But I can't really make heads or tails from the documentation, on what this project here actually tries to accomplish. Adding a detailed description to the README or wiki should be strongly considered.

**Comment by keirf** [comment]
It's a floppy drive replacement, which uses floppy images on a USB stick in place of real physical floppy disks. I will add a sentence or two to the wiki front page.

**Comment by keirf** [comment]
New intro text in the main README and the Wiki Home Page.
