### ISSUE TITLE
Flashfloppy 2.14 not working with Sam Coupe

### ISSUE THREAD

**Issue by o0Nosferatu0o** [keirf/FlashFloppy#313]
Hi Keirf, my name's Pedro Torres and i'm from Portugal. I was attempting to use a Gotek with my Sam Coupe. The Sam has 3.0 Rom, 512k ram and an original floppy drive.
This Gotek is working without a problem with Amiga/Amstrad CPC/Atari. It was flashed to 2.14 and couldn't boot any .dsk with it. I came upon the https://github.com/keirf/FlashFloppy/issues/92 and tested the #2 firmware you posted there and it worked right of the bat. With 2.14 started to read and stated "53 No Dos" stoping at track 04.

**Comment by keirf** [comment]
Could you send me a link to, or attach here, a DSK which works now but did not work in 2.14.

Also could you try the following firmwares available on the Downloads page:
- v0.9.18a (This I guess is the proper official release on which the one you downloaded was based)
- v0.15
- v1.2

That will do for starters :) Thanks!

**Comment by keirf** [comment]
Reopen if anyone can reproduce this issue and supply the requested info.
