### ISSUE TITLE
Spelling issue in help - FF-v2.13 (Amiga)

### ISSUE THREAD

**Issue by chunkypixel** [keirf/FlashFloppy#315]
Hi,
Just purchased a Gotek with your FF-v2.13 firmware which I'm using on my Amiga 500 and found a spelling issue in the help for the F1 function key description.

### Line
Escape to **abord** the search 
should be **abort**

Thanks for your hard work @keirf !

**Comment by chunkypixel** [comment]
Wow - just realised i'm a bit behind and this may already be fixed - if so apologies!

**Comment by keirf** [comment]
Thanks, fixed in the source code now, and will be rolled up into the next fix release.
