### ISSUE TITLE
Problem with the rotary control

### ISSUE THREAD

**Issue by briefer666** [keirf/FlashFloppy#316]
Hi

I have installed a KY-040 rotary control, and it works but only to move forward through the menus. Moving the rotary clockwise or anticlockwise have the same effect, move to the next item, not the previous.

I try to remove the pull-up resistors from the back of the PCB and with and without plugin the +3.3v pin, but did not fix the issue.

any clues? should I try soldering directly to the rotary directly?

kind regards

**Comment by penfold42** [comment]
Did you also hook up the push button ?

Is it possible you switched a couple of wires ?

**Comment by keirf** [comment]
Flashfloppy version? Have you tried adjusting rotary= setting in FF.CFG?

**Comment by briefer666** [comment]
Thank you for your quick answer. Have to look in my browser history, but it seems like I installed 3.7a (I installed it some time ago and I am trying to install the rotary now)

I checked the wires two and three times, everything seems to be in place.

[url=https://ibb.co/cJz5QTd][img]https://i.ibb.co/5TqDLcV/IMG-0084.jpg[/img][/url]
[url=https://ibb.co/dmsxShm][img]https://i.ibb.co/xFKdy4F/IMG-20200213-140930.jpg[/img][/url]

I also tested with FF.CFG with rotary=reverse,half, and then it only goes back, not forward.

Should I try another fw?

**Comment by keirf** [comment]
Try latest 3.x and if no luck with any rotary= setting I think you need a new rotary encoder.

**Comment by briefer666** [comment]
Thanks! I will do that 😉

**Comment by briefer666** [comment]
Thanks! I will do that

**Comment by briefer666** [comment]
Ok, I updated and it went to worse :( 

now the rotary does not move through the menus. I tried rotaryas full, quarter, half and grey. Only quarter and grey moves, but goes to the next item and back again in one step.
Push button always work.

I am going to solder the cables directly to the rotary contacts, and bypass the board.

cheers

**Comment by briefer666** [comment]
And it works! wiring directly to the rotary bypassing the board fixed the problem. Thanks!
