### ISSUE TITLE
HFE with NFA section not working (v2.14) 

### ISSUE THREAD

**Issue by drdpj** [keirf/FlashFloppy#317]
Hello - it's feasible that it's a badly encoded HFE, but it *does* work converted to SCP then written to a real disk. Track 39, last sector has a few unformatted 
[HFEs - v1 and 3.zip](https://github.com/keirf/FlashFloppy/files/4208577/HFEs.-.v1.and.3.zip)

The v1 is the original, the v3 is just saved out as a v3 (and the extra tracks removed)

**Comment by keirf** [comment]
So do both of these work converted to SCP and then written to disk with Greaseweazle, but neither works with FlashFloppy?

**Comment by keirf** [comment]
And the v3 is generated from the v1?

**Comment by keirf** [comment]
There really doesn't seem to be anything that unusual here and FF should deal with HFEv1 just fine, it's a really simple format. I don't see what's unformatted. Do you mean extra tracks or something?

**Comment by keirf** [comment]
And what machine is this for, a BBC? I wonder if it's a protection which is fussy about timings...

**Comment by drdpj** [comment]
It's BBC Micro, yes. If you look at sector 9 on track 39 you'll see there's a gap with no fluxes between approx 3.9 and 4.5ms?

**Comment by drdpj** [comment]
Something very odd - HxC is doing an appalling job of converting that HFE to SCP - the HFE loads fine, but this is what drops out...
[HFEv1_hfe.zip](https://github.com/keirf/FlashFloppy/files/4208653/HFEv1_hfe.zip)

**Comment by keirf** [comment]
Ah I see, a No Flux Area. Flashfloppy will definitely get confused if it's longer than max timer setting (~900us). Maybe it can in other cases too, not sure it's been tested.

So even hxc's mangled scp works when written to disk?

**Comment by keirf** [comment]
Or do you think its supposed to be a fuzzy bits area? Since you say the protection expects randomness rather than pure zeroes.

**Comment by drdpj** [comment]
Seems to - I think all the data is on the earlier tracks!

**Comment by drdpj** [comment]
Possibly fuzzy bits, but we have no way of knowing as the original is lost
to the mists of time... But NFA should yield random too? On a real disk it
just cranks up the gain...

**Comment by keirf** [comment]
If you write no flux, you get randomness on read. If you write very rapid fluxes, you get no flux on read. There are protections out there which depend on either one of these. So: Which does No Flux in an HFE mean? It's not defined, right.

**Comment by keirf** [comment]
Okay, had a closer look: Looks like a ~500us NFA on the HFEv1, HFEv3, and the generated SCP too. 

By the way the SCP is I think fine, as if you look in track-view mode all sectors are present and green, it's just HxC has decided to spray red all over certain tracks. It has a habit of doing that to SCP images, it's likely a bug so just something to watch out for.

Anyway, that 516us NFA in the SCP will be detected and written as NFA by Greaseweazle. So I'm pretty sure it is *intended* to be No Flux. As you wrote that very SCP image to disk via GW, and it works, right?

That size of NFA should be handled correctly by FlashFloppy in the HFE images too. Curious.

**Comment by keirf** [comment]
Could you try dumping the HFE from Flashfloppy via greaseweazle and supply that as scp? Use the HFEv1 if the scp generated from it worked on disk. Yes I could do it myself 😉

**Comment by drdpj** [comment]
[tbp-all.zip](https://github.com/keirf/FlashFloppy/files/4208936/tbp-all.zip)
Here's the original HFE (truncated to 40 tracks), the original converted SCP that was written, and the SCP that was read back :)

**Comment by keirf** [comment]
So that is the scp read from gotek with that hfe mounted?

**Comment by drdpj** [comment]
Oooh, I see what you mean... Hang on a mo :D

**Comment by drdpj** [comment]
[tbp-ff-read.zip](https://github.com/keirf/FlashFloppy/files/4209022/tbp-ff-read.zip)
Here you go - read off the gotek with gw :)

**Comment by keirf** [comment]
The NFA is still there, and the right size: 516us.

**Comment by keirf** [comment]
So it's all a bit weird really. Is the Gotek tested on the same BBC as the real disk written by GW?

**Comment by keirf** [comment]
Another thought: is the scp redump from real disk from the BBC drive? If not, is that possible to set up? Wonder if the old BBC drive might respond differently to that no flux area. Bit of a long shot. That flux area is starting to feel like a red herring.

**Comment by drdpj** [comment]
So, tbp-read.scp is a dump from the floppy that works on the beeb from a 5.25" 40 track floppy drive. The HFE in the floppy emulator's failing as it seeks to track 39 during the initial loading (which must be where it's doing the check on that sector)...  I wonder... Could it be a speed thing?

**Comment by drdpj** [comment]
(everything has been tested on the same computer!)

**Comment by keirf** [comment]
Are you running on an 8271 FDC and/or with `index-suppression = no`?

**Comment by keirf** [comment]
Also, to verify the bits coming off the Gotek are basically fine: Take `tbp-ff-read.scp` (the dump from Gotek) and write it back to disk. And test that disk. It will probably work.

**Comment by drdpj** [comment]
Running with a 1770 with index-suppression=no.  The final test (dump from gotek back to disk) works fine.

**Comment by keirf** [comment]
Please try changing to `index-suppression=yes`. The 1770 generally works okay like that right?

**Comment by drdpj** [comment]
Yes, 1770 is fine like that - but changing that to a yes, still no dice.

**Comment by keirf** [comment]
Tough cookie. I think it still must be timing related if it works Gotek -> disk -> BBC but not Gotek -> BBC.

**Comment by keirf** [comment]
No other non default drive settings in FF.CFG?

**Comment by drdpj** [comment]
host = acorn
index-suppression = yes
track-change = realtime
display-type = oled-128x32
oled-font = 8x16

**Comment by keirf** [comment]
Try `track-change = instant` as well

**Comment by drdpj** [comment]
No dices :)

**Comment by keirf** [comment]
Final conclusion after some external discussions: this should be a flaky region (expressable in HFEv3 but not HFEv1).
