### ISSUE TITLE
"r16" on three digit display at power on

### ISSUE THREAD

**Issue by GustavoLafava** [keirf/FlashFloppy#323]
I had this kind of error (i presume) during emulator power on and I didn't found any regard that. Is that simply an firmware corruption or something similar?

![error](https://user-images.githubusercontent.com/4705483/77530977-78d92a00-6e92-11ea-88e7-724e3ea0c723.jpg)

**Comment by keirf** [comment]
It says "rib" and is telling you the floppy ribbon cable is installed wrong way round.

**Comment by GustavoLafava** [comment]
Ach! My bad.. Thank you!
