### ISSUE TITLE
Akai S1100 No samples on power up test program

### ISSUE THREAD

**Issue by belzrebuth** [keirf/FlashFloppy#325]
Hi,
I have a weird issue with my S1100 and flash floppy.,.
My S1100 is running os 4.3.
It seems that when booting with just a blank formatted disk loaded (001) the sampler starts with the default test program but the program contains no samples instead of the default sine, square, pulse.
If I power on the sampler without a USB drive it boots normally with the samples loaded.
The disk drive otherwise works okay.
I can load/format and save normally.
When testing I've only a blank 1600kB .img file and the FF.CFG file on my USB drive.
Tried 3 different usb drives with the same result.
Any ideas what might be causing this?
I'm thinking maybe something forces the sampler to load whatever is in the disk too soon?
Just a thought..I really don't know what's going on.

I'm using this FF.CFG 
https://drive.google.com/file/d/1JWmoVbSuA3u0KTOzmThWpH47l-FKbY6Y/edit

**Comment by keirf** [comment]
Are you sure that's not some normal behaviour?

**Comment by belzrebuth** [comment]
Yes,
I should have noticed it before.

**Comment by belzrebuth** [comment]
Ι'll try with a regular floppy and report back to ensure this is floppy related.
I can also place the original eproms back.
These are the 2 things I did recently on it.
I've upgraded the S1100's OS and replaced the floppy with a floppy emulator.

**Comment by keirf** [comment]
I think that would be interesting. This would be a weird issue to be Gotek related.
