### ISSUE TITLE
No scrolling

### ISSUE THREAD

**Issue by 1xzui341** [keirf/FlashFloppy#33]
I have no luck with scrolling text so far.config file is in root directory,latest FW is flashed.
The display itself works fine,i used a common 128x64 oled.
Are there any special requirements a display must fulfill?

**Comment by keirf** [comment]
You need to update to latest HXCSDFE.CFG and AUTOBOOT.HFE, see the links here: https://github.com/keirf/FlashFloppy/wiki/Operating-Modes#hxc-autoboot-mode (HxC Autoboot Mode)
