### ISSUE TITLE
Atari ST AUTOBOOT: Keyboard layout is AZERTY

### ISSUE THREAD

**Issue by Clifhanger3** [keirf/FlashFloppy#330]
I am having trouble using the keyboard on Atari ST when i press F1 to search for files. I am using the Gotek drive

When I type:
Q it comes out as A
W comes out as Z
A comes out as Q
Z comes out as W
M key doesn't work at all

This is only an issue withing the flash floppy. The keyboard works fine in any text editing program I load.

Any ideas?

**Comment by keirf** [comment]
This is with the AUTOBOOT program, right?

**Comment by Clifhanger3** [comment]
> This is with the AUTOBOOT program, right?

yeah correct!

**Comment by Squirrel61** [comment]
It looks like the QWERTY keyboard layout is hardcoded in the Autoboot
program, while you are using a keyboard with AZERTY layout.

Op di 21 apr. 2020 om 11:45 schreef Clifhanger3 <notifications@github.com>:

**Comment by Clifhanger3** [comment]
So i am using a QWERTY keyboard as that is the atari ST key layout.

Is there a way of changing this?

**Comment by Squirrel61** [comment]
I don't know. I never had an ST but found on the internet that the AZERTY
keyboard seems to exist so it seemed the logical explanation for the
behaviour you found.


Op di 21 apr. 2020 om 12:07 schreef Clifhanger3 <notifications@github.com>:

**Comment by keirf** [comment]
Looks like @Squirrel61 is right but wrong way round: The AZERTY keyboard layout is hardcoded. Because the original author is French, of course :)

**Comment by keirf** [comment]
It is hardcoded but could be fixed: The codes are all in atari_st/keymap.h. If someone wants to do a patch to QWERTY-fy them, I'll take it.

**Comment by Clifhanger3** [comment]
> It is hardcoded but could be fixed: The codes are all in atari_st/keymap.h. If someone wants to do a patch to QWERTY-fy them, I'll take it.

This is where it's above my head. So i can't be of any assistance doing that haha. hopefully those smarter than me will be able to resolve :)

**Comment by bfollowell** [comment]
OK, I have no idea how to compile or create a new AUTOBOOT file, but I was able to modify the keymap.h file to the correct values for a QWERTY style ST keyboard, at least the U.S & U.K. versions. Would someone be able to use this to create a QWERTY version of AUTOBOOT?

Thanks.
[keymap.zip](https://github.com/keirf/FlashFloppy/files/4533475/keymap.zip)

**Comment by keirf** [comment]
Sorry for the delay. Here you go: Please test. If it works I will happily make this the keymap for next release.

[ST_AB_330_1.zip](https://github.com/keirf/FlashFloppy/files/4700299/ST_AB_330_1.zip)

**Comment by bfollowell** [comment]
I will. Thank you!

**Comment by Clifhanger3** [comment]
Yep, tested and it works as QWERTY.

Thank you very much!

**Comment by keirf** [comment]
Pushed to the repository and will feature in the next release.
