### ISSUE TITLE
Using Flashfloppy with Trackstar 128 (reading Apple 2 disks)

### ISSUE THREAD

**Issue by keenerb** [keirf/FlashFloppy#333]
I'm attempting to use a Flashfloppy device with an Apple II emulator ISA card called a Trackstar 128.

I haven't had a lot of success so far; HXC firmware at least gets me far enough to boot an Apple II game but disks are read-only.

Should I expect flash floppy to be able to read Apple II disk images?  The Trackstar used native 360kb IBM floppy drives to read and copy even copy-protected apple disk images, so it's theoretically possible.

**Comment by keirf** [comment]
Should work. Are you using 360kb IMG file? Geometry should automatically be 40 cylinder DSDD 9 sectors per track. Are you jumpered correctly? Might need a jumper at JC at Gotek rear.
