### ISSUE TITLE
Is the FM Towns PC Supported? 

### ISSUE THREAD

**Issue by cyo-the-vile** [keirf/FlashFloppy#334]
The FM Towns line of Japanese PCs use a Shugart standard connector...is flash floppy confirmed to support these PCs? I haven't seen any documentation online of people using a flashed GOTEK for this purpose.  I know the FM Towns Marty with an adaptor should be supported as it uses the same 26 pin 1.25mm pitch FFC cable as the PC-98 floppy drives do.  Just wasn't sure regarding the FM Towns PC.

**Comment by keirf** [comment]
I don't have 100% confirmation but some Japanese 360rpm formats are explicitly supported already.

**Comment by cyo-the-vile** [comment]
Yes I saw some PC-98 stuff is supported.  I'll see if it can work and report my results :)
