### ISSUE TITLE
Errors with BBC Master

### ISSUE THREAD

**Issue by drdpj** [keirf/FlashFloppy#34]
HFE (FM) images were working fine with 0.9.3a, but having upgraded to 0.9.5a it's not behaving well - disc error 0E which is a data CRC error :(
(0.9.4a is OK - just checked that)
d.

**Comment by keirf** [comment]
Are you sure (have you checked 0.9.5a again)? There should be nothing between 0.9.3a and 0.9.5a (let along 0.9.4.a and 0.9.5a) that affects the actual floppy emulation -- the changes were all to do with the UI.

**Comment by drdpj** [comment]
I've tried it again with 0.9.5a, and it seems to be behaving itself. No idea what was going on there :( Curse you ancient hardware!
