### ISSUE TITLE
Display Request

### ISSUE THREAD

**Issue by Manojkumar619619** [keirf/FlashFloppy#347]
Hi Sir
Good Day

Can you make changes that initial start up display F-F ( without usb stick ) to any other spell like company name or etc ...?

**Comment by keirf** [comment]
Via FF.CFG for example? This is possible.

**Comment by Manojkumar619619** [comment]
> Via FF.CFG for example? This is possible

Thank you sir. Is it Possible on UPD firmware update ?

**Comment by keirf** [comment]
Yes, you would need to do your own build of the firmware, with customised banner string, and use the resulting UPD file. It would then be "baked into" the firmware. At least until the next update!
