### ISSUE TITLE
UPD file update

### ISSUE THREAD

**Issue by Manojkumar619619** [keirf/FlashFloppy#350]
Hi Sir
Good Day

Can i Update this attached UPD file into your FlashFloppy V.2.14 Or 3.13a ?
if not, any other way to update this UPD file into your Flash.
Please update me Sir..
Waiting for your response
Thank You. 
  
[files upd.zip](https://github.com/keirf/FlashFloppy/files/4911662/files.upd.zip)

**Comment by keirf** [comment]
No, HxC firmware updates require purchase of an HxC license: https://hxc2001.com/store/
