### ISSUE TITLE
ERROR: Media Attach failed! on Amiga 500 Plus when used as external

### ISSUE THREAD

**Issue by Wetmackeral** [keirf/FlashFloppy#356]
![15974404837703825541678197775744](https://user-images.githubusercontent.com/69698041/90294064-74cb9a00-de7d-11ea-8078-46f89c8ba1b2.jpg)
![15974405104883297876193914861137](https://user-images.githubusercontent.com/69698041/90294083-7f862f00-de7d-11ea-9840-2e58b69341d9.jpg)
![15974405240673646648605462312897](https://user-images.githubusercontent.com/69698041/90294100-8ad95a80-de7d-11ea-8b38-c1b1b857da26.jpg)

I can't work out why I keep getting this error message, I've followed the setup instructions to the letter.

Is this due to the fact it's plugged in as an external drive? How can I get around this?

**Comment by keirf** [comment]
Have you tried reformatting the USB stick, or trying another stick?

**Comment by keirf** [comment]
And do you get this error every time, or intermittently?

**Comment by Wetmackeral** [comment]
Hi, thanks for this, using a different memory stick worked first-time - I was getting it constantly on every attempt with the previous stick. The non-working stick was a SanDisk Ultrafit 64GB USB3.1 (formatted to FAT32 from exFAT); the working stick is a SanDisk Ultra Flair 128GB USB 3.0 (natively FAT32)
