### ISSUE TITLE
FF 3.16 Eject & Menu don´t eject Media

### ISSUE THREAD

**Issue by Starfoxfs** [keirf/FlashFloppy#359]
Hi,

i have updated to new Flashfloppy 3.16 yesterday. 

If i eject an Image (Eject & Menu) the Image (ADF) doesn´t be displayed as Ejected.

Don´t know its a Bug ? in 2.14 this will be displayed as Ejected, in 3.16 it re-reads the Image after klick on Eject Menu

**Comment by keirf** [comment]
Whole you are in the menu the image is ejected. So what is the problem you see: you immediately and unexpectedly exit the menu again?

**Comment by Starfoxfs** [comment]
Hmm,
If i press Eject & Menu with Rotary Button i´m in the Menu to select other Images, but the Image isn´t ejected or it doesn´t leave ejected it re-reads after less than 1 second.

I´m in native mode with Gotek.

**Comment by keirf** [comment]
Perhaps you need autoselect-file-secs=0 and autoselect-folder-secs=0 in FF.CFG file?

**Comment by Starfoxfs** [comment]
Now i know Eject & Menu is Ejected then it´s ok.

Thanks for the great work on Flashfloppy :-)
