### ISSUE TITLE
Kuka KRC1 Flash Floppy Errors

### ISSUE THREAD

**Issue by hikodaci** [keirf/FlashFloppy#363]
I have a machine which is made by KUKA Robot. There is Win95 inside it. And the floppy drive reads as 1.44 Standart floppy.

I can read and the write files in explorer on the computer so there is a no different mod as dos or etc. 

I can use the GOTEK with original firmware on this machine. And I upgraded it for Flashfloppy firmware V3.16

After flashing, The GOTEK digits shows F-F and When I push the right button it shows 3 and 16. I think there is no problem with flashing.

I have created two different IMG files (empty and my files) with a software of WinImage on the Windows. (Dolu is meaning Full, Bos is meaning Empty)

![Dolu](https://user-images.githubusercontent.com/70331466/91821948-c4f97900-ec3f-11ea-88b5-081c37996c39.PNG)
![Boş](https://user-images.githubusercontent.com/70331466/91821956-c7f46980-ec3f-11ea-93c8-7270b4f77a25.PNG)
I put two IMG files, FF.CFG and IMG.CFG files in the flash memory which is formatted as Fat32.
![Flashbellek2](https://user-images.githubusercontent.com/70331466/91821921-bd39d480-ec3f-11ea-9221-b3476771c292.PNG)
Also, I changed the interface in FF.CFG file.
![disket_](https://user-images.githubusercontent.com/70331466/91822142-025e0680-ec40-11ea-92be-b5aea4dc2bd6.PNG)

The GOTEK shows 000 and 001 on its digits, I think they are my IMG files. But when I operate the read function on machine, It is not working. Also, writing is not working too.

What is the problem? And what have I to do?

**Comment by keirf** [comment]
What's happened to your IMG file sizes? In the last picture they are no longer 1,440KB in size. That is why it's not working.

**Comment by keirf** [comment]
Also you do not need FF.CFG or IMG.CFG files. Remove them. Also clear cached config by holding both buttons *after* power on, with no USB stick inserted, for five seconds until the display shows 'RST'. This clears any cached config.

Now make sure you have jumpers at positions S1 and JC at the rear of the Gotek. And no other jumpers.

**Comment by hikodaci** [comment]
> What's happened to your IMG file sizes? In the last picture, they are no longer 1,440KB in size. That is why it's not working.
> 
> EDIT: The IMG files must each be exactly 1,474,560 bytes long. Please check that.

The last picture is wrong I know. I have tried to shows only config file settings in this picture, not IMG files.

My IMG files are 1.440KB too, and I think there is no problem with them.

![flash1](https://user-images.githubusercontent.com/70331466/91824090-e14ae500-ec42-11ea-9675-a28697d1c9c6.PNG)


I will try it again to remove the config files on the flash memory.

**Comment by keirf** [comment]
I think actually the problem is the example IMG.CFG you had installed. Just removing that should fix your problem. You could leave FF.CFG and not reset your flash config.

**Comment by hikodaci** [comment]
This is the machine and GOTEK.

![WhatsApp Image 2020-09-01 at 11 18 44 (1)](https://user-images.githubusercontent.com/70331466/91825890-88308080-ec45-11ea-93b4-aec19c857176.jpeg)

![WhatsApp Image 2020-09-01 at 11 18 44](https://user-images.githubusercontent.com/70331466/91825919-92527f00-ec45-11ea-95b4-b2099b9629bd.jpeg)


I reset the GOTEK with push two buttons and it shows RST on the display.
The config files are removed on the flash memory. There are only 2 IMG files on it.

When I put the flash memory it shows me that,
![WhatsApp Image 2020-09-01 at 11 18 46 (1)](https://user-images.githubusercontent.com/70331466/91826059-c463e100-ec45-11ea-9567-c42202ca229c.jpeg)
Then it shows 000 and I can change it to 001.
However, when I Load from GOTEK to Machine, Machine showed errors.
![WhatsApp Image 2020-09-01 at 11 18 46](https://user-images.githubusercontent.com/70331466/91825846-7b139180-ec45-11ea-8ad6-a69a56ad6848.jpeg)
And I Tried save to Floppy it showed this error.
![WhatsApp Image 2020-09-01 at 11 18 46](https://user-images.githubusercontent.com/70331466/91825993-aa2a0300-ec45-11ea-8783-c546c9d4af6c.jpeg)

**Comment by keirf** [comment]
Definitely only the two IMG files on the USB stick? Does the green LED on front of the Gotek ever light up?

**Comment by keirf** [comment]
And show a picture of jumpers at the rear of the Gotek.

**Comment by hikodaci** [comment]
This is the inside of USB stick.

![inside](https://user-images.githubusercontent.com/70331466/91831411-b4033480-ec4c-11ea-8905-f1c2a2520b39.PNG)

And it is the jumpers at the rear of the Gotek.

![jumper](https://user-images.githubusercontent.com/70331466/91831588-ed3ba480-ec4c-11ea-9726-df6bd95ffa76.jpeg)

**Comment by hikodaci** [comment]
> Definitely only the two IMG files on the USB stick? Does the green LED on front of the Gotek ever light up?

The Green Led on the front of Gotek is never light up.

**Comment by keirf** [comment]
The green LED is the drive select indicator so if it never lights up, it's no surprise you can't read/write: the drive is never selected! This would also explain why you see the track indicator (`0_`) for a short while but never again: The track number is never changed because the drive is never selected.

Try the S1 jumper at S0, and also at MO and see if you can get that green LED to light at all.

If you are at all handy with an oscilloscope or logic analyser you could also look for signs of drive- and motor-select signalling on pins 10, 12, 14, and/or 16.

**Comment by keirf** [comment]
You can also try all the above with JC removed too. This could be a simple drive-select/interface-select configuration error at the jumpers.

**Comment by hikodaci** [comment]
> The green LED is the drive select indicator so if it never lights up, it's no surprise you can't read/write: the drive is never selected! This would also explain why you see the track indicator (`0_`) for a short while but never again: The track number is never changed because the drive is never selected.
> 
> Try the S1 jumper at S0, and also at MO and see if you can get that green LED to light at all.
> 
> If you are at all handy with an oscilloscope or logic analyser you could also look for signs of drive- and motor-select signalling on pins 10, 12, 14, and/or 16.

I tried it M0, S1 and S0 with JC and without JC but there is still no light up of green led.

Also I can see again _0 when I push the right button and it changes from 000 to 001.

**Comment by keirf** [comment]
Then I start to wonder if it is a hardware or cabling problem. You need to fault-find why there is no drive-select reaching the Gotek. 

Another option is to try permanently selecting the Gotek by moving the S1 jumper to be horizontal across S0-JB on the lower of the two rows. This should permanently light the green LED.

**Comment by hikodaci** [comment]
The Gotek is working on the machine with original firmware and its jumper is only S1.

But I want to make it with Flash Floppy.

**Comment by keirf** [comment]
This would not be the first "I only changed the firmware" bug report where the firmware was not to blame.

**Comment by keirf** [comment]
I would revert to jumpers at S1 and JC, those are almost certainly correct. Another thing possibly to try is a single-line FF.CFG containing `chgrst=delay-3`. This changes disk-change reporting. If it doesn't help you can revert to default `chgrst=step`. But my guess now is that in reflashing the Gotek the cabling has been upset.

**Comment by hikodaci** [comment]
Should I make flashing with new one GOTEK? Can this problem be from GOTEK?

And How can I sure the upgrade firmware with flashfloppy is completed as successfully?

I remember the green led is light up yesterday when I try to read the disk, but it wasn't working still on the machine. I don't understand why it is not lighting now?

**Comment by keirf** [comment]
The problem is unlikely to be the Gotek: The LED is basically driven by the host asserting drive-select, there is no smartness on the Gotek side to decide whether to light that LED. Far more likely the drive cable has gone bad or is loose at one end or the other.

If you saw the green LED light yesterday then that is excellent news: The IMG.CFG you copied onto your stick would at that point have been the thing stopping your Gotek from working (the example IMG.CFG overrides the default IMG disk layout and forces it to be a 720k DD PC disk!).

**Comment by keirf** [comment]
If you have a supply of Goteks perhaps you should swap in a factory-firmware one and confirm it still works?

**Comment by hikodaci** [comment]
> If you have a supply of Goteks perhaps you should swap in a factory-firmware one and confirm it still works?

I have another GOTEK which has original firmware. And it is working right now.

**Comment by keirf** [comment]
And green LED lights of course I'm sure.... How weird!

**Comment by hikodaci** [comment]
> The problem is unlikely to be the Gotek: The LED is basically driven by the host asserting drive-select, there is no smartness on the Gotek side to decide whether to light that LED. Far more likely the drive cable has gone bad or is loose at one end or the other.
> 
> If you saw the green LED light yesterday then that is excellent news: The IMG.CFG you copied onto your stick would at that point have been the thing stopping your Gotek from working (the example IMG.CFG overrides the default IMG disk layout and forces it to be a 720k DD PC disk!).

So, What I have to do? Should I upgrade my Gotek again with flash floppy from zero?

Yes, I have put the FF.CFG and IMG.CFG files in USB stick with IMG files at the same time. But now Green Led is not light up never. And I'm sure the cable is not broken.

**Comment by hikodaci** [comment]
> And green LED lights of course I'm sure.... How weird!

Yes, original GOTEK's led is lighting when the machine read or write.

**Comment by keirf** [comment]
Place a jumper horizontally across S0 and JB along lower row (closest to the S0, JB, etc white writing). The green LED should permanently light?

**Comment by hikodaci** [comment]
> Place a jumper horizontally across S0 and JB along lower row (closest to the S0, JB, etc white writing). The green LED should permanently light?

I will try tomorrow and inform you. Thank you for everything and your efforts

**Comment by keirf** [comment]
Yes come back to it tomorrow. Working out why that green LED no longer lights is your focus. I suppose it could be a bad Gotek or jumper or something. It would be very very rare though

**Comment by hikodaci** [comment]
Hi dear,

I fixed the problem, it because of Jumper. My Jumper pin is broken. When I tried to place a jumper horizontally across S0 and JB, the green led flashing and I changed the jumper pin with a new one the green led light permanently. Then I place it S1 and JB my USB stick was operated on it smoothly. Thank you for all your support. You can add the KUKA KRC1 Robot on the list which is working Flash Floppy.

**Comment by hikodaci** [comment]
Last question, Now I can not open the USB stick in windows10. What is your suggestion? I need the IMG files created by machine in the USB stick.

**Comment by keirf** [comment]
What do you mean you can't open it? Stick not recognised?

**Comment by keirf** [comment]
And to be clear: These are blank IMG files that you wrote files to from the KUKA, and now you want to look at these filled IMG files on Windows 10? That should work perfectly fine.

**Comment by hikodaci** [comment]
"You need to format the disk in drive E: before you can use it."

**Comment by hikodaci** [comment]
> And to be clear: These are blank IMG files that you wrote files to from the KUKA, and now you want to look at these filled IMG files on Windows 10? That should work perfectly fine.

There were 2 IMG files which are created by me on Windows10. One of them full and other one was empty.

I upload and download on the Gotek in Kuka, there was no problem. And when I want to search the files on Windows, It gives this error message about USB stick.

**Comment by keirf** [comment]
Somehow the MBR has been lost I suspect. Repartition/reformat as MBR/FAT32 and try again. I don't know how this will have happened, the only reports I get like this are from using the AUTOBOOT file selector on Atari ST and Amiga computers. Of course you are not running an AUTOBOOT file selector.

**Comment by keirf** [comment]
In this state I would assume the stick no longer works in the Gotek either?

**Comment by hikodaci** [comment]
> In this state I would assume the stick no longer works in the Gotek either?

I will try again with the different USB stick for full steps.

**Comment by hikodaci** [comment]
ok. it is working with a new USB stick non problem. I think it was about USB stick error.
