### ISSUE TITLE
Add Yamaha QX5FD MIDI sequencer to supported devices

### ISSUE THREAD

**Issue by chriswareham** [keirf/FlashFloppy#367]
I have tested FlashFloppy firmware v3.16 on a Yamaha QX5FD MIDI sequencer with a Gotek drive. Formatting, saving and loading all work using a blank HFE file generated from the HxC floppy emulator software. Please add this to the supported devices list on the wiki.

I previously tried a HxC drive in the same machine without success. I will order another drive and test the more sophisticated Yamaha QX3 as well, since this exhibits the same issues with a HxC drive - I would test with the Gotek I already have but the QX5FD is a bit awkward to reassemble!

**Comment by chrispoacher** [comment]
Does the QX5FD require an additional adapter or does it connect direct? I’ve heard some horror stories about this and the QX3. J

**Comment by chriswareham** [comment]
I had to extend the power cables on both the QX5FD and QX3, but otherwise no modifications - the original 34 pin connectors are standard Shugart. I also modified my QX1 (yes, I like Yamaha sequencers) to have a HxC rev F, and that just needed a cheap floppy adapter for the cables.

**Comment by keirf** [comment]
Added to the wiki. Thanks!
