### ISSUE TITLE
"rotary" option - unable to set 2 values

### ISSUE THREAD

**Issue by baritonomarchetto** [keirf/FlashFloppy#372]
Hello Keirf,

I am using your software in my AKAI S2000 with no major issues. Only thing is, if I define two values for the "rotary" option in my FF.cfg file, it only gets the first value.

In particular, if I set:

`rotary = full, reverse`

or

`rotary = full ,reverse`

the "reverse" option is ignored.

If instead I set

`rotary = reverse`

the reverse option is set correctly.

I suppose something like

`rotary = half, reverse` could still work, being "half" not the default option, but I did not test it.

I don't think it's relevant, but FF.cfg is under "FF" folder in my specific case.

(thanks for the hard work so far!)

**Comment by keirf** [comment]
No whitespace between options please, only the "," is allowed. Whitespace is allowed around "=". That's just how it is, at the moment at least. The parser is pretty dumb!

**Comment by keirf** [comment]
Ie. set `rotary = full,reverse` exactly like that

**Comment by baritonomarchetto** [comment]
Ok, perfect. Please set the notes on FF accordingly: actually there's a space in the description that could lead some user (like me :)) to use the wrong format ;)

**Comment by keirf** [comment]
I have made it even clearer in the wiki now :)
