### ISSUE TITLE
IMG.CFG giving Error 31 after update to 3.20

### ISSUE THREAD

**Issue by dallday** [keirf/FlashFloppy#381]
I was using version 2.14 of flash floppy and all was working. I have now updated to version 3.20 and it no longer seems to like my IMG.CFG file.
All the images on the USB stick show *err*31 on the oled display and will not load.
The same USB stick works fine under 3.19
I tried adding a tracks parameter and this works fine in version 3.19 but not in 3.20
Not sure what I have done wrong or what I need to do to correct this

IMG.CFG File contains
[default]
cyls = 35
heads = 2
file-layout = interleaved
tracks = 1-35
secs = 18
bps = 256
id=0
mode=mfm
iam = no

Thanks for a brilliant product 
David

**Comment by keirf** [comment]
The default tag is now `[]` instead of `[default]`. You don't need the `tracks=` line so get rid of that.

**Comment by dallday** [comment]
Thanks - that works
