### ISSUE TITLE
Korg 01W FF.cfg to do and error e34

### ISSUE THREAD

**Issue by chacals84** [keirf/FlashFloppy#385]
Hello,

I have 2 Korg 01W : one FD et One Pro X.

I would like to put gotech usb floppy emulator, the korg 01w have a 720 Ko 2DD disk drive.

My 2 gotech are 1,44 one. I put on one gotech flashfloppy and i have error E34 when i put my usb stick.

I format my usb stick in fat32, and i have this error, i couldn't choose a floppy disk on 100 i have on usb stick.

I put FF.CFG with akai for interface. Do i have to do Img.cfg files  too ? And what parameter do i put in ?

Thank you for your answer.

Best Regards.

P.S. : excuse my bad english, i am a french guy ;) ;)

**Comment by keirf** [comment]
What are the image filenames? They should be IMG files (with suffix .IMG) and then they should be detected and work ok.

**Comment by chacals84** [comment]
Hello, thank you for your answer.

I have no image on the 100 floppy disk, i would like to choose a disk to format it with the korg menu, and save the floppy disk i have.

I would like to load with the real floppy disk and disk drive and after save on usb stick.

I couldn't do that ? I must have a img file on floppy disk to enable it with flashfloppy ?

Thank you for you answer

Best regards

**Comment by keirf** [comment]
Yes, but if you can format it on the Korg and you are sure the disk format is PC-style 720kB disks (right?) then you can just make an exactly 720kB size file called whateveryoulike.img on the USB drive.

**Comment by chacals84** [comment]
No, i don't know the format of disk, i would like to knw what FF.CFG or/and IMG.CFG i have to do to make it works. 

I will try tomorow to do like you said a file *.img of 720 Ko ;)

I saw for 01w that we must take the shugart type

thank you, i will tell you if it works.

Best Regards.

**Comment by keirf** [comment]
I think the format is probably 800kB. Anyway, attached here is a 720kB IMG and an 800kB IMG. Both need formatting. You can try formatting/writing each one, and see which works.  Then you can simply format the working one, and then copy it as many times as you like so that you always have a fresh formatted disk image to hand.

[img.zip](https://github.com/keirf/FlashFloppy/files/5461469/img.zip)

**Comment by chacals84** [comment]
Ok, thank you, but, how i format the img you give  ? Sorry, but, i know PC, but not Korg stuff ;) ;)

**Comment by keirf** [comment]
Doesn't the Korg have a "format disk" option in its menus? I know Korg even less than you, I'm sure.

**Comment by chacals84** [comment]
yes, it had, but, i have error E34 on screnn and i could not format with korg menu ;)

I write the image you give to me on 000 et 001 disk, i try this before i go to sleep ;)

**Comment by chacals84** [comment]
I format my usb stick in fat 32 mode, without make 100 floppy disk (i have a 4 Go usb stick).

I put you 720.img i test i have E31 error, and i test 800.img and same error.

I could i make a 713 Ko Img ? How do you create a xxx Ko Img ?

**Comment by keirf** [comment]
Apologies I made a typo creating those images and they're the wrong size!! Hence not recognised.

Here is a replacement zip file with correct sized images :+1: 

[img2.zip](https://github.com/keirf/FlashFloppy/files/5463366/img2.zip)

**Comment by chacals84** [comment]
And, me, i forgot to put FF.CFG to have interfac = akai for korg synthetiser.

I test your image when i return from my job office ;) ;)

Thank you for you rapid answer, if you have a donnation page, give it to me.

**Comment by keirf** [comment]
Just to note, the line you need in FF.CFG is `host = akai`. Probably for interface you want `interface = shugart` but that is the default anyway.

Donations page: https://github.com/keirf/FlashFloppy/wiki/Donations

**Comment by chacals84** [comment]
yes you are right "host" not "interface"

ok for donation page

**Comment by chacals84** [comment]
Yes, yes and reyes it works with the img2.zip. and FF.CFG file with interface = shugart and host = akai.

I took the 720.img file, format it the korg 01w show "formatting" the usb floppy emulator % of formating and korg 01w show "coompleted. I put back original floppy disk drive, load original file A, pub back the usb floppy emulator and save on usb stick the image.

How could i put many img file to have multiple image file with multiple floppy disk.

Thank you for your helpness.

**Comment by keirf** [comment]
If all you have is the three-digit numeric display, you may want to run in indexed mode which is described here: https://github.com/keirf/FlashFloppy/wiki/Initial-Setup#indexed-mode

Essentially all your files are given a numeric name, and they correspond to the 3-digit number on the display.

Then you can simply duplicate your IMG file as many times as you like: DSKA0000.IMG, DSKA0001.IMG, DSKA0002.IMG, ...

**Comment by chacals84** [comment]
I test with 2 images i name FDUFILEA.IMG and FDUFILEB.IMG that correspond on the preload disk file A and B i saved.

Then i have my 3 digit on goteh drive give 000 and 001 for the 2 files, but i don't know which is 000 and 001, but, i have to put oled screen,  rotary button and speaker i buy.

Many thanks i go on donate page you give to me to put 10 euros for you, it's not a lot, but, it's all i could do.

Best Regards.

**Comment by chacals84** [comment]
Ok, i find to put all image files with indexed type 0000_myfilename.img (no prefix i take this option). On my 4 Go i could put 5000 720 Ko disk, cool ;)

**Comment by keirf** [comment]
That's right you can have any suffix (_myfilename) and the prefix is configurable and can even be nothing at all. I guess you read about that :)

**Comment by chacals84** [comment]
Yes, i do donation, i hope you could do good works with it. You could close this issue, thank you very much. Best regards.
