### ISSUE TITLE
Commodore Amiga Reading HD 1.76MB ADF Images.

### ISSUE THREAD

**Issue by Tallguy297** [keirf/FlashFloppy#390]
This is not really an issue rather than an observation.

A while ago a wrote a post to you regarding accessing high density floppy images on the Commodore Amiga, see [here](https://github.com/keirf/FlashFloppy/issues/354).

The documentation I received with the Gotek had stated one of two ways to use the floppy emulator.
Either
1) Copy the AUTORUN.HFE & HXCSDFE.CFG to the root directory of the USB storage device or
2) Copy the FF.CFG & IMG.CFG files to the root directory or FF directory on the USB storage device.

So I did the first one and had no problems accessing images until I went to access high-density floppy images.
After checking some forums, I decided to do both and copy both sets of files on to the USB storage device.
I edited the FF.CFG file and changed the line `interface = shugart` to `interface = amiga`

Now I have no problems accessing or booting from either double-density or high-density disc images either from the software manager menu or directly.
I don't have to double reset or re-eject the ADF image. It works first time, every time without fail.
I am probably stating something completely obvious.
However I haven't had much experience with the Gotek and for me this is an achievement.

I hope this information is useful.
Also, thank you for all your help, software and firmware updates. It is much appreciated.

**Comment by keirf** [comment]
Thanks for the info :)
