### ISSUE TITLE
Multiple disk images

### ISSUE THREAD

**Issue by WauloK** [keirf/FlashFloppy#399]
Hi! I have a GoTek type floppy USB drive for my Amiga 500.
I can load single-load games fine.
I tried with a dual-disk game (Defender of the Crown) and put Disk 1 in slot 1 and Disk 2 in slot 2. I used F7 to restart and it loaded up Disk 1 then said "Insert Disk 2". I pressed the UP button on the GoTek to select the new drive and pressed the OK button but it keeps asking for Disk 2 to be inserted. Do I need to do something else?

**Comment by keirf** [comment]
Have you tried any other multi-disk games?

**Comment by WauloK** [comment]
I downloaded the latest USB files and it works now. Thank you! 👍
