### ISSUE TITLE
ST images with 11 sectors - unreadable

### ISSUE THREAD

**Issue by TzOk83** [keirf/FlashFloppy#40]
ST disk images created in STeEM which have 11 sectors per track appear as empty or garbage in real Atari ST with Gotek/FF, however reported disk capacity is correct. Tested under TOS 1.06D and 2.06D.
[DD_80_11.zip](https://github.com/keirf/FlashFloppy/files/1576802/DD_80_11.zip)

**Comment by keirf** [comment]
Thanks I'll check it out.

**Comment by TzOk83** [comment]
I don't quite get the SD/DD/HD/ED switching routine in img.c. At first I tough that in 11 S/T you may fall into HD, but from my calculations the limit seems to be 1025kB per disk (if tracklen is in bits). 2 sides, 84 tracks, 11 S/T, and 512 B/s gives 924kB, so it is below threshold. Or am I wrong? Maybe the gap3 value is too short?

P.S.
Why it is a gap3, not just a gap? And why it has undeclared (full) length (according to its values, should be 7 bits long).

P.P.S.
When may I expect the next release? Any roadmap for the releases?

**Comment by TzOk83** [comment]
I have found another document which gives some other numbers...
http://docs.mamedev.org/techspecs/floppy.html

Each track begins with a header:
80B of GAP (4E)
15B of SYNC (13B of 00 and 3B of C2)
01B of MARK (FC)
50B of GAP (4E) [VARIABLE LENGTH]
Then the sectors follow:
15B of SYNC (13B of 00 and 3B of 1A)
01B of MARK (FE)
04B of ADDR (TRACK, HEAD, SECTOR, TYPE)
02B of CRC
22B of GAP (4E)
15B of SYNC (13B of 00 and 3B of 1A)
01B of MARK (FB)
512B of USER DATA
2B of CRC
84B of GAP [VARIABLE LENGTH]

This seems to be a document you were using, isn't it? But this still gives me inter sector gap of 104Bytes.

**Comment by keirf** [comment]
I will get round to looking at this next week I think. And start getting releases out again this month after the recent hiatus.

**Comment by TzOk83** [comment]
If you need any additional data, just ask. I have an Atari STE with a working DD floppy drive, a logic analyzer, and a digital storage oscilloscope. So I may capture some data if you need.

**Comment by TzOk83** [comment]
Please see this (page 25):
[Atari-Copy-Protection.pdf](https://github.com/keirf/FlashFloppy/files/1613032/Atari-Copy-Protection.pdf)

**Comment by kodak80** [comment]
Not sure if this helps with fixing the .ST issue but I have tried using a HFE disk image with 11 sectors and it works fine with FlashFloppy firmware on my Gotek.

**Comment by TzOk83** [comment]
.HFE has all the timings inside (I'm not sure, but think it is a raw MFM data), while .ST/.IMG carries only binary sector data, and all the inter-sector gaps and timing have to be calculated by firmware. There is a software to convert .ST to .HFE and it will generate everything what is needed.

**Comment by keirf** [comment]
Thanks. I have all the info I need. Patience please and I will get back with a patch for testing.

**Comment by keirf** [comment]
I have fixed a few bugs with 11-sector DD tracks. The main one was that interleaved ordering emitted sector data incorrectly. Please test the following patched firmware. If it works for read then please also test write (if that is supported by ST for 11-sector disks). If it works I will shortly do a release with the fixed included.

[ff_st_11.zip](https://github.com/keirf/FlashFloppy/files/1631823/ff_st_11.zip)

**Comment by TzOk83** [comment]
Everything seems to work ok. I have not measured times, but it seems to be slightly slower than actual floppy. I don't know why, but FastCopy PRO reports that drive is single sided, yet FastCopy III reads this image correctly.

**Comment by keirf** [comment]
@TzOk83 It's slower than actual floppy on what operation? Copy, read, write? Is this true only for 11-sector images or for 10-sector images too? We will need to do some digging to track this one down, if there's an issue here.

**Comment by TzOk83** [comment]
I'll make measurements on reading/writing speeds, but not today.

**Comment by keirf** [comment]
No problem, let me know as and when. I'm closing this issue, open another for any performance problems.
