### ISSUE TITLE
Akai MPC-60 & FF60 “no floppy disk”

### ISSUE THREAD

**Issue by andr229k** [keirf/FlashFloppy#402]
Dear FlashFloppy Community,
I’m working on getting a Floppy Emulator with Flashfloppy version 3.22 to work proper in Akai MPC-60.

The problem is that sometimes Akai MPC-60 doesn’t recognize the disks and display FF60 “no floppy disk”  on the screen others times it loads smooth.

These are the config settings:
Interface = Shugart
Host = akai

Jumper on s0

**Comment by keirf** [comment]
Try `chgrst=delay-3` in FF.CFG?

**Comment by JoNilsson** [comment]
For the MPC-60 You need to set 

```yml
interface = shugart
host = pc-dos
```
in you FF.CFG
