### ISSUE TITLE
Detailed description of HFE file format.

### ISSUE THREAD

**Issue by Tubatstuff** [keirf/FlashFloppy#408]
All I can find on this subject is the 1.5 page PDF for HFE 1.0.   Leaves a lot to be answered, particularly for later versions of HFE.

Is there **anywhere** a more detailed discussion is posted?

**Comment by keirf** [comment]
The canonical resource would be the HxC implementations. In the libhxcfe loader sources, part of hxcfloppyemulator on sourceforge. There's an implementation in FlashFloppy too: https://github.com/keirf/FlashFloppy/blob/master/src/image/hfe.c

**Comment by keirf** [comment]
I would move this to Discussions but the action has gone awol in the Github UI. So I'll close it instead. If you want to discuss HFE stuff some more, do it under Discussions as this is not a FlashFloppy issue and doesn't belong here. Cheers :)
