### ISSUE TITLE
Ensoniq ASR-X [Non Pro] and Disk not readable

### ISSUE THREAD

**Issue by andr229k** [keirf/FlashFloppy#417]
E: I have this Ensoniq ASR-X [standard version] installed with a Floppy Emulator incl. FlashFloppy. The Ensoniq ASR-X has internal version 2.67 [2.50+ is important to be able to read example ASR-10/EPS 16+ disk as per following [link](https://syntaur.com/tech_asr-x.html)] 
Jumper = S0
Interface = Shugart
Host = ensoniq

S: It initiates the handshake to start loading and then gives the error “Disk not readable”.
D: The attached disk works fine, when using HxC as firmware.
A: Tried various USB-sticks.

**Attachments:**
1. Error message
2. HxC Info [[Link](https://hxc2001.com/download/floppy_drive_emulator/support.htm)]
3. Disk example

![HxC info](https://user-images.githubusercontent.com/52201354/104879145-8f8ac900-595d-11eb-88a2-f77533e68063.JPG)
[TECHSTART-30.zip](https://github.com/keirf/FlashFloppy/files/5828196/TECHSTART-30.zip)
![Error](https://user-images.githubusercontent.com/52201354/104879152-931e5000-595d-11eb-9d85-e75dfc100ed1.jpg)

**Comment by keirf** [comment]
Have you tested on HxC yourself? And if so, what HxC type and what settings?

On FlashFloppy does the load make any progress or does it immediately fail with no obvious disk access?

**Comment by andr229k** [comment]
Ticket can be closed, issue was around the USB-stick itself.
