### ISSUE TITLE
Support for truncated .ADM/.ADL (Acorn ADFS) images?

### ISSUE THREAD

**Issue by rhalkyard** [keirf/flashfloppy#418]
[The host-specific documentation for Acorn systems](https://github.com/keirf/FlashFloppy/wiki/Host-Platforms#acorn-archimedes) points out that some ADFS images are truncated, and must be manually padded to a valid size before FlashFloppy will recognise them. FlashFloppy has support for truncated DFS images (.SSD and .DSD), since truncated ADFS images are also 'out in the wild' and are generated by some tools, it would be nice to have some support for these too.

I realise that this isn't straightforward for a generic .ADF image, since ADFS supports multiple formats of different sizes, but the .ADM and .ADL extensions specify an image in the M or L formats, which have fixed sizes (320K and 640K, respectively). Would it be possible to add support for truncated .ADM and .ADL at least?

**Comment by keirf** [comment]
Here's a more open-ended question: For DFS and ADFS images (SSD, DSD, AD?) should I be interrogating the disk geometry from the image itself? A lot of Beeb/Acorn tools I think do that. And, if that's possible, we may get more reliable geometry detection *and* of course it's then trivial to supporet truncated image files.

For example, DSD is currently always 80-track double-sided, but I think perhaps 40-track may exist too? So there's a DFS example I'm not sure is even 100% correct right now. 40-track would get erroneously extended to 80-track!

Perhaps one for some discussion with Acorn bods...
