### ISSUE TITLE
Issue with 3.2.3 FW and menu software for Amiga.

### ISSUE THREAD

**Issue by SmoothAdmin** [keirf/FlashFloppy#419]
F10 doesn't save and reboot on my A2000. Instead the menu locks up until I do a warm start.
F9 does work, but after adding images past 006 in the menu, saving them, and rebooting, the drive only allows me to choose images 001 to 006, after that it goes back to 001. And I have verified by going back into HFE that the images appear at 007, 008, etc.

**Comment by keirf** [comment]
Are the AUTOBOOT.HFE and HXCSDFE.CFG from FlashFloppy release zip file?

Can you attach an offending HXCSDFE.CFG here, to this ticket?

**Comment by keirf** [comment]
any update?
