### ISSUE TITLE
20x4 LCD display not working

### ISSUE THREAD

**Issue by shift838** [keirf/FlashFloppy#420]
I recently purchased a new GOTEK drive and loaded FlashFloppy 3.23 FW.  I have followed the guide to hook up a 20x4 LCD display with I2C backpack using the 2 x 4.7k resistors but when the unit powers up only the display characters are solid white blocks.  adjusting the contrast control only dims or brightens them.  characters are not readable.  (a 16x2 display works fine)

I have included in the FF.CFG file on the root of the USB 

display-type = lcd-20x04

I have also tried 

display-type = auto

but neither works.  What am I missing ?

**Comment by omikron88** [comment]
Chck the backpack I2C address. It has several choices often, selectable by
jumpers  or zero resistors.

Dne pá 29. 1. 2021 17:06 uživatel shift838 <notifications@github.com>
napsal:

**Comment by shift838** [comment]
I had a bad ground wire!
