### ISSUE TITLE
add Yamaha PSR 1700 to compatibility list

### ISSUE THREAD

**Issue by KARAPAHUU** [keirf/FlashFloppy#421]
Hello everybody and a VERY VERY GREAT thanks for all this work !!!!

I worked for a long time to replace the floppy drive of my Yamaha PSR 1700 keyboard and I never found a really explicit tutorial.

I bought a GOTEK SFRM72-FU.DL drive because the keyboard only reads 720kb floppy disks.

I made a 24-34 pin converter using this table, after several test to find the good configuration

![Yamaha PSR-1700 34-34 convertor](https://user-images.githubusercontent.com/78303465/106383501-c255a800-63c6-11eb-88f3-98ebe63bf23c.PNG)

For this I'm using the Yamaha electronic diagram and this site https://www.linuxrouen.fr/wp/musique-assistee-par-ordinateur-mao/yamaha-psr-620-gotek-sfrm72-fu-dl-emulateur-usb-de-lecteur-de-disquettes-3-5-720-ko-2dd-13799/

![PSR1700-2700_OA1 Floppyanschluss](https://user-images.githubusercontent.com/78303465/106383577-24aea880-63c7-11eb-81d8-6bbc0f6d8983.jpg)

On the GOTEK only the S1 jumper is present
The original firmware 126.F01 was replaced by Flashfloppy 3.23 (cable to cable method) with this method https://www.binarydevotion.com/?p=228
No special configuration (FF.CFG original)
The USB stick is formatted in FAT 32 and I created IMG files with USB_Floppy_Manager_v1.40i (I attach an empty IMG file) 
[FIMG000.zip](https://github.com/keirf/FlashFloppy/files/5899692/FIMG000.zip)

I am so happy and ready to answer your questions. I am preparing a video tutorail and add the link in this issue soon

( so sorry for my poor english)

**Comment by keirf** [comment]
Added to the compatibility list https://github.com/keirf/FlashFloppy/wiki/Host-Platforms#yamaha
Added warning that this is not easy (need to make an adapter to the Yamaha mainboard or FFC connector).

**Comment by KARAPAHUU** [comment]
Ok thanks !

This is the link to my video to explain how craft the converter

https://www.youtube.com/watch?v=s5ZfBuPnyA0&t=19s

**Comment by now-its-dark** [comment]
Here is an adapter design for this purpose, you can find them prebuilt in various places 
https://github.com/marucome09/24PFFCto34P_conv

There is also a super overpriced option from Flexidrive https://floppyemulator.com/products/34-24p1-25adaptor/
