### ISSUE TITLE
Probelem with new Gotek 

### ISSUE THREAD

**Issue by rodospl** [keirf/FlashFloppy#429]
Freshly flashed Gotek with FF 3.23 firmware (conf with OLED), after boot freezes with the information "Reset Flash Configuration". No jumpers are short-circuited, I've tried with different USB sticks.

**Comment by keirf** [comment]
If you have a multimeter check if jumper row JA is shorted, could be bad soldering on underside of the Gotek PCB.

**Comment by rodospl** [comment]
I've already done that, JA isn't shorted

**Comment by keirf** [comment]
Not sure then. Bad Gotek so get another one.
