### ISSUE TITLE
ZSK MSC embroidary machine

### ISSUE THREAD

**Issue by vinibali** [keirf/flashfloppy#431]
Hi!
A friend of mine has an old ZSK from the first years of the 90s. I was not able to read any code with Gotek's original firmware, however  I tried every combination of the jumpers.
This machine works only with 720K drives, does anybody here had some luck with the default settings?

**Comment by vinibali** [comment]
The ideas @keirf mention are working with this device?
[Embroidery Machines #37](https://github.com/keirf/FlashFloppy/issues/37)

**Comment by keirf** [comment]
So are you using FlashFloppy or original firmware?

**Comment by vinibali** [comment]
FlashFloppy at the moment, the first part of the comment was just some historical information :)

**Comment by keirf** [comment]
Is your aim to format/save a new disk. Or do you have existing disks to preserve/transfer?

I would use a double density HFE image and try formatting it on the embroidery machine.
