### ISSUE TITLE
Static in ff.cfg gets overruled by Sub-folders

### ISSUE THREAD

**Issue by andr229k** [keirf/FlashFloppy#446]
I have my boot-disk, FF.cfg and IMAGE_A.CFG on USB-stick root. Additionally I have some sub-folders with other content.

I experience that my Gotek with the latest firmware jumps to the sub-folder, instead of image specified in IMAGE_A.CFG.

Note:
image-on-startup = static
Boot image name added in IMAGE_A.CFG

**Comment by keirf** [comment]
Since v3.x the correct filename is INIT_A.CFG
