### ISSUE TITLE
OLED display showing corrupted data from time to time

### ISSUE THREAD

**Issue by atssada** [keirf/FlashFloppy#459]
Not always reproducible but frequently happening when I am using two Gotek Drives(FlashFloppy 3.23) for A and B drive emulation respectively in PC8801FA.

- Drive A is hardly showing this issue, but Drive B is showing the issue relatively frequent. 
- When I starts with 4mhz mode instead of 8Mhz, issue frequency is reduced pretty much
- When I starts with USB storage unplugged, issue frequency is reduced drastically (almost zero).

And I found the following article to speculate this issue is related to timing of writing data to OLED.
https://learn.adafruit.com/monochrome-oled-breakouts/troubleshooting-2

I hope this can help your fantastic firmware to be flawless.

Best,
Kim.

**Comment by keirf** [comment]
Not a problem I've heard of before, and you see it on both drives in the same system!

Possible causes:
1. System noise -- how long are the cables to the OLEDs?
2. Different/bad OLED models from usual. Did you buy them together? Can you try other OLEDs?

Unfortunately without reproducing this issue, this is unlikely to be fixed/worked-around in firmware.
