### ISSUE TITLE
Provide separated clock & data?

### ISSUE THREAD

**Issue by snhirsch** [keirf/FlashFloppy#467]
I have a legacy system with WDC 1771 controller talking to a pair of ancient Memorex 8" floppy drives.  The controller has no data separator logic and relies on the drive to provide discrete clock and data signals.  Is there any way to do this from a Gotek / FF?  I understand any solution would require custom wiring, but that's something I can handle if the software and hardware is capable.

**Comment by Dietrich-L** [comment]
See issue 351
