### ISSUE TITLE
FF.CFG file and disk images for Akai S950

### ISSUE THREAD

**Issue by nzremo1** [keirf/FlashFloppy#468]
Hi Keir

Many thanks for all of this very helpful information on here. I have purchased an Akai S950 with a Gotek USB reader installed. When I turn the unit on, the screen on the reader says "FlashFloppy v2.14" (white writing on black background).

I believe what I need for the S950 to read the USB stick is a FF.CFG file that is specifically configured for an Akai S950 and some disk image files.

I have come across information on here suggesting the FF.CFG file for an S950 is:

jppc-hdout: As jppc but with high-density select output on pin 2
akai-s950: Legacy alias of jppc-hdou

Unfortunately I have no idea how to configure a FF.CFG file for use in a S950. Is there any chance you could please give me some advice? Do you have access to a FF.CFG file ready to go in an S950? Any help you might be able to provide would be much appreciated.

Best regards from New Zealand.

**Comment by Earthman90** [comment]
it may helps

https://github.com/keirf/flashfloppy/commit/6668abee872e82f7b8d76937f409e1e6c9e403db
