### ISSUE TITLE
firmware 3.23 with fixed skew/interleave on MSDMF (1.68M) images

### ISSUE THREAD

**Issue by gfernval** [keirf/FlashFloppy#480]
Could you build a 3.23 firmware with skew/interleave on MSDMF (1.68M) images fix?
Problem is that 3.24 and 3.25 doesn´t work well with 2 gotek STM based connected (Drive A and Drive B)
to a Ohio Scientific C4P computer (uses HFE images). Appears random writes that trash the HFE images.
It would be advisable to release separate firmware versions optimized for STM and Artery microcontrollers.

thanks

**Comment by keirf** [comment]
There should be no degradation in v3.24, the changes are straightforward and RAM changes affect Artery only. If not the case it needs tracking down and fixing.

**Comment by keirf** [comment]
Here is an automated build immediately after the MSDMF fix but before the Artery changes. You will need to be logged in to Github to download the Artifact at the bottom of the page:
https://github.com/keirf/FlashFloppy/actions/runs/620521215

If it works better than v3.24 with HFE images then there's an issue to be tracked down.

**Comment by gfernval** [comment]
Thanks for the file, it is possible to build the firmware under Windows (using msys32)?

**Comment by keirf** [comment]
You don't need to, it's already built. Unzip the non-debug zip file and use the UPD file within.
