### ISSUE TITLE
Support for Kryoflex or raw flux images?

### ISSUE THREAD

**Issue by sofakng** [keirf/FlashFloppy#487]
Does FlashFloppy support Kryoflex or any raw flux images?  It doesn't appear to so I think this would be great to have as an addition.

**Comment by keirf** [comment]
Not enough ram or usb bandwidth.

**Comment by sofakng** [comment]
Are you sure?  It looks like the HxC firmware supports them.

(I'm not talking about creating them but reading/using them)

**Comment by keirf** [comment]
I'm pretty sure it doesn't and would require conversion to another format such as HFE. The HxC feature list encompasses formats supported by the PC-hosted conversion tool.

**Comment by sofakng** [comment]
Sorry, you are correct.  I was confused by the feature list.
