### ISSUE TITLE
Atari 1040 STFM, FF 3.25, Can't save to disk

### ISSUE THREAD

**Issue by Johnnii360** [keirf/FlashFloppy#491]
Hello there!

I wanted to test my old NEC P6 Monochrome Pinwriter today but can't because 1st Word / Atari Works can't save files to the disk. How can I fix this? Maybe also games can't save to USB but it didn't tested it yet.

**Comment by Johnnii360** [comment]
Very good support from creator here...

**Comment by keirf** [comment]
Writing works on Atari ST. No bug. Check cables, check that image files in usb stick are not read-only, run a test program on ST if you know of one.
