### ISSUE TITLE
Yamaha A3000 showing 0- and 0_ on disk load

### ISSUE THREAD

**Issue by baronvonponce** [keirf/FlashFloppy#499]
After updating from v2.14 to v3.26, the basic LCD red screen on gotek started showing: 0- and 0_ after disk load.

Haven't managed to make a Yamaha A3000 sampler with a 64mb SCSI work with FF yet.

Tried jumpers: S0, S1 and M0 with interface = jc and shugart; also: host = unspecified, the rest of the settings have been kept as were preset.

The disk image files are in many formats: .img and .IMA files generated with WinImage and all the versions available of .hfe files  generated with HxC Software.

Also i tried downgrading FF but stills the same.

Advice will be appreciated

**Comment by keirf** [comment]
So what's the problem? You don't like the new track display? The 0_ display is showing cylinder number and side (top or bottom) during disk accesses. After a pause it should return to 000 (or whatever) to show the disk image number. This is normal, and it isn;t configurable.

**Comment by baronvonponce** [comment]
Hello, Keirf, i'm glad to read you!!

I didn't know the display was a regular setting. The problem, then, is my ignorance and outdated knowledge of FF... Now my device is working and i want to thank you for FlashFloppy!!
