### ISSUE TITLE
Display continually scrolling through directories

### ISSUE THREAD

**Issue by baileyt3** [keirf/FlashFloppy#500]
I installed 3.26 on a GOEX, the display scrolls/flickers through all directories continuously, pressing or rotating the wheel had no effect, installed 3.25 and the problem stopped, working normally.

This is before I connect to my ST, device just powered up with button pressed to do an update, update completes and the issue starts immediately.

**Comment by keirf** [comment]
I will test on the only GOEX board I have, which I think is r1. Do you have an r2 board (it will say on it, after LT.OSD).

**Comment by keirf** [comment]
Okay it is a bug in handling "Enhanced Gotek" models. Please try the following build. Use the non-debug zip file contained within and apply the UPD file as usual.

https://nightly.link/keirf/FlashFloppy/actions/artifacts/71644243.zip

**Comment by baileyt3** [comment]
Hi, just had a look and mine has r3 on it.

**Comment by iancourt** [comment]
> https://nightly.link/keirf/FlashFloppy/actions/artifacts/71644243.zip

Confirming that this build fixed the issue for me on my OpenFlops, flashed in DFU mode.

**Comment by keirf** [comment]
Thanks I need to test it across other goteks and then make a release

**Comment by keirf** [comment]
Fixed in v3.27
