### ISSUE TITLE
Create empty/blank image on USB stick

### ISSUE THREAD

**Issue by roses2uk** [keirf/FlashFloppy#514]
I'm sure this must have been raised before, but I'm blowed if I can find anything in this forum using the search function. So I apologise in advance for wasting your time.

How do I create a blank or empty image on my Gotek's USB stick so that I can save the contents of my sampler's memory as if to a fresh floppy disk? I'm especially referring to a Roland S760 rackmount and a Roland W30 keyboard workstation.

Thx

**Comment by keirf** [comment]
Have a blank image ready to go and then Clone it or Copy and Paste it via the eject menu (available only if you have an OLED display)

**Comment by roses2uk** [comment]
Yeah, I have an OLED display, and have seen those commands. But I don't know how to create a blank image to start with. Any 760/W30 owners care to help? Could I just not overwrite one of the existing images on the USB stick (as I have backups on my PC)?

**Comment by keirf** [comment]
Yes that would work
