### ISSUE TITLE
Akai s900 flash floppy read only one img

### ISSUE THREAD

**Issue by chrismkz** [keirf/FlashFloppy#518]
Hi all just flashed a gotek with flash floppy for my sampler s900. I create an img file and format it with the akai then create others dsk0002 etc… but just can’t navigate even if I choose indexed mod . Any ideas will be appreciated thx

**Comment by keirf** [comment]
What Gotek PCB model (it is written on the PCB, visible near floppy ribbon connector)?

**Comment by chrismkz** [comment]
Sfrkc30.at47

**Comment by chrismkz** [comment]
Sfrkc30at4.7

**Comment by chrismkz** [comment]
Got an sfrc92at3 which pertectky white hxc image

**Comment by chrismkz** [comment]
Solved the problem comes from the last flashfloppy  3.27 . I flash with 3.25 and  It works

**Comment by keirf** [comment]
This issue was addressed in v3.28 can you please try that version. It is the latest.

**Comment by keirf** [comment]
If it doesn't work can you work out which version introduces the problem. And is this a gotek with just the buttons for input (no rotary encoder)?

**Comment by chrismkz** [comment]
It is a gotek with button . And the 3.27 doesn’t work . Will try the 3.28 and keep you inform

**Comment by chrismkz** [comment]
It works with 3.28

**Comment by chrismkz** [comment]
Thx

**Comment by chrismkz** [comment]
Now will try with a s950

**Comment by chrismkz** [comment]
Make it work on akai s01, but on emu esi2000 the sampler ask for a floppy'please insert floppy’ will work on that now
