### ISSUE TITLE
UFA1M44-100 emulator floppy

### ISSUE THREAD

**Issue by biomedicalahmed** [keirf/FlashFloppy#526]
This type is USB front and USB back
![11111](https://user-images.githubusercontent.com/73754880/131260174-e3230ff7-a555-48e9-a58e-709629bd1998.jpg)

does it need to proceed flash floppy?
if yes
it has two sockets U2- 7 holes(j3-j4)
U1 7 holes(j1-j2)

**Comment by keirf** [comment]
Cannot be used with FlashFloppy.
