### ISSUE TITLE
Rotary connection re-routing

### ISSUE THREAD

**Issue by andr229k** [keirf/FlashFloppy#530]
I ordered a used AT32Gotek LQFP 64 on eBay, where the seller had a failed attempt to solder a wire into the pin-holes for Rotary-mod beside the OLED, maybe due to too much heat. 

Would it or is it possible to choose the back pins for rotary [Have the option to choose the routing], like we had at the start of the AT32 migration, so I can save this Gotek?

**Comment by keirf** [comment]
It is not worth the effort for one Gotek.

**Comment by andr229k** [comment]
Issue resolved by using alternative entry point as per attached screenshot
![image](https://user-images.githubusercontent.com/52201354/133661796-3161b5ce-529f-4e70-bc81-224f261c3e01.png)

**Comment by keirf** [comment]
Good call. Hadn't realised it was this model with the extra pins!
