### ISSUE TITLE
An unseen model: SFRA619

### ISSUE THREAD

**Issue by denjhang** [keirf/FlashFloppy#531]
![22B7EA3855BD841B0CB11D5D4D50688B](https://user-images.githubusercontent.com/61811583/132174169-21949b7b-feb5-49dc-871c-860f3a6c6772.png)
![6C04218C58D30CE7159366FBFEC80BE8](https://user-images.githubusercontent.com/61811583/132174173-49ba7166-af6a-4a54-aaf1-2359d999fce8.png)

**Comment by keirf** [comment]
Does it work?

**Comment by denjhang** [comment]
I tried it a bit, and successfully uploaded the firmware using DFU mode (I used a USB male-to-male cable and directly connected it to my computer). The OLED mini display has been installed, but I found that the modified version of the PCB does not have DT And CLK leads, so it is impossible to install a rotary encoder (unless I use a flying lead).

**Comment by keirf** [comment]
I think it must be an old model.

**Comment by duca750** [comment]
It is not old, I have received two for my equipment today, has someone found a solution for the rotary encoder? Thanks.

**Comment by keirf** [comment]
Depending where you got it from it could have sat in stock a long time. It doesn't look very shiny and new. Compare usb socket on this ticket of a brand new model: https://github.com/keirf/FlashFloppy/issues/539

**Comment by wistal** [comment]
Just leave a comment to confirm this model works, I got this model recently, after flash the FF firmware, it works well, and it also supports OLED screen.
UART header in J4 and 4 pin i2c header in J7 as above picture.

**Comment by WellsWang** [comment]
> It is not old, I have received two for my equipment today, has someone found a solution for the rotary encoder? Thanks.

You can fly wires from PC10/PC11 (PIN 78/79 ) of STM32F105 to enable rotary encoder. I tried it and it works fine.
