### ISSUE TITLE
Error with parsing config file, pin 2,34 didn't change state

### ISSUE THREAD

**Issue by z-op** [keirf/FlashFloppy#536]
Seems to be regression.
HW: SFRKC30.AT4 AT32F415RBT6
Step to reproduce:
1. Flashing stable or alfa version.
2. place some.IMA
3. place FF.CFG in the root folder or /FF/ with contents:
pin02 = low
pin34 = low
result: this pins does not change state and always hi-level.

**Comment by keirf** [comment]
Pins 2 and 34 will only be driven low when the drive is selected. Have you pulled the relevant select pin (eg. pin10 = S0, pin12 = S1) low before checking pins 2 and 34?

**Comment by keirf** [comment]
Confirmed correct behaviour on SFRKC30.AT4 with FlashFloppy v3.28.
