### ISSUE TITLE
Gotek board sfrkc30.at4

### ISSUE THREAD

**Issue by martingclark** [keirf/FlashFloppy#538]
Just received a board of the above designation, dont know if its fully supported yet, i do know sometimes adf's which are on my usb dont show up when booting the gotek, is this an issue anyone has seen ?
Have i been sent an incompatible drive ? Firmware i got it sent to me with is 3.28

Thanks #

**Comment by keirf** [comment]
Should be fully supported in 3.28 firmware. Perhaps your stick or its filesystem is causing a problem somehow?
