### ISSUE TITLE
Support for OS/2 XDF format

### ISSUE THREAD

**Issue by thecanislupus** [keirf/FlashFloppy#54]
Hi
I would like to use the Floppy Flash to install the OS/2 4.0 from floppy images.
The problem is that there is no support for images with 1.8Mb. See below:

-rw-r--r-- 1 t t 1474560 Dez 24  1996 Installation Disk00.img
-rw-r--r-- 1 t t 1474560 Dez 24  1996 Installation Disk01.img
-rw-r--r-- 1 t t 1474560 Dez 24  1996 Installation Disk02.img
-rw-r--r-- 1 t t 1884160 Dez 24  1996 Installation Disk03.img
-rw-r--r-- 1 t t 1884160 Dez 24  1996 Installation Disk04.img
-rw-r--r-- 1 t t 1884160 Dez 24  1996 Installation Disk05.img
-rw-r--r-- 1 t t 1884160 Dez 24  1996 Installation Disk06.img
-rw-r--r-- 1 t t 1884160 Dez 24  1996 Installation Disk07.img
-rw-r--r-- 1 t t 1884160 Dez 24  1996 Installation Disk08.img
-rw-r--r-- 1 t t 1884160 Dez 24  1996 Installation Disk09.img

I found same information on this page: http://www.os2museum.com/wp/the-xdf-diskette-format/
Is there support for these image formats?

Thx
Thiago

**Comment by keirf** [comment]
Yes would like to support this.

**Comment by claunia** [comment]
Related to https://github.com/keirf/Disk-Utilities/issues/50

**Comment by claunia** [comment]
A good description is here.
Images should arrive your email soon.
In a nutshell:
Real XDF layout: Track 0 Heads 0 & 1 have 19 spt at 512 bps, tracks 1 to 79 have 4 sectors per track, one 8192, one 2048, one 1024, one 512 bytes.
XDF image layout: 80 tracks 23 spt 512 bps.

The XDF format is divided in two pieces: the mini image, and the real image.
The real layout contains the mini image first (FAT16, 2 FATs, 8 sectors, usually contains a test file with the contents of the real image) followed by the real image (FAT16, 1 FAT while BPB indicates two copies, 23 spt). On the real image track 0 (both heads) have sectors missing (23-19) marked as bad.
The XDF image moves everything, the real image is first, the mini image is set where the second copy of the FAT would be placed, and track 0 has 4 sectors of 512 bytes appended to each head.

For 5.25" the values change but the idea remains the same: image is bigger than real, there's a mini image that is first on real disk but placed in 2nd fat space in image.
I have not found any real 5.25" XDF floppy but the fake images created with https://github.com/claunia/CreateXDF can be written to a real floppy using XDFCOPY on a real drive (I tried to write it with FlashFloppy but you already know its not quite working for me).

3.5" ED XDF is supposedly suppoted according to XDFCOPY disassemblies, but neither a real floppy, neither a working image, has been obtained yet.

**Comment by claunia** [comment]
Attached test images in .XDF format and corresponding .HFE format at http://www.claunia.com/XDF.tar.xz

**Comment by keirf** [comment]
I think the crux of your patch is initialize_xdf_maps(). Where did those geometries come from, did you work them out manually or was there an existing resource you could take them from?

**Comment by keirf** [comment]
I guess there's possibly some magic in xdf_open() too, though could you work out geometry from file size only, or is it really necessary to probe the BPB?

**Comment by sftwninja** [comment]
I derived the gemoetries from PCem's floppy tables and my own research on my OS/2 Warp 4 disk set. You don't _have_ to probe the BPB, you could also just compare sizes since all 5 formats are constant, however I only had the 3.5 HD XDF format at hand at the moment.

**Comment by keirf** [comment]
The bit that actually uses the xdf_map is the bit that's missing, right? Could you at least mock up or pseudocode that bit, or document it? The xdf_map arrays are a bit opaque, as to how you'd use them...

**Comment by sftwninja** [comment]
Sure can. I'll post a patch in a bit.

**Comment by sftwninja** [comment]
@keirf let me know if this helps any
sftwninja/FlashFloppy@2415968

**Comment by keirf** [comment]
@sftwninja having just looked at an image vs raw disk myself, I can see what your data structures mean now. I can see how XDF raw data maps onto tracks/sectors for tracks other than zero.

However you don't give much info about track 0, and how sections there map to a real disk. It's definitely not fully sequential, in sector numbering or XDF image layout. What do you think?

**Comment by keirf** [comment]
For example, XDF sectors 0-10 seem to map to side 0, sector ids 129-139.
XDF sectors 12-19 seem to map to side 0, sector ids 1-8.
XDF sectors 22-36 seem to map to side 1, sector ids 129-143.
XDF sectors 42-45 seem to map to side 1, sector ids 144-147.
I guess XDF sectors 11,20-21,37-41 don't get used?
Does this match your knowledge?

**Comment by keirf** [comment]
@claunia do you have anything to add to above comments?

It's really nuts also that sequential sectors in the XDF image can vary back and forth as to which side of the disk they occur on!

**Comment by keirf** [comment]
I have patch nearly ready to go on branch `xdf`. It's just not getting data placement on cylinder 0 quite right yet... Should be small fix and then ready for test :)

**Comment by claunia** [comment]
Hi @keirf, I've been working and could not answer your messages sorry.

Cylinder 0 Side 0 should be the same as the expected physical format, as that contains a mini FAT with a file (destined to have the XDF.COM driver but OS/2 just stored a disk id). From that on all tracks contain several sized disks.

XDF ED is still unknown, I have not yet found a disk.
5.25 HD and 3.5 HD XDF are as the HFE I sent you. Those HFE are created with the real XDFCOPY in a real computer using FlashFloppy for formatting, using images created by my CreateXDF, with the information taken from 86Box/VARCem and testing with OS/2 Warp 3.0 and PC-DOS 2000.

Hope this information is enough.

**Comment by keirf** [comment]
I don't even support regular ED disks yet, I believe (it's implemented but I had only reports of failure with it). So ED XDF is for the future. ;) And there is no DD XDF, and I expect HD 5.25 XDF is rather rare too. So I hope the HD XDF with 11-sector FAT and 14-sector RootDir is all that anyone ever sees, as I have rather hardcoded my support to target that :)

**Comment by keirf** [comment]
By the way fdutils, xdfcopy.c is a great document for the correspondence between the image file and the physical disk. https://github.com/Distrotech/fdutils/blob/master/src/xdfcopy.c

**Comment by keirf** [comment]
XDF (at least the 1840kB 3.5" HD variant) Supported in v2.2a. Please test and raise a new ticket for any issues or requests for further support.
