### ISSUE TITLE
IBM ps/2 30286 not seeing the gotek

### ISSUE THREAD

**Issue by robotalec** [keirf/FlashFloppy#545]
Hey I have been trying to get my IBm ps/2 model 30 286 to see the gotek.  I followed the wiki and removed the 6 and 3 pin and I can get it power but I have tried two goteks.  one it sees but cannot read from and one that it does not see but powers on.

the first gotek was orignally modded for my tandy 1000hx which it works on and i removed most of the ground pins on.  It sees this one but refuses to read any ima/img files i load to a flash.  I can see the gotek sees the files and I know they are good images.

THe second gotek it will get a green light but the computer spits out a 601 error.

ANy help will be great to get either gotek to be recognized

**Comment by WBSTClarke** [comment]
You either need an FF.CFG file with "interface = ibmpc or ibmpc-hdout" or jumper JC to select "interface = ibmpc". This should correctly set up pins 2 and 34. Pin 4 should be low to indicate a 1.44MB drive. If it is connected to the Gotek this should occur as required.
