### ISSUE TITLE
720K disk is not detecting using Gotek on Toshiba T1100 Plus with 26pin connector

### ISSUE THREAD

**Issue by dmitryelj** [keirf/FlashFloppy#549]
Hi all,

Thanks for the cool project. I was trying FlashFloppy with Toshiba T1100 Plus, and there are 2 challenges:
- It can support only 720K floppies
- Motherboard has two 26-pin floppy connectors 

I am using Gotek with the 3.29 firmware. The jumper is in S1 position. The drive is connected using this chinese adapter:
![image](https://user-images.githubusercontent.com/18378056/136911422-2a69cecb-787a-48b9-b6d7-4baf05baa7b5.png)

The USB drive has a FAT system and only one 720K image on it with DOS 3.3. Result: when the PC is trying to access the disk, I can see the LED blinking on Gotek within 1-2s, but then there is only a message "Insert disk...". 

Is it a software issue, or do I need any pinout/hardware changes? I saw a thread about removing two resistors on Gotek but it was for the oscilloscope and I am not sure it is relevant for PC.

Data from the Toshiba T1100 Plus service manual:

Motherboard connector pinout:
![image](https://user-images.githubusercontent.com/18378056/136911541-29658e3d-1e60-411d-a4df-855e0bf40d55.png)

Floppy specs:
![image](https://user-images.githubusercontent.com/18378056/136911600-6be652b4-0f98-44fb-a527-9f723974c32e.png)

Tnx

**Comment by dmitryelj** [comment]
Yes, exactly.

**Comment by keirf** [comment]
If you can boot from drive B, can you then format drive A?

**Comment by keirf** [comment]
Yes, pin 2 is DSKCHG and pin 34 is READY, when `interface=shugart`. That matches and that's why the FlashFloppy interface configuration should be set that way.

Pins 4, 6 don't matter. Motor signals don't matter. Drive Select A doesn't matter (you jumpered S1 which is Drive Sel B).

You could try jumper MO instead of S1 and see what happens.

**Comment by dmitryelj** [comment]
Thanks, I will investigate what causes the higher voltage later.
I tested again Gotek with jumpers M0 and S1 and also tried connection in Drive A and Drive B motherboard ports, there is no difference in all 4 combinations. It makes sense to check with the oscilloscope if there is any difference with the Gotek and real floppy behavior.

Thanks for help, anyway I know a bit better now how it works :)

**Comment by keirf** [comment]
I'll tell you what, it is almost certainly the 6 volt supply. 

The issue is the 74HC04 chip. At Vcc=6v its input-high threshold is above what the 3.3v-supplied MCU can output. So it's a voltage threshold issue.

If you fix the supply voltage to be 5v I'm sure you'll find everything works fine!

**Comment by dmitryelj** [comment]
Cool, thanks for sharing, I'll update the thread when results will be ready
