### ISSUE TITLE
Filename scrolling while choosing an image

### ISSUE THREAD

**Issue by MarcMuc** [keirf/FlashFloppy#56]
It would be better to have the filename already scrolling while choosing one. Sometimes it's hard to see which is the right image if you're using long file/foldernames.

E.g.
Workbench_3.1_ESCOM_(Disk 1 of 6)_Install.adf
Workbench_3.1_ESCOM_(Disk 2 of 6)_Workbench.adf

As alternative it would be good to use both lines to display the filename (fading out the Track-Status).
The track-status is not interesting while searching for a file.

Thanks!

**Comment by keirf** [comment]
Yes scroll is important. Discussed this recently elsewhere. It will be implemented.
