### ISSUE TITLE
Help for IMG.CFG

### ISSUE THREAD

**Issue by Wawavoun** [keirf/flashfloppy#568]
Hello there,

Not really an issue...

I hope to read the joined disk image with my Gotek + FlashFloppy (last update).

I give a look to the IMG.CFG made for TCS systems but this one lack single side single density support.

Is it possible to get the modifications to do for supporting Flex SS SD and DS SD

Many thanks and congratulations for this well done job.
Philippe

[ECFLEX0 - Master0.zip](https://github.com/keirf/FlashFloppy/files/7522826/ECFLEX0.-.Master0.zip)

**Comment by keirf** [comment]
The example DSK/IMG is only 100kB in size. Pretty small. Is it a 40-cylinder image? Also I can only guess at the geometry, but assuming it is like the SD boot track in DD images, I can extrapolate to make a 40-cylinder definition as below.
[IMG.zip](https://github.com/keirf/FlashFloppy/files/7581983/IMG.zip)
