### ISSUE TITLE
SFRBA16 - will "flash floppy" work?

### ISSUE THREAD

**Issue by dippaolo** [keirf/FlashFloppy#573]
Hello
Will "flash floppy" work on SFRBA16 PCB?
https://photos.app.goo.gl/QJjuucvs9Qc2nSN47

**Comment by keirf** [comment]
I don't know 100% but I'm very confident it will work fine. Looks like a normal Gotek with an extra jumper block.

**Comment by dippaolo** [comment]
I confirm that it works.
