### ISSUE TITLE
Device behaves odd and U3 [AT chip] gets very hot

### ISSUE THREAD

**Issue by andr229k** [keirf/flashfloppy#582]
**Environment:**
Gotek SFRKC30.AT2 flashed with Flashfloppy 3.29 to be installed internal in Amiga 500.

**Symptoms:**
Device behaves odd and U3 [AT chip] gets very hot.

**Diagnose:**
N/A

**Actions:**
•	Ensured that IDE is inserted correct pin 1 to pin 1.
•	Checked that voltage from Amiga 500 is not above 5+ voltage
•	Checked U4 for 3.3 V

**Theory:**
U3 is in short circuit and this use too much ampere from regulator.

Any idea, how this can be troubleshooted or diagnosed?

**Comment by keirf** [comment]
Does it get hot if the only connection is the power connection? I would strip the board back, disconnect things like display, connect only 5v power and see if it still gets hot. If so there could be a short circuit (eg bad soldering) so inspect for that. Ultimately may need to try reflowing the MCU. If still no success the MCU could be bad.
