### ISSUE TITLE
Bad EDSK data reads since v4.2a

### ISSUE THREAD

**Issue by keirf** [keirf/FlashFloppy#586]
This is a user report, sent to me by email. It seems that incorrect data is included in EDSK sectors since v4.2a (ie since EDSK became async). Attached is an original EDSK image file, and the result of reading this to HFE via FlashFloppy and Greaseweazle. Note sector contents are not correct despite overall track geometries being correct.

[testimage.tar.gz](https://github.com/keirf/FlashFloppy/files/7712540/testimage.tar.gz)

**Comment by ejona86** [comment]
I didn't get a chance to look at this today. It'll probably be the weekend before I can investigate.

**Comment by keirf** [comment]
User confirmed the fix works for him. Thanks!
