### ISSUE TITLE
v4.1a - 4.4a Direct Access Mode on Amiga: "ERROR ... LBA Change test failed! Write issue?"

### ISSUE THREAD

**Issue by Tallguy297** [keirf/flashfloppy#596]
I flashed my Gotek with the latest version 4.4a firmware.
When I reset my Amiga and used the Software selector I received this error...
`ERROR! LBA Change test failed! Write issue?`, then the drive changes to direct access mode.
I have reflashed the Gotek with previous firmware versions from 4.1a to 4.3a.
Same error each time.

There is no problem using firmware version 3.29 and earlier.

**Comment by lordoftears** [comment]
I am experiencing the same identical issue

**Comment by andiweli** [comment]
Same experience with latest 4.4a on a GoEX drive. 
Booting from preconfigured ADF disks on my A1200 works, only AUTOBOOT.HFE/FileSelector refuses and shows this bug.

**Comment by lordoftears** [comment]
I did some tests. I can launch the adf files I already had in autoboot, but I cannot boot autoboot itself (same error as in topic title). Last firmware working is 3.29

Emanuele
________________________________

**Comment by keirf** [comment]
There is no need for further user testing. It is definitely borked! :)

**Comment by ejona86** [comment]
@keirf, did you take a look with a logic analyzer? A logic recording would be useful if it is easy.

It'll probably be a week more before I'm able to try to reproduce by adding code to ff-testbed. I've read through my async porting commit and don't see any obvious bugs, especially for SET_LBA which I didn't change. That has me figuring this is likely a timing/buffering issue, but I'd be happy if it were a simple bug instead.

**Comment by keirf** [comment]
@ejona86 I have not found time to investigate as yet. This may require repro and serial debugging with an actual Amiga, as of course testbed does already make use of DA mode with no problems.

Some people have seen this error on Amiga AUTOBOOT fairly reliably from cold boot since forever. I never repro'ed that. With luck it could be the same bug somehow made 100% probable here (wishful thinking).

**Comment by Liriel-666** [comment]
Same error on atari st 4.1-4.4a

Last Version that work on my gotek with  Artery  chip is 3.30

**Comment by gearmesh** [comment]
I have it with 4.4a on an Amiga 1000

**Comment by tacksetB** [comment]
Same bug on Amiga 500 with an AT32F415 Gotek and FF 4.5a pre-release

Had to downgrade the firmware to FF 3.34 to make my Gotek work again.

**Comment by keirf** [comment]
Okay I debugged this and it was a pretty simple issue to do with the write-protect line status. It's fixed now and I've released v4.6a

**Comment by ejona86** [comment]
The bug was introduced in 1937c174d798f4ae42aa55f9abe55492fdb3e4c1
