### ISSUE TITLE
Image sizes beyond 2.88MB

### ISSUE THREAD

**Issue by gen-angry** [keirf/flashfloppy#598]
Hello,

I use a program called 'UltraISO' to generate floppy images that I use for my DOS rig. I use it to make images ranging from 180KB to 2.88MB which all work great. 

It has the option to make '5.76MB' disk images (I'm not sure what these are), 20.8MB Floptical images, and 120MB LS-120 images (as well as 240MB).  

I tried adding the following in FF.CFG (info taken from ultraiso's image info page).

```
# 5.76mb in ultraiso
#
[::5898240]
cyls = 80
heads = 4
secs = 36
bps = 512

# 20.8mb in ultraiso
#
[::20818944]
cyls = 251
heads = 6
secs = 27
bps = 512

# 120mb in ultraiso
#
[::125829120]
cyls = 240
heads = 32
secs = 32
bps = 512
```

but still get an error 31. Currently using FF v4.4a.

I'm not sure how feasible it is to get these working or if it even is a stupid idea altogether but... here we are. Would it even be feasible or even possible to get these larger images working with FlashFloppy? 

Thanks for hearing me out anyways :)

**Comment by keirf** [comment]
A real physical floppy drive has only one head signal, so only two heads maximum is physically possible.
