### ISSUE TITLE
Casio FZ10M – Disk Error

### ISSUE THREAD

**Issue by andr229k** [keirf/flashfloppy#600]
**Environment:**
Gotek installed with Flashfloppy 3.29 and jumper on S0.

interface = Shugart
host = casio

**Diagnose:**
Above setup was tested with another floppy emulator, which worked without issues.

**Symptoms:**
Casio FZ10M is able to see the disk, but give the error “Disk Error”, when trying to execute load. [See screenshot]

**Actions:**
•	Tested different usb-sticks [problem remained]
•	Tried to install this Floppy emulator drive in another Casio sampler [problem remained]

Any ideas or suggestions to investigate, if the Floppy Emulator is “defect”? 

**Screenshot:**
![npszprwetabmadonkmqr](https://user-images.githubusercontent.com/52201354/149837239-a7c3d988-b6c0-4831-b65e-4663f72bb4f3.jpg)

**Demo image:**
[Cello_Violin.hfe.txt](https://github.com/keirf/flashfloppy/files/7884658/Cello_Violin.hfe.txt)

**Comment by Dietrich-L** [comment]
I suggest to remove the .txt extension

**Comment by andr229k** [comment]
> I suggest to remove the .txt extension

No, then you cannot upload it to GitHub.

**Comment by keirf** [comment]
What other floppy emulator did you test? Another Gotek? With FlashFloppy?

**Comment by andr229k** [comment]
> What other floppy emulator did you test? Another Gotek? With FlashFloppy?

Hi Keir,

Thank you for the reply.

The Gotek model is SFRC922D, which means that it is a STM32 revision.

**Comment by keirf** [comment]
If another Gotek works then this Gotek is clearly at fault.

**Comment by andr229k** [comment]
> If another Gotek works then this Gotek is clearly at fault.

I will try get the drive tested with something else
