### ISSUE TITLE
Can't access to GOTEK from MS-DOS

### ISSUE THREAD

**Issue by 8art33z** [keirf/flashfloppy#601]
Would you please let me know how can I boot MS-DOS from a GOTEK which is upgraded with FlashFloppy firmware? I tried many times to format an empty image file and access the image contents from drive A: (which is the Gotek); It tries to access for some seconds. I can see the activity from the LED and the LCD display but eventually it doesn't work and everything stops. Same thing happens during the MS-DOS boot.

**Comment by davidvrootech** [comment]
![16428546987017982975364107361394](https://user-images.githubusercontent.com/80770494/150638648-b9f3d7f9-c421-4ee2-9715-beb936bdc957.jpg)
This is what I get with firmware 4.4a running on the SFRC922AT3. I have tried different flash drives and settings.

**Comment by keirf** [comment]
@davidvrootech Problem may be filesystem in the IMG file. Block level problems would give explicit access errors.

**Comment by 8art33z** [comment]
For me file FF.CFG do the trick. Jumper JC didn't work with my latest "crippled version" of GOTEK.

**Comment by keirf** [comment]
Gotek board KC30AT2 does not have a JC jumper unfortunately. You will see JC is not labelled on the PCB.

**Comment by 8art33z** [comment]
> Gotek board KC30AT2 does not have a JC jumper unfortunately. You will see JC is not labelled on the PCB.

That's it!
