### ISSUE TITLE
Amiga SCP & IPF images

### ISSUE THREAD

**Issue by merlinkv** [keirf/flashfloppy#604]
Hello Keirf.

First of all, I know about the HxC software to convert floppy image types, but I want to ask you if it's possible to add native support for SCP and IPF disk images.

I have made backups of all my original games using Greaseweazle (SCP format) and I can use these images in WinUAE or I can save again to new real disks. All disks works without problems. The same with IPF and my Kryoflux,

But I cannot use the SCP images directly with Flashfloppy. I need to convert these images to HFE format and the conversions aren't 100% accurate in some cases resulting in "bad disks".

Do you think that will be possible to include native support for SCP & IPF?

Thanks for your work.

**Comment by keirf** [comment]
SCP is impossible without more USB bandwidth or more RAM. The files are too large for streaming over Full Speed USB.

IPF needs more RAM (and possibly CPU) for decoding. I am trialling a new pin-compatible chip for allowing this. But it is future work, and the chip is not yet readily available. It will not be possible on existing Gotek hardware.
