### ISSUE TITLE
ERROR: writesector -> failure while seeking the track 00! - hardware issue

### ISSUE THREAD

**Issue by mamut-tme** [keirf/flashfloppy#605]
I want the community to know, what was in my case the root cause of the problem:
`ERROR: writesector -> failure while seeking the track 00!`

I couldn't make my gotek work on my friends Atari ST, on my Amiga 500 it worked, but the HxC Selector would display the above error message. The Amiga Test kit wouldn't pass the read test. I suspected the 7404 buffer, since my hardware had a HC series element, so I replaced it with a HCT series part. No luck with that cause. Then I started probing the board when running the read test in Amiga Test kit. It came out, that the signal dissapears before the Q2 transistor. I desoldered it and there it was! The transistor had a shortcut between G-S. I measured all other transistors, Q3 had the same issue. Temporarily I soldered some BC547 which I had in my drawer (through-hole, of course) and the problem is solved for now.

So if anyone has or will have a similar problem simply check with a multimeter if there is a shortcut on the transistors. Though I recommend putting there some real MosFETs, due to the low resistance when on (BC547 or any other bipolar transistor will have a voltage drop of 0,2V, which will not cause the voltage on the ribbon cable to go to exact 0V, which is still in tolerance of TTL, but maybe, in some computer it will be a problem). I think I will put there some 2N7002, which my local supplier has in stock. In my case, the transistors were most probably shot from the beginning, because it never worked.

I don't know, maybe its a good idea to add this to the troubleshooting section of the wiki?

**Comment by keirf** [comment]
The Goteks are cheap, not completely QCed, and there will be odd problems with a very small percentage of them. The hardware problems are somewhat random however -- fault-finding skills are required to track down specific problems, and it's outside the scope of the wiki.
