### ISSUE TITLE
Akai s900 should say S0 "host platforms" 

### ISSUE THREAD

**Issue by ilantz** [keirf/flashfloppy#608]
I've followed the note to set the jumper to S1 for S900, but accessing the disk feature on the akai triggered the "OOPS! Disk not mounted." error. setting the jumper to S0 solves it. 

Got a Gotek SFRKC30.AT2, running fp 3.30, and an Akai s900

** had a fatal typo across here... edited the original title and body of the issue. it is S0 which is working.

**Comment by keirf** [comment]
Which note is this? https://github.com/keirf/flashfloppy/wiki/Host-Platforms#akai states that the jumper position is usually S0 for all Akai, and there is no further mention of jumper setting for S900 specifically.

**Comment by ilantz** [comment]
Right, but in there, the heading/title of "S01, S900:" had me understanding that it should be S01 for S900... perhaps would be worth to just remove "S01, "

**Comment by keirf** [comment]
But SO1 is legitimately an Akai model.

**Comment by ilantz** [comment]
🤦‍♂️ gotcha. complete oversight on my part.
