### ISSUE TITLE
0.96" GME64128-11 128x64 display garbaged and is rotated by 90 degrees 

### ISSUE THREAD

**Issue by RetroJeff** [keirf/flashfloppy#627]
Platform: GoTek Artery 
I have two 0.96" VER64x128 VER:3.2 GME64128-11 displays is rotated by 90 degrees and is garbaged after halfway through the 3 line.  I have tried -rotate and every other display option.  I have uploaded 2 pictures, one of the garbage and a 2nd of the back of the PCB.

I have tested this on 2 different GoTek's with the same results and both GoTeks work with a 1.3" 128x64 display using the 128x64 display option.

It's a nice form-factor that fits inside the case

Suggestions ?
Jeff
![IMG_8385](https://user-images.githubusercontent.com/102201404/159616832-f9298b26-b10c-45b0-9005-c4272ada7aa6.JPG)
![IMG_8386](https://user-images.githubusercontent.com/102201404/159616854-68b9dcee-81af-4eee-b0b3-dbde52bda4da.JPG)

**Comment by keirf** [comment]
No plans for support of this type.
