### ISSUE TITLE
Some games of sharp X1 have image errors.

### ISSUE THREAD

**Issue by SoukinOKATU** [keirf/flashfloppy#637]
I now use the firmware of 4.4a and use it to sharp X1 turbo.The interface has used Shugart and jppc respectively
But there are two strange questions:
1.ys1, occasionally after the title, the game freezes at the beginning (the sound will get stuck)
2. Space Harrier, I have two kinds of images, 2D and D88, but the two images are normal in the emulator. However, on x1turbo（Convert to HDF format）, the title screen lacks the option menu, and after entering the game, the whole picture is wrong. There is no music but sound effect
Images of both games can be found in "Neo Kobe sharp X1" on archive.org,And they can all run on the emulator
Here are the images of the two games
[X1.zip](https://github.com/keirf/flashfloppy/files/8479751/X1.zip)
.

**Comment by keirf** [comment]
Is there any difference in behaviour using v3.30 firmware?

**Comment by keirf** [comment]
And indeed are you sure these titles should run 100% on your hardware eg with real floppy drive.

**Comment by SoukinOKATU** [comment]
> 

It can be confirmed that ys1 using a real floppy drive is normal (yes, I have purchased a floppy disk)

But I only have a virtual image, and this image seems to be encrypted and cannot be copied into an empty floppy disk

**Comment by SoukinOKATU** [comment]
Previously, a Japanese researcher saw that using the hxc floppy disk emulator, Space Harrier title screen  is indeed normal (with menu options)
![20220414104819](https://user-images.githubusercontent.com/32446208/163303913-876d8eaf-4092-4f07-8649-8969ee9fb457.jpg)
The screen running with the emulator is also normal.But if it run with gotek, the option text in the middle will disappear.
![20220414104944](https://user-images.githubusercontent.com/32446208/163304106-3b2336cb-2341-4d1a-a797-b6493ee42c14.jpg)
In the emulator, the normal game is like this,But if it run with gotek, The picture will turn white except for some enemies and main characters
![20220414105010](https://user-images.githubusercontent.com/32446208/163304258-65a30044-a59e-48dd-a5f8-0b58306973db.jpg)

**Comment by keirf** [comment]
May I ask what Gotek type? Artery or STM chip?

**Comment by keirf** [comment]
Do you still wish to pursue this issue?
