### ISSUE TITLE
encoder not working only sw button works

### ISSUE THREAD

**Issue by Danny-VdH** [keirf/flashfloppy#638]
Board sfrkc30.at2
flashfloppy and bootloader 4.3a

from left to right (right side cristal)
left first row
NC
JK = button SW
middle row
DT=encoder A
CLK=encoder B
right row
+5V
GROUND

in FF.cfg
rotary = full
 
check 100 times, don't get it working, please any help, thanks

**Comment by keirf** [comment]
The header is documented here: https://github.com/keirf/flashfloppy/wiki/Hardware-Mods#kc30-rotary-header
