### ISSUE TITLE
Problem with 1.3" screen, left pixel uninitialzed on the right of the screen

### ISSUE THREAD

**Issue by Neo2003** [keirf/FlashFloppy#647]
Tested FF 3.28 and 3.30 with Artery and STM gotek and several screens (all same model)
![écran0](https://user-images.githubusercontent.com/28825/166950691-8c4683ed-28d7-4ac0-a1d2-a0f5fc00f961.jpg)

![PbScreen](https://user-images.githubusercontent.com/28825/166950732-8ae1387e-f8a1-40aa-a5c4-3c3d610fac3a.jpg)

There is always these pixels on the right of the screen where it seems FF does never display anything.

**Comment by keirf** [comment]
Can you try
```
display-type = oled-128x64
````
in FF.CFG (https://github.com/keirf/flashfloppy/wiki/FF.CFG-Configuration-File)

**Comment by Neo2003** [comment]
Yes, it works. I thought auto would be enough.
Many thanks
