### ISSUE TITLE
OLED only displaying static

### ISSUE THREAD

**Issue by 99z** [keirf/flashfloppy#653]
I'm unsure if this is a FlashFloppy issue but figured I'd ask here.

I purchased this for my 500: https://amigastore.eu/en/676-internal-usb-floppy-emulator-gotek-for-amiga-500-600-and-1200.html

Functionally, it works fine. I can boot into the FlashFloppy Selector, load adf files and play. But the OLED always displays static, as shown below:

![IMG_0038](https://user-images.githubusercontent.com/7397825/171517473-9ec34eb0-f0ed-4bc5-b998-04f433bb0daf.jpg)

Neither of the buttons on the side have any effect.

**Comment by keirf** [comment]
Some OLEDs can be problematic. With latest FlashFloppy you could try `display-type=oled-128×32-slow` in FF.CFG to talk more slowly to the OLED.

**Comment by keirf** [comment]
Then I would say your OLED is bad and you should seek a replacement.
