### ISSUE TITLE
Using a USB-C to USB-A cable for firmware programming

### ISSUE THREAD

**Issue by paran01d** [keirf/flashfloppy#655]
Just wanted to document that I have used a USB-C to USB-A cable from a USB-C port on my computer to successfully program both artery and stm goteks. As there quite popular for connecting to modern android mobiles I figured more people would have them laying around than USB-A to USB-A cables.

I tried to update this in the wiki but couldn't figure out how to make a PR.

**Comment by randybb** [comment]
USB-C is just a regular usb 3.1 port whith usb2 and usb3 signals. On a PC it always supports both, but many low cost phones are using only usb2. I don't think this needs to be mentioned.
