### ISSUE TITLE
SPI flash device read/write

### ISSUE THREAD

**Issue by KyleCardoza** [keirf/flashfloppy#658]
Is it possible to add to FlashFloppy the ability to use an SPI flash ROM (one of the little 8-pin models) instead of a USB drive as a medium? Like, use the whole ROM chip as if it were a single disk image? For example, through some otherwise-unused GPIO pins.

**Comment by KyleCardoza** [comment]
I guess that could work -- I could make a flex PCB cable to solder to the footprint. The use case I have in mind is for a custom removable SPI flash ROM, as a sort of "retro disk" format.

**Comment by keirf** [comment]
Oh I see. Not really on my todo pile I'm afraid.
