### ISSUE TITLE
New version of SFRKC30.AT2; IO issues

### ISSUE THREAD

**Issue by bangstk** [keirf/flashfloppy#663]
Hello,

I have SFRKC30.AT2, but unlike what is stated in the wiki, it DOES have a JC header, and a corresponding trace on the board, it goes to the middle hole in 5-pin row of the programming header, and goes all the way down directly into an MCU pin. It seems there is a new revision of SFRKC30.AT2 despite the same name.

![photo_2022-07-03_18-24-32](https://user-images.githubusercontent.com/4380573/177082973-b0d95ec2-3dfe-4a0a-b056-16191cc71825.jpg)

Incidentally, I am having IO pin issues. Using the 3.33 IO test firmware:
WGATE (pin 24) is stuck reading as LOW by the Gotek even if 5V is applied (number 6 never appears)
TRK00 (pin 26) is always outputting 5V and does not toggle LOW with the other outputs

Is it possible the board rev switched some of these pins around? Is there anything I should test to find out? Or is it more likely I have board/MCU damage somehow?

**Comment by keirf** [comment]
Highly unlikely the board is bad and the JC addition is expected. I can fix io test for this board for you to try.

**Comment by keirf** [comment]
Is it usart tx (pa9) that jc is connected to?

**Comment by bangstk** [comment]
Having trouble connecting to the Artery site to get the datasheet; but JC here is connected to the 3rd pin from the left on the bottom side of the MCU (bottom being LED side of the board)

**Comment by keirf** [comment]
Yes that is pin PA9. That was the pin I agreed with factory and JC should just work in that case.

**Comment by keirf** [comment]
I have fixed the io_test, so please try the update file from the following automated build. Just click on the artifact link at the bottom of the page (you will need to be logged into github):
https://github.com/keirf/flashfloppy/actions/runs/2608421537
Let me know how it goes!

**Comment by keirf** [comment]
I'd also like one of these new .AT2 boards for my test collection, if anyone has ordered multiple and has a spare!

**Comment by RetroClinic** [comment]
I've looked at my stock, and without taking them apart, my .AT2 don't have the letters JC printed adjacent to the 3rd header from the right, so I presume that's the older version? The new ones I got last week are .AT3 with the larger chip.

**Comment by keirf** [comment]
> I've looked at my stock, and without taking them apart, my .AT2 don't have the letters JC printed adjacent to the 3rd header from the right, so I presume that's the older version? The new ones I got last week are .AT3 with the larger chip.

That would be right. The new version has JC printed. Thanks for checking!

**Comment by keirf** [comment]
See fixed io-test in v3.34. Please open a new issue if there are further problems.
