### ISSUE TITLE
rotary 'clicking' eject menu

### ISSUE THREAD

**Issue by gen-angry** [keirf/flashfloppy#666]
Hello,

I use a gotek with an oled + rotary on version 3.33. 

If I happen to turn the rotary half of a click, it will load the eject menu. Sometimes it'll do it 'on the way' of a full click, then I end up scrolling through the eject menu and sometimes landing on 'delete' by accident. This has only started to happen recently IIRC but I can't remember nor pinpoint an exact time that it's started to happen.

Is there a way to disable the eject menu entirely (I don't need any of it) or is my rotary just bad?

Thanks and have a great day! :)

**Comment by keirf** [comment]
You cannot disable the eject menu on select button press. You need to replace your encoder, they tend to be cheap and poorly made.
