### ISSUE TITLE
Firmware update via FF.cfg possible?

### ISSUE THREAD

**Issue by olDirdey** [keirf/flashfloppy#677]
Updating the firmware via the USB stick is a nice solution, unfortunately not possible on the fly with rotary only devices. 

Would it be possible to extend the ff.cfg by a function that allows reading the update files from the stick without holding both buttons when inserting?

**Comment by keirf** [comment]
Two more methods:
1. Press the rotary button is equivalent to holding the two legacy buttons
2. If you have oled display then press rotary with no stick inserted to enter main menu. Firmware update is an option on this menu.

**Comment by olDirdey** [comment]
Thank you very much keir. Update worked. I have not noticed the option in the main menu.
