### ISSUE TITLE
Gotek installed in Spectrum+3 not recognising any files

### ISSUE THREAD

**Issue by DAZZADOOBY** [keirf/flashfloppy#680]
I've recently installed a Gotek drive on my Spectrum +3. The display appears fine but it doesn't recognise any files on the USB sticks I've installed. I've tried different sticks with no joy. 
![20220811_181651](https://user-images.githubusercontent.com/60366445/184194388-261865e8-7be7-48c2-bb94-b8f6457d5a49.jpg)

**Comment by keirf** [comment]
Either your Gotek is broken, or your USB sticks are not formatted to FAT32. If you insert a FAT32 formatted USB stick I guarantee the Gotek display will change. Unless it's broken.

**Comment by keirf** [comment]
Oh no! I tell you what are your usb sticks now recognised in a PC? Probably not. Your power connector is wrong way round and you are feeding your sticks 12v and blowing them up one by one. Stop that.

**Comment by DAZZADOOBY** [comment]
Recognised absolutely fine. I bought the +3 cable kit so it's not a voltage issue.Sent from my Galaxy
-------- Original message --------From: Keir Fraser ***@***.***> Date: 11/08/2022  19:03  (GMT+00:00) To: keirf/flashfloppy ***@***.***> Cc: DAZZADOOBY ***@***.***>, Author ***@***.***> Subject: Re: [keirf/flashfloppy] Gotek installed in Spectrum+3 not recognising any files (Issue #680) 
Oh no! I tell you what are your usb sticks now recognised in a PC? Probably not. Your power connector is wrong way round and you are feeding your sticks 12v and blowing them up one by one. Stop that.

**Comment by keirf** [comment]
That's good! Then see my original reply.
