### ISSUE TITLE
TAOBAO Blue Pill - STM32F103 based board still supported?

### ISSUE THREAD

**Issue by ole00** [keirf/flashfloppy#694]
Hi,
I checked out  the hardware branch and would like to build the TB-161 board. Does the recent (ish) code still support that board? I have a STM32F103C8 version of the 'blue pill'  with 128kb flash and 20kb SRAM (I checked wiki which states 32kb SRAM is on the edge). I built the firmware(v3.2) and the bootloader with the main program fits under 128kb. If that board (TB-161) is no longer supported, what is the last FF version that supported the STMF103? Thanks.

**Comment by keirf** [comment]
It should work. 103 is still supported and those old boards are all the same to the firmware.

**Comment by ole00** [comment]
Thanks. Will try that.
