### ISSUE TITLE
Displaying more text with narrow font

### ISSUE THREAD

**Issue by zzarko** [keirf/FlashFloppy#7]
Not an issue, more a small question and/or proposition... When 7x16 font already exists, is it possible to use it on full display width, to display more chars in adf/hfe name? Maybe even to display file extension (or maybe just an indicator, H-hfe, A-adf) in the second row of text, giving more space for the filename?

**Comment by keirf** [comment]
Yes the 7x16 font will be integrated into the main firmware build and # char columns will be configurable via an INI style config file. Very soon :)

Leaving this issue open to track the feature.

**Comment by keirf** [comment]
7x16 font is now integrated into the main build. Remaining work item is a config option to allow 18 chars per row when using the 7x16 font.

**Comment by zzarko** [comment]
GREAT! Thank you!

**Comment by bstrobel** [comment]
And while we are at it, displaying more lines/information on the very common OLED displays with 128x64 (as opposed to the 128x32 ones recommended here)?

Note: My 128x64 with SDD1306 work already with no changes, at least for me. The display is usable. It seems only that every other scan line is skipped and the characters appear somewhat stretched. Aside from that it is working fine though.

**Comment by keirf** [comment]
Yes the question is: what to put on those extra lines. :)

**Comment by tenuke** [comment]
demo effects :>

2017-10-17 21:01 GMT+03:00 Keir Fraser <notifications@github.com>:

**Comment by zzarko** [comment]
Maybe:
- displayng file name in two rows, so no more scrolling
- displaying the name of parent directory or full path (maybe combined with file name)
- current mode (native/autoboot/index)

**Comment by bstrobel** [comment]
How about showing it like this?

```
  Indy3_1.adf
> Indy3_2.adf
  Indy3_3.adf
02/17 T:35 S:0
```
Indy3_2.adf is the select file. In the first line the previous file in the list is displayed, the current file in the second line (marked by "> "), and in the third line we have the next file. Status is in the fourth line.

**Comment by bstrobel** [comment]
And instead of wasting space with the selection marker "> " you could also display the selected file in line2 inverse (black on white instead of white on black).

**Comment by zzarko** [comment]
Wow, Keir, thanks, I'll try this as soon as I can!
