### ISSUE TITLE
2.88 ED disk images

### ISSUE THREAD

**Issue by linuxmaster** [keirf/FlashFloppy#70]
Is it possible to implement support of 2.88 disk images, LS120/240, ZIP100, ZIP250? How we can help you with that?

**Comment by keirf** [comment]
2.88 ED is already "supported" in that an IMG file of the appropriate size will have its geometry auto-detected. So first step is to try an existing ED IMG and see if you can read that okay via FlashFloppy. If not then serial logs from a debug build will be useful.

The data rate of the various super floppy formats is likely too high to be supported by full-speed USB. I think a board based around STM32F4 with HS USB and more RAM for buffering would be needed.

**Comment by TzOk83** [comment]
Neither SuperDisk nor ZIP drives were using Shugart-like interface. These were IDE drives (in external variant - ECP/LPT or USB).

**Comment by keirf** [comment]
Ticket restricted to 2.88 ED disk images (IMG files). Left open for now in case you would like to test this support.

**Comment by keirf** [comment]
Pleease reopen if you wish to test 2.88MB ED
