### ISSUE TITLE
Gotek with roland s760

### ISSUE THREAD

**Issue by shindoja** [keirf/flashfloppy#717]
Hi ! Just got my Gotek SFRKC30.AT2, unmodified, plugged it in the s760, set jumpers to JB and SO. Its say please change disk after showed for .5sec ( Not s760 disk ).

I did format the usb to Master Boot Record, And add the 2.24.OUT file on Roland Website in the root directory also.

Im far from being a code guy hehe

Do i have to put another firmware in the Gotek or do i have to add the FF.CFG file into the usb also ? Dont wanna mess the firmware if i dont need to !

What im I missing to make it work ?

Thanks a lot !

**Comment by keirf** [comment]
Support request belongs in Discussion. You already posted there, and I will respond there.
