### ISSUE TITLE
pin_motor pulldown is not set on gotek_enhanced() (e.g. SFRKC30.AT4.35)

### ISSUE THREAD

**Issue by tdaede** [keirf/flashfloppy#718]
This means if the MOR jumper is not installed for any reason, the motor is considered off.

**Comment by keirf** [comment]
Only if motor-delay is not set to ignore. This mcu pin is pulled up by an external resistor.
Don't set to other than ignore without jumpering MOR.

Possibly the motor hack pin for standard gotek also should have floated instead of pulling down. It doesn't really matter too much either way I think.

**Comment by tdaede** [comment]
On the SFRKC30.AT4.35, it ends up getting pulled up by something. As long as the default is ignore anyway, I think that's OK, but it is a potential source of different behavior between the two models.
