### ISSUE TITLE
add Yamaha RM1x to supported devices

### ISSUE THREAD

**Issue by cursesA** [keirf/flashfloppy#722]
Yamaha RM1x MIDI sequencer confirmed working with the following:

- FlashFloppy 3.38
- Gotek SFRKC30.AT4.35 3 digit 7 segment LED display
- jumper at S1
- interface = ibmpc in FF.CFG

.IMG files on the USB stick also need to be formatted using the RM1x Disk job menu

**Comment by keirf** [comment]
Done, thanks! https://github.com/keirf/flashfloppy/wiki/Host-Platforms#rm1x
