### ISSUE TITLE
issues with RX50 and dual FF goteks in DECmate II

### ISSUE THREAD

**Issue by rsxrsxrsx** [keirf/flashfloppy#746]
i am experiencing a strange issue attempting to use RX50 emulation on two goteks with the latest prerelease FF firmware in a DECmate II system. the first gotek (`SYS:`) that i am booting from is connected to the first floppy controller port on the system board, and functions as expected. it is using a straight-through cable and is jumpered S0. the second gotek (`DAT:`) that i am attempting to format is connected to the second floppy controller port, and does not seem to work. i am using a ribbon cable (have tried multiple positions), and the unit is jumpered S1. both have the following `FF.CFG` and `IMG.CFG`:

`FF.CFG`:
```
host = dec
```

`IMG.CFG`:
```
[hfe]
cyls = 80
heads = 1
secs = 10
interleave = 1
bps = 512
id = 1
rpm = 300
rate = 250
mode = mfm
iam = no
```

for the operating system, these drive pairs are represented as `RX50:` and `RX51:` (`SYS:`), and `RX52:` and `RX53:` (`DAT:`). if i issue a `DIR RX50:` (or `RX51:`), the activity LED on `SYS:` lights up and i am shown the contents of the disk as expected. however, if i issue a `DIR RX52:`, the activity LED on `SYS:` again lights up, and the system hangs. i should be seeing activity on `DAT:` and a listing of the disk image on that drive. as far as i have been able to determine this isn't related to my cabling or jumper setup, so i am wondering if maybe something in firmware is causing this?

**Comment by keirf** [comment]
It doesn't really sound like a firmware issue. Why would the firmware itself behave differently depending on which FDC it is connected to?
