### ISSUE TITLE
Akai MPC-2000 Classic wont boot from Boot-disk

### ISSUE THREAD

**Issue by andr229k** [keirf/flashfloppy#747]
E:
Gotek with Flashfloppy 3.37 installed.
Jumper = S0
interface = ibmpc-hdout
host = akai

S:
Emulator shows the Boot disk on OLED screen, but does only count up to Track 00.1 and stand still as shown on screenshot.

D:
When the boot-disk .HFE is shown on the screen, this indicates that USB-stick is correctly formatted as FAT32.

A:
Tested different USB-sticks sizes and brand, no effect.

Any ideas or suggestions? :)

![pic](https://user-images.githubusercontent.com/52201354/213467900-7152493c-ca07-4eae-9596-a38e719ffd11.jpg)
[Boot disk 1.72.hfe.txt](https://github.com/keirf/flashfloppy/files/10457608/Boot.disk.1.72.hfe.txt)

**Comment by andr229k** [comment]
A:
Updated firmware to 3.38, no effect, still stuck on Track 00.1

**Comment by keirf** [comment]
Is W always shown? Indicates writing to disk. Seems unlikely during boot?

**Comment by andr229k** [comment]
Faulty Gotek build, device thrown out and new made, problem fixed.
