### ISSUE TITLE
Spurious index

### ISSUE THREAD

**Issue by claunia** [keirf/FlashFloppy#75]
Sometimes on read or writes there's a spurious index pulse before the full 200ms, and the 200ms timer resets after this spurious pulse. (checked with a logic analyzer)

**Comment by keirf** [comment]
Please attach a (Saleae?) trace file. Or at least attach a screen capture.

Index pulses aren't guaranteed to be 200ms apart on FlashFloppy, however they would rarely be *closer* than 200ms, except when `index-suppression = no`. So worth a quick look.

**Comment by claunia** [comment]
Oh I set that config.

I can only generate "sigrok" files :/

Or a capture but well, in the /INDEX line, in between the 200ms pulses, there is a pulse every 6ms

**Comment by keirf** [comment]
Don't set `index-suppression = no`, it's only needed for some Acorn systems which use regular index pulses to detect disk-inserted. However, with that option you will see extra 'fake' pulses on every head step and immediately after every write.

I think sigrok format is okay, there's free software to view them I believe?

**Comment by claunia** [comment]
indeed whole libsigrok, dunno if for windows but it's what I used for creating the dump on Linux

**Comment by keirf** [comment]
I use Linux anyway so not a problem.

**Comment by keirf** [comment]
This will be a symptom of `index-suppression = no`. Addressed on other tickets. Closing.
