### ISSUE TITLE
Ensoniq asr 10 cant swapping images 

### ISSUE THREAD

**Issue by grandpuba22** [keirf/flashfloppy#758]
Hello. I have a problem saving the project to 2 discs ensoniq asr10 and akai mpc3000. The flash floppy emulator does not understand changing the image disk. I tried many options in changing the file cfg. settings)cant save to multiple floppies.

**Comment by grandpuba22** [comment]
Anybody has good images for ensoniq asr10 and good config file?to save project with multiple floppies

**Comment by keirf** [comment]
Usually disk change problems are IBMPC vs Shugart interface settings. Have you tried changing `interface=` setting in FF.CFG? And/or adding jumper JC at rear of Gotek?

**Comment by grandpuba22** [comment]
I am changing interface ensoniq asr…nothing happens)shugart and ibmpc not hellping)ensoniq asr works only with ibmpbc-hdout)

**Comment by grandpuba22** [comment]
My drive is eilasung fdd-udd u144k)with ensoniq asr10 it’s only works with hbmpc-hdout host ensoniq.I tried change inteface to shugart or ibmpc it,s not working)I dont know where the jumper jc?

**Comment by keirf** [comment]
You should ask in the discussion area in GitHub or in the FlashFloppy Facebook group. This area is for firmware bugs rather than general support.

**Comment by keirf** [comment]
One last thing for you to try is chgrst=delay-3 in FF.CFG

**Comment by grandpuba22** [comment]
Thanx i will try
