### ISSUE TITLE
Technics KN2000 support

### ISSUE THREAD

**Issue by Erriez** [keirf/flashfloppy#769]
I've a full functional Technics KN2000 keyboard from 1993 and I'm interested in this floppy emulator hardware/software project. The original built-in floppy drive supports 720kB floppy's only with FAT filesystem.

Here is the disk controller schematic with pin-out:
![image](https://user-images.githubusercontent.com/8849873/224541626-b26a0d86-6238-4517-ba84-67b812fa7180.png)

Any suggestion if this will work with a `Gotek Floppy Emulator met Rotary Encoder` or other emulator and how to proceed?

Related links with information:
- https://gotek.nl/technics-kn2000/
- https://torlus.com/floppy/forum/viewtopic.php?f=18&t=1175

**Comment by keirf** [comment]
First you'll need an adapter from 34 pin IDC on the Gotek to the 24 pin probably FFC here. Likely exists as I think some other musical instruments use this 24 pin interface. After that you will need disk images too.

**Comment by Erriez** [comment]
I received an answer from gotek.nl: The pin-out is different as you confirmed (thanks @keirf). The Gotek part should not be a problem, but the challenge is the dimensions to physically fit into the keyboard. I've added related links in the description of this issue.

**Comment by keirf** [comment]
So it looks like gotek.nl can sort you out, from the link you added?

**Comment by Erriez** [comment]
Not really, because they don't have a KN2000 device to test it. So I'm at my own and is a risk as I currently have a working floppy-drive.

**Comment by keirf** [comment]
Do they have the physical adapter available?

**Comment by Erriez** [comment]
A physical adapter is not available due to the low number of KN2000 requests.

**Comment by keirf** [comment]
I see. Without such an adapter you are stuck and Gotek cannot be used with this keyboard.

**Comment by Erriez** [comment]
Looking for this adapter:
![dapter](https://torlus.com/floppy/forum/download/file.php?id=786&sid=5d484bc42c43f0f7fa94232f445baf10)

**Comment by keirf** [comment]
There's a good UK seller who sells a "plug and play" package including Gotek, adapter, and USB drive. The current listing for KN 2000: https://www.ebay.co.uk/itm/134022605591

Reasonable prices for "turnkey", and very friendly, so if you want any pre-sales advice I suggest dropping them a line.
