### ISSUE TITLE
USB Flash / Pendrive looking - WiFi network storage (Samba) client

### ISSUE THREAD

**Issue by mesmariusz** [keirf/FlashFloppy#77]
Hi. 

I have I great looking idea for Golek / FlashFloppy hardware extension, but I'm not sure where could I wrote It (so I decided here). This is not an "issue" in fact, but this is a great looking idea for Gotek hardware extension. And not only for the Gotek!

I'm looking for a solution that I could use "USB Flash Memory" looking (acting) device which (in fact) is a WiFi client of Samba shares existing in the LAN (WLAN). When you put it in some device (in Gotek for example) then for Gotek it looks as an ordinary Flash memory. Gotek doesn't know this is just network Samba shared folder :-)

It looks this is a really nice idea for many old devices with no network storage support. 

And probably I found a way how to do it:
https://cdn-learn.adafruit.com/downloads/pdf/turning-your-raspberry-pi-zero-into-a-usb-gadget.pdf

What do you think about ?

**Comment by keirf** [comment]
It looks plausible though the PiZ will need to act as a USB mass-storage (MSC) device, not an Ethernet or serial device as described in that document. Good luck!

I will close this issue as not directly related to the FlashFloppy software itself.
