### ISSUE TITLE
Yamaha QY700 Gotek crash in Executing... (no Save/Load)

### ISSUE THREAD

**Issue by daftpunker** [keirf/flashfloppy#776]
Hi all

After installing my Gotek SFRKC30AT 3 3.35 – 32KB on the Yamaha QY700 jumper on S1 and JC I can't save or load, In attempts the qy700 remains planted in "Executing" and the gotek does not react

![qy700mio](https://user-images.githubusercontent.com/128594378/229724349-20c8c87d-a7d9-41e6-9bc8-36cff3c9eaf3.jpg)

Even trying to load not the qy700 does not see anything to load even though I select them from the gotek.

I enclose the tested USB sticks:

[Qy700 Trial1.zip](https://github.com/keirf/flashfloppy/files/11145986/Qy700.Trial1.zip)

[Trial2.zip](https://github.com/keirf/flashfloppy/files/11145992/Trial2.zip)

Obviously I also tried to do the factory reset but nothing to do.
Do you have a usb stick ready and working to attach to see if it's a problem with the ff.cfg file?

Thank you for your attention

**Comment by daftpunker** [comment]
No one showed up... can anyone help me? I also tried to format on QY700 the file but .hfe nothing to do whether it is a save or a format or a load it hangs in the initial phase and remains in Executing

**Comment by daftpunker** [comment]
Format
![qy700formatexec](https://github.com/keirf/flashfloppy/assets/128594378/2b1e1fd4-b8b1-406c-bb8b-7c7247c437f6)
![qy700formatexecdisplay](https://github.com/keirf/flashfloppy/assets/128594378/9ccde22f-d39f-40a3-bf89-82f1217859fb)

**Comment by daftpunker** [comment]
Save
![qy700execut](https://github.com/keirf/flashfloppy/assets/128594378/dc1092d2-7e71-4e7e-ae40-c67defb5db49)
![qy700executBlank](https://github.com/keirf/flashfloppy/assets/128594378/3390f8b9-80c5-4d55-8ee4-29a73f3bb0a6)

**Comment by keirf** [comment]
In the first photo back in April the Gotek has a FAT02 error, which is an internal error in the FAT library used by FlashFloppy. Subsequent photos don't show this error though.

**Comment by keirf** [comment]
These disk images are regular PC 1.44MB. You should instead be using IMG files rather than HFE. You will not be able to reliably format (or possibly even save to) HD HFE image files from a Gotek with 32kB RAM. IMG files are much easier to write to.

**Comment by daftpunker** [comment]
Hi Keirf, thanks for the quick response.
1 I changed the jumper configuration, now the jumper is only on S1.

2 I factory reset the Gotek via the menu

3 I have the files that I took over from the first new design QY700. I put them on the USB stick, just the CFG file and the image file. I will send you the contents of the test stick.
Returns error 31
[QY700.zip](https://github.com/keirf/flashfloppy/files/11638687/QY700.zip)
![WhatsApp Image 2023-06-02 at 22 04 55](https://github.com/keirf/flashfloppy/assets/128594378/efe187b1-f332-46f9-9bbc-a254db788a1d)
![WhatsApp Image 2023-06-02 at 22 05 57](https://github.com/keirf/flashfloppy/assets/128594378/b0e1ed44-184f-481f-992a-9a8c339d4f5e)
![WhatsApp Image 2023-06-02 at 22 06 05](https://github.com/keirf/flashfloppy/assets/128594378/365b82b0-0956-4e31-bc2d-549f39a7e33f)
![WhatsApp Image 2023-06-02 at 22 06 05 (1)](https://github.com/keirf/flashfloppy/assets/128594378/323a784e-1f8e-4c11-a9fb-d86821aaf8df)

**Comment by keirf** [comment]
This is because the IMG file is somehow 512 bytes smaller than it should be. It needs to be 1474560 bytes long. Perhaps the HFE image file contained a corrupted sector?

Get yourself a good 1474560 byte IMG file and you should get further.

**Comment by keirf** [comment]
Here is my conversion of qy700_Demo2.hfe to IMG format. Perhaps this is useful?
[qy700_Demo2.zip](https://github.com/keirf/flashfloppy/files/11638947/qy700_Demo2.zip)

**Comment by daftpunker** [comment]
Hi, I tested but nothing changed.
I enclose stick and photos
[QY700keirf.zip](https://github.com/keirf/flashfloppy/files/11641968/QY700keirf.zip)

Test Load: 

![load](https://github.com/keirf/flashfloppy/assets/128594378/ea7f09dd-b987-4956-a83f-91c199950475)
![load gotek](https://github.com/keirf/flashfloppy/assets/128594378/23312e5e-3200-4321-81b4-9af9646d22a8)

Test format: 

![format](https://github.com/keirf/flashfloppy/assets/128594378/2cb50bf0-7075-401c-aee1-9bc7d9b6b551)
![format gotek](https://github.com/keirf/flashfloppy/assets/128594378/d10b8665-9a1a-4575-8494-9971935b0293)

**Comment by daftpunker** [comment]
Always the same result even with this test

[QY700 2.zip](https://github.com/keirf/flashfloppy/files/11642000/QY700.2.zip)


![WhatsApp Image 2023-06-03 at 09 18 49](https://github.com/keirf/flashfloppy/assets/128594378/57095082-f467-4f03-aae7-42ae3292c2ce)


![WhatsApp Image 2023-06-03 at 09 18 51](https://github.com/keirf/flashfloppy/assets/128594378/417919c1-8f12-4840-a88d-e3c71e75405a)


![WhatsApp Image 2023-06-03 at 09 18 52 (2)](https://github.com/keirf/flashfloppy/assets/128594378/efcf12a4-2c19-4b0f-a72b-0c2d1e4daf57)


![WhatsApp Image 2023-06-03 at 09 18 52 (1)](https://github.com/keirf/flashfloppy/assets/128594378/37896474-1aff-4c47-8c52-56637ae46782)

![WhatsApp Image 2023-06-03 at 09 18 52](https://github.com/keirf/flashfloppy/assets/128594378/b244518a-3f38-40c9-8725-9c6c5092b6d3)

![WhatsApp Image 2023-06-03 at 09 18 53](https://github.com/keirf/flashfloppy/assets/128594378/9660d972-7c32-4bb9-847e-7db039f09d4a)

**Comment by keirf** [comment]
Looks fine on Gotek side. Usb stick? No more ideas.

**Comment by daftpunker** [comment]
I tried with different keys formatted and read by other goteks but nothing to do. It remains at T:00.0
