### ISSUE TITLE
Emu ESI-32 Gotek KO SAVE error “Floppy FIFO Overrun”

### ISSUE THREAD

**Issue by daftpunker** [keirf/flashfloppy#777]
Hi guys, I'm having problems saving with my gotek SFRKC30AT 2 on my sampler Emu ESI-32

I enclose a zip with all the contents of the trial usb stick:

[EMU Esi32.zip](https://github.com/keirf/flashfloppy/files/11146122/EMU.Esi32.zip)

The problem occurs only in the save operation, after a few seconds 
![save](https://user-images.githubusercontent.com/128594378/229728896-cb060e39-698b-48b9-9f22-8a8b7034120d.jpg)

the second execution bar stops with this error: "Floppy FIFO Overrun"

![overrun](https://user-images.githubusercontent.com/128594378/229728943-efbc525c-0a32-4d85-a2f4-846f19195342.jpg)

The problem occurs only on the save procedure. Gotek instead reacts well in loading operations

**Comment by keirf** [comment]
Maybe the USB drive is too slow and you have a 415 based Gotek (does it say 32kB on the title page when no USB stick is inserted?). Try another stick. Also consider getting a AT32F435 based Gotek now they are more readily available. Much bigger buffers (384kB RAM).

**Comment by daftpunker** [comment]
![WhatsApp Image 2023-05-23 at 11 36 47](https://github.com/keirf/flashfloppy/assets/128594378/662ade6a-0f7c-497a-adf4-a909a2df99cf)

**Comment by keirf** [comment]
You have no chance of reliably saving to a high-density HFE image from a 32kB Gotek. You either need a 435-based Gotek, or here you switch to 1440kB IMG files. You can convert the HFE images to IMG using HxC software, or Greaseweazle tools. Unlike EMU II (and other EMU double-density instruments) the EMU HD sector format is same as IBM PC.

**Comment by keirf** [comment]
Any more to say on this one, or shall I close it?

**Comment by daftpunker** [comment]
Hi Keirf, changing usb stick with a new one works! He deceived me because the old key works with all the other samplers I have but on this Emu it is indigestible! Yes you can close the post, thanks
