### ISSUE TITLE
Can't read images on Zenith Z100 after formatting

### ISSUE THREAD

**Issue by robdaemon** [keirf/FlashFloppy#783]
I'm attempting to format new images on a Zenith Z100 with the 3.39 firmware, and I'm running into a bit of an issue -

I took an existing image, copied it to a new name on my flash drive, then ran FORMAT /S under Zenith ZDOS (it's basically MS-DOS) - the disk finishes formatting and transferring the system files, but when I continue to write to the disk I get `Sector error writing drive A`

The the machine is treating this as a 48 tpi, 5 1/4" low density drive. The physical drive from this machine is a Mitsubishi MF501A-301UD.

The monitor ROM indicates "MFM 250K 0200h BPS Sector 001-007" during boot, but I'm not sure if that's helpful to you.

I don't have any trouble using existing images, but it's when I format an image to get a blank disk that I start to run into problems.

**Comment by keirf** [comment]
What type of images do you use? The problem is likely lack of ram buffering in the Gotek if you have one of the 415 chip Goteks. The new 435 Goteks are much better (12x more ram)

**Comment by keirf** [comment]
Try another USB stick and failing that if you really need format capability get a larger ram Gotek. They are advertised as at32f435 Goteks.
