### ISSUE TITLE
Acorn Advice

### ISSUE THREAD

**Issue by futaba8u** [keirf/FlashFloppy#79]
I am trying to get my A3010 working with my gotek and all I can get is empty drive message.
Please can you help I have a couple of goteks working with my ST and Amiga but I'm really lost as what to do now.
Thanks.

**Comment by drdpj** [comment]
Latest version of the firmware, in ff.cfg you need to set:
host = acorn
index-suppression = no

Then you should be able to use ADFS sector images (named *.adf) with
impunity, and double (not high) density HFEs. :)

d.

**Comment by futaba8u** [comment]
Thank you for your reply.
I have tried what you have suggested I changed these settings in examples file and then saved and copied the file ff to the usb stick I must be doing something wrong but not sure what?

**Comment by futaba8u** [comment]
Gotek is finding files but still showing empty drive just cannot work out what I am doing wrong

**Comment by keirf** [comment]
Correct jumper setting and ribbon cable inserted correctly?

**Comment by futaba8u** [comment]
I have jumper set on S0 and ribbon cable looks to be correct when turned around green light just stays on!
I must be doing something wrong?

**Comment by futaba8u** [comment]
![untitled](https://user-images.githubusercontent.com/35174821/37793915-e4f3cbdc-2e07-11e8-9cc3-160835edb190.jpg)
This is all I have on my usb stick the FF file is what had been changed to host= acorn and index supression =no

**Comment by keirf** [comment]
Probably need `interface = ibmpc` in FF.CFG?

**Comment by futaba8u** [comment]
Thanks for the help drive now working.
