### ISSUE TITLE
Ensoniq EPS does not boot when Gotek is connected

### ISSUE THREAD

**Issue by t-xxxxxx** [keirf/flashfloppy#793]
Hi,

i want to upgrade my EPS Classic with an Gotek which has the latest Flash Floppy Installed.

I connected the Gotek and made an FF.CFG File from the Hosts list for the Ensoniq EPS. 
But as soon as i power on the Sampler it does not boot at all. It hangs and shows nothing on the Screen.

If i disconnect the Gotek it boots and asks for an Disk. So any ideas what could be the problem, that the EPS does not boot when the Gotek is connected?

**Comment by keirf** [comment]
Does the Gotek itself power up?

**Comment by t-xxxxxx** [comment]
Hi, nevermind it was a defective Floppy Cable. 

So everything works. Thank you.
