### ISSUE TITLE
building the firmware from official source code does not generate the same official firmware

### ISSUE THREAD

**Issue by gfernval** [keirf/flashfloppy#794]
I have downloaded the file https://github.com/keirf/flashfloppy/archive/refs/tags/v3.39.zip (official 3.39 release) 
and compiled it in Ubuntu 20.04 according to the wiki docs:

# sudo apt -y install git gcc-arm-none-eabi python3-pip srecord stm32flash zip unzip wget
# python3 -m pip install --user crcmod intelhex
# unzip flashfloppy-3.39.zip
# cd flashfloppy-3.39
# make dist

It compiles succesfully without problems, but the firmware .hex files generated are not identical to the official firmware. What is the reason?
Different time and date used in the building  of the official firmware? Different compiler versions used in the building? Different HxC_Compat_Mode-v9-FF.zip downloaded from the web?

**Comment by keirf** [comment]
Indeed: different compiler, different compile date.

More importantly by default version is set to the git tree hash. If you want to specify a version number you need `make dist VER=3.39` for example.
