### ISSUE TITLE
ADF Filename Change

### ISSUE THREAD

**Issue by shan2752** [keirf/flashfloppy#798]
Hello,

Thanks for all the great work in creating Flash Floppy!  Is it anyway possible for an ADF file name to be changed within Amiga OS and the change reflected on the USB/SD image file?

This would be extremely helpful if it were possible.  Thanks!

**Comment by keirf** [comment]
Unfortunately not, since the Amiga host knows nothing about the image file names. All it can change is the amigados volume label within the image file itself.

**Comment by shan2752** [comment]
Is there a way to rename an adf file within Flash Floppy?  For example, I have a blank disk ADF called Blank01.adf, I dms extract an archive to this blank, which I want to rename.

Thanks!

**Comment by keirf** [comment]
Nope I'm afraid not. It may get added in future.
