### ISSUE TITLE
USB activity led constantly blinking

### ISSUE THREAD

**Issue by harmund** [keirf/FlashFloppy#80]
Is it really necessary to constantly read from the USB-drive, even when the floppy is not in use? Not only is the blinking annoying, but on some USB-drives the files seem to get corrupted when left running for long periods of time.

**Comment by keirf** [comment]
Floppy drives constantly read while motor running (and Gotek ignores motor signal). Buffer cache post v1.0 will fix this for most images where a cylinder fits in ram.

Endless reads should not wear out Flash devices. Flashing led is too bad, pick one with no led 😊
