### ISSUE TITLE
Need Help: using FlashFloppy as 720KB Drive for PC-XT system

### ISSUE THREAD

**Issue by iosoft** [keirf/flashfloppy#800]
Friends,

I installed FlashFloppy on my Gotek (SFRKC30.AT2).
But I have a 2GB Pen-drive only. This is the lowest size I have.

Now -
- How to configure it to work as 720KB Drive for PC-XT system?
- How to create and upload Disk image(s)? One DOS Boot image.

Regards

**Comment by iosoft** [comment]
> Format stick FAT32 and place 720kb image files on the stick. Place jumpers at rear of Gotek at S1 and JC. Gotek will automatically detect img files and let you select between them.

Thank you for your kind time and suggestion.

1. So, I need to set 2 Jumpers, S1 and JC (currently I have only S1)

![IMG20230506173057p - Copy](https://github.com/keirf/flashfloppy/assets/349968/aed8df72-77bc-4bf1-b1ed-422b2daf6316)

2. Where can I find/create these 720kb image files?
Specially a DOS Boot image.

P.S. Doing it 1st time, so.....

**Comment by keirf** [comment]
Finding images is part of setting up on a new system. For example I can google around for PC DOS boot disks and find this link for early PC-DOS, which looks promising (160kB disk image): https://winworldpc.com/product/pc-dos/1x

I'm sure MS DOS install media images must be out there somewhere too...

**Comment by iosoft** [comment]
Friend, one more small question.

My PC-XT (clone) supports only 360KB or 720KB Floppy Drivers, selected by Jumpers.
So, I set the jumper as 720KB and also the FlashFloppy as 720KB as you suggested above.

![IMG20230205223659](https://github.com/keirf/flashfloppy/assets/349968/d506893b-baec-4a8a-844a-b71f297d111f)

**Question:** 
So I have to upload only 720KB size .img files?
I cannot use/upload any 1.44MB images, right?

**Comment by omikron88** [comment]
1.44MB Floppy uses double bitrate.

Dne pá 23. 6. 2023 9:27 uživatel Ayan Debnath ***@***.***>
napsal:

**Comment by iosoft** [comment]
> 1.44MB Floppy uses double bitrate.

So, not possible right?

**Comment by omikron88** [comment]
No, if the controller cannot be switched for that.

Dne pá 23. 6. 2023 9:39 uživatel Ayan Debnath ***@***.***>
napsal:

**Comment by iosoft** [comment]
> No, if the controller cannot be switched for that.

Ok. I was just asking.... you know that XT-IDE thing can make old system to use High-capacity drives in old systems..... may be that is also possible for FlashFloppy or combined with XT-IDE+FlashFloppy.

That would be cool!
