### ISSUE TITLE
Firmware Update Error [E03]

### ISSUE THREAD

**Issue by JoNilsson** [keirf/flashfloppy#805]
Just got the new release, and tried to update device bought on ebay.  One of these pre-fab deals with the larger 128x64 display and rotary encoder

Keep getting 

```
FF Update Flash
[E03]  
```
Anyone got an idea?

**Comment by keirf** [comment]
Possibly wrong update file copied to the usb stick. There are two in the distribution zip. You can safely copy both to the usb stick and try again.

In any case, E03 means invalid update file or bad signature so perhaps the copy didn't work properly?

**Comment by JoNilsson** [comment]
Thanks for the reply.   

I compiled the distribution and was able to get an update file that worked.  Maybe my download corrupted or likewise.  

Thanks for the quick response.   

Closing issue.
