### ISSUE TITLE
Wiki Host Platforms update request: Yamaha EX5

### ISSUE THREAD

**Issue by jontrulson** [keirf/flashfloppy#806]
Hi,

There does not appear to be a mechanism for submitting a PR for the wiki, so I thought I would just open an issue.

I just wanted to add that this software (3.39) works fine with Yamaha EX5 (and likely EX5R, EX7, and EX7R) synthesizers.

Standard 34 pin cable.  S1 **must** be jumpered instead of S0, and the _interface_  option in FF.CFG set to 'ibmpc'.

Thanks for the great software!

FWIW: Using a SFRKC30AT3 based gotek with 128x32 OLED, rotary encoder and sound mods purchased through reverb.com

**Comment by keirf** [comment]
Thanks for the report. I have added this to the wiki.
