### ISSUE TITLE
If tag name is invalid ([tag::]) all images with this tag will report Error 31

### ISSUE THREAD

**Issue by jjakob** [keirf/flashfloppy#820]
Tags in IMG.CFG need to be in format `[<tagname>][::<filesize>]`. If a tag has the double colon but no filesize, like `[tag::]`, all images with that tag will have Error 31 "Bad Image File". This took me some time to figure out as I thought there was a problem with my images and not with the tag name.
It would be nice if this were reported as a separate error. Perhaps "IMG.CFG syntax error".

**Comment by keirf** [comment]
Unfortunately syntax error reporting for IMG.CFG and FF.CFG is not likely to be implemented in firmware. Possibly I could implement an offline syntax checker in Python.

I could also probably relax the syntax checking in firmware and permit trailing `::`. However the documentation is consistent and correct in associating `::` with a required following filesize.
