### ISSUE TITLE
Formatting in high density

### ISSUE THREAD

**Issue by claunia** [keirf/FlashFloppy#83]
Formatting in high density works randomly.

**Comment by keirf** [comment]
Here's a firmware for you to try. It batches HFE writes so should perform a lot faster on ordinary USB sticks. Let me know how it goes, I can also tune it further if it seems on the right track.

[ff_83_1.zip](https://github.com/keirf/FlashFloppy/files/1852631/ff_83_1.zip)

**Comment by claunia** [comment]
it's gotten worse, now it never works, not even on the SSD were all HD formats did work :/

**Comment by keirf** [comment]
That's weird, might need to test myself, writing HD images from Supercard Pro perhaps. Might need to speed things up by implementing a buffer cache at least for FAT metadata.

**Comment by keirf** [comment]
Please test again with latest FF v2.x.

**Comment by keirf** [comment]
Please reopen or reissue if this persists on v2.12 or later.
