### ISSUE TITLE
64x128 OLED display

### ISSUE THREAD

**Issue by sirdavid2** [keirf/flashfloppy#834]
Would it be possible to add 64x128 OLED display with 90 degrees rotation?

**Comment by keirf** [comment]
No plan for this I'm afraid. With the fonts used I think it would be quite ugly and not fit the display well.

**Comment by sirdavid2** [comment]
Sorry but I don't understand the fonts problem. 128x64 is supported (even with 180 degrees rotation), so 64x128 with 90 or 270 degrees rotation should look exactly the same with the same fonts.

**Comment by keirf** [comment]
Oh I see. I thought you wanted an OLED viewable vertically rather than horizontally. For your usage just get a 128x64 OLED.

**Comment by sirdavid2** [comment]
I already have two 64x128 OLEDS and I wanted to use them somehow. I thought that rotating by 90/270 degrees shouldn't be difficult to add since rotation by 180 already exists.

**Comment by keirf** [comment]
It's much more difficult. 180 degree rotation is simply a command in the oled controller. I think 64x128 doesn't even use the same controller.
