### ISSUE TITLE
Update documentation with settings for Akai S1000

### ISSUE THREAD

**Issue by janvrany** [keirf/flashfloppy#854]
Gotek with FlashFloppy seems to work fine with Akai S1000 but the documentation (wiki) is lacking any details on working configuration. It'd be nice to update it to make easier for others. 
Here's what I propose to be copy-pasted into the wiki:

---

#### S1000:

```
interface = shugart
host = akai
pin02 = nc
pin34 = rdy
nav-mode = native
```

Jumper must be in position S0. Works with 1.6MB (1638400 bytes) `.img` images.
Based on information found at https://sba.io/posts/using-a-gotek-with-akai-s1000/.

---

I'd open PR but do not know how to open a PR for Wiki.

**Comment by keirf** [comment]
Thanks, actually this is exactly same config as S1100, so I will simply update the section heading.
