### ISSUE TITLE
Where is FF.cfg file?

### ISSUE THREAD

**Issue by alex3331** [keirf/flashfloppy#855]
Hi 
I need to rotate my OLED screen, so the advice is to modify FF.CFG file - but where is this file?

**Comment by tenuke** [comment]
Make or copy such text-file into the root of the usb-stick.
Example ff.cfg is in the flashfloppy.zip

ti 5. jouluk. 2023 klo 23.53 alex3331 ***@***.***> kirjoitti:

**Comment by alex3331** [comment]
Tried both
display-type=oled-128x64-rotate
and
display-type=oled-128x64 -rotate
without any luck. Am I missing something?

**Comment by keirf** [comment]
The former should work (no spaces on the line, between sub options). Perhaps filename is wrong or it's not a plain text file.

**Comment by alex3331** [comment]
The file was in flashfloppy 3.41 distribution in examples folder. edited with Notepad

**Comment by keirf** [comment]
This should certainly work: `display-type=oled-128x64-rotate` (no spaces).

If it didn't there is something wrong with the name, location, or filetype of your FF.CFG file.

**Comment by keirf** [comment]
You may also try `display-type=oled-128x64` (in case your display is already rotated, and you need it unrotated).
