### ISSUE TITLE
Slot selection scrolling

### ISSUE THREAD

**Issue by kingoffools2015** [keirf/flashfloppy#857]
after selecting a file in Flashfloppy the slot selection bar to select the slot keeps on scrolling, this makes it impossible to assign the image to a slot.  Does anyone know the cause of this and a solution?

**Comment by keirf** [comment]
I would run Amiga Test Kit and test your keyboard, mouse and joystick. Maybe you have a sticky switch.

**Comment by zhed42** [comment]
hello

j'ai le meme probleme a t"il ete resolu? merci

**Comment by keirf** [comment]
Same: probably a bad joystick or joystick port.

**Comment by zhed42** [comment]
Non car pas de problème avec le lecteur disquette les jeux fonctionne parfaitement
