### ISSUE TITLE
oled not displaying folder name

### ISSUE THREAD

**Issue by nex86** [keirf/flashfloppy#865]
Hello,
I'm using a 128x32px OLED for my project,
I want to see at least folder name and image name, I don't need to see the rest.
so I tried specifying:
display-order = '3,0'

for

0: Current image name
1: Status
2: Image/Volume info
3: Current subfolder name

but all I currently see is the image name, not the folder name...

Any idea?

**Comment by keirf** [comment]
Should be `display-order = 3,0`

Note no single quotes. The example FF.CFG is more than misleading here. I will fix it!
