### ISSUE TITLE
[Enhancement], test mode for oled screen, piezo and encoder.

### ISSUE THREAD

**Issue by ewanuno** [keirf/flashfloppy#866]
i recently assembled a batch of goteks, flashed them with flashfloppy and fitted them with OLED screens, rotary encoders and piezo speakers.

it would be very convenient if a simple test mode was implemented for these hardware mods.

my sugestions as follows:

test mode should be available in the menu when no usb device is attached.

fill the screen with white pixels, so defective screens can be identified.

play a sound on the piezo, 

check direction and button on encoder.

**Comment by keirf** [comment]
I suggest hook up to a Greaseweazle and "gw write" a few tracks of an Amiga ADF or similar. You will also see display working and can test rotary at the same time. And it tests USB. It's a much better overall test than suggested.
