### ISSUE TITLE
Gotek error/issue

### ISSUE THREAD

**Issue by jorgythegreat** [keirf/flashfloppy#869]
Hey, I'm trying to use this with an Akai MPC2000XL and no matter what I do, I cannot update the firmware or load any files onto the MPC. 

The current FF firmware installed is 3.38. I continuously get an error code E01 when trying to update the firmware and the update file is located in the root of the USB. I've tried multiple different update files and they al have the same error, E01.

When trying to load files, the Gotek immediately has an error of 34 which is not config file but the file is present and located in the root of the USB. The USB is formatted to FAT32. 

And, the OLED screen is upside down no matter how many times I have corrected this according to the information located here.

**Comment by keirf** [comment]
What is the model number of your Gotek (it's at the rear of the Gotek on the PCB)? You may be copying the wrong upd file. There are two files with that suffix in recent FlashFloppy distributions, and you can safely copy *both* to the root of your USB stick. The correct one will then be picked up by the update program.

Error 34 is no valid image file found. So what is the name of your image file?

For the upside down display you probably need this in your FF.CFG file:
```
display-type=oled-128x64-rotate
```

It doesn't sound like you're getting *any* files on USB drive picked up by the Gotek at the moment, which is pretty weird.
