### ISSUE TITLE
HFE image cannot be written reliable

### ISSUE THREAD

**Issue by claunia** [keirf/FlashFloppy#87]
When trying to write files to an HFE image, independently of its density, small writes tend to succeed, but big ones fail.

I have not a logic analyze of this behaviour yet, but will provide when time comes.

**Comment by keirf** [comment]
Please re-test this with latest FF v2.x. Should be a lot better now.

**Comment by keirf** [comment]
Please reopen or reissue if this persists on v2.12 or later.
