### ISSUE TITLE
rib error no matter what

### ISSUE THREAD

**Issue by kisikis** [keirf/flashfloppy#872]
I'm having a weird problem in an old IBM-compatible computer.

My Flashfloppy flashed Gotek works great in other old computers (386, Pentium MMX, Pentium 3), but in my old 8088 PC the Gotek's display always reads "rib". I've tried putting the ribbon cable on backwards, tried 4 different ribbon cables, but always the same error. Am I missing something obvious?

**Comment by liveboxandy** [comment]
Is it supposed to be IBM compatible or SHUGART compatible? Early 8088 PC's
supported 4 x floppy drives and the pinout was slightly different.

**Comment by kisikis** [comment]
I've tried setting it to shugart as well, and tried all the suggestions under 'Host Platforms / General Notes'

**Comment by keirf** [comment]
It means several signal lines are grounded for at least one second at startup. Including select, step, write gate. So probably there is some hardware problem here.

**Comment by kisikis** [comment]
The computer is called Santa Clara Systems PCterminal. It is a full 8088 system with a 8087, 640K ram, CGA graphics and floppy connector onboard. Normally it boots straight into connecting via an integrated Novell network adapter to a NetWare server. I have not been able to find a manual or anything much about it. In the very few bits of information I've found on it, there was an optional 360K floppy drive available, making it a normal PC compatible, just no hard drive. It seems like perhaps there was a special cable or special floppy drive required.

Is there a way to figure out the pinout of the floppy connector on the board, without schematics?

**Comment by keirf** [comment]
Perhaps you can trace which pins are hardwired to ground or power rails and which are signal pins, at least?

**Comment by kisikis** [comment]
Okay I've mapped out the connector on the board as far as ground and power. Odd pins 1-33 are all ground. And I get 5V on pins 8, 26, 28, 30. Does that make sense?

**Comment by kisikis** [comment]
I get the same measurements in my Pentium MMX PC, except also 5V on pin 34

**Comment by keirf** [comment]
I suspect it is a regular 34p interface. Perhaps it's simply broken!

**Comment by kisikis** [comment]
Well, thank you for your help anyway.
