### ISSUE TITLE
PC-98 HDI format support (not HDM)

### ISSUE THREAD

**Issue by windship** [keirf/flashfloppy#879]
There's lots of HDI format of PC-98 HDD image because of Anex86 emulator. I think you can find them easily from internet. 
I couldn't find any converter or information about this. FlashFloppy can access HDM format but no way about HDI.

Can you add HDI format support for next update of FlashFloppy? 
You can find some technical information about HDI format here:
https://www.pc98.org/project/doc/hdi.html

**Comment by keirf** [comment]
Example HDI images would be useful.

**Comment by windship** [comment]
[YUNO.zip](https://github.com/keirf/flashfloppy/files/14661664/YUNO.zip)
[Ultima Underworld 2.zip](https://github.com/keirf/flashfloppy/files/14661705/Ultima.Underworld.2.zip)
Please check!

**Comment by windship** [comment]
Hello, any progress?

**Comment by levrin** [comment]
Last I checked, HDI is for hard disk images, not floppies.

**Comment by keirf** [comment]
Yes that is true, and FDI images are already supported. FlashFloppy cannot support HDD images so HDI cannot be supported.

**Comment by windship** [comment]
Hmm but HDM is hard disk image format also and FF support it right?
