### ISSUE TITLE
JC jumper marking on SFRKC30.AT2 board

### ISSUE THREAD

**Issue by dstolpmann** [keirf/flashfloppy#884]
Hi,
the wiki mentions on the [Hardware Mods](https://github.com/keirf/flashfloppy/wiki/Hardware-Mods) page that the SFRKC30.AT2 model of the Gotek does not have JC marked in the usual jumper position. However, my Gotek with this board model does have this marking at exactly the position indicated in the illustration on that page.

Here is a photo of my board:
![gotek_SFRKC30_AT2](https://github.com/keirf/flashfloppy/assets/7644267/ab297c19-0b60-4500-9fea-c1bd6b815bd0)

I am not sure if I got the message wrong or if there are different revisions of this board model.

**Comment by keirf** [comment]
A blue board, how fancy! Anyway, yes, later revisions of the AT2 board do have JC reinstated. And it works.

I have updated the wiki to reflect that only some AT2 boards are missing JC.

Thanks for the report!
