### ISSUE TITLE
E-MU Emulator I Gotek FF

### ISSUE THREAD

**Issue by tsvines** [keirf/flashfloppy#893]
Hi

Does anyone have any experience getting the Gotek with Flash Floppy working on an E-MU Emulator I ?  So far I have not been able to get the EI to recognize the drive. I believe it is a configuration issue with CFG file. Any help would be greatly appreciated. Thanks!

**Comment by keirf** [comment]
Jumper at S0 only, probably. And use HFE image files. Please look for tech support on forums, or the Facebook group, or in the Discussions area of the GitHub project.
