### ISSUE TITLE
amstrad cpc dsk support

### ISSUE THREAD

**Issue by Breiztiger** [keirf/FlashFloppy#9]
hi

very good job for gotek drive !!!

do you think supporting native dsk format for Amstrad cpc ?

thanks in advance

**Comment by keirf** [comment]
Not sure, it's not a pure sector image like ADF/IMG/ST. It's not too far off though so probably supportable with not too much trouble.

I will leave this issue open for now to track progress.

**Comment by Breiztiger** [comment]
if only no protected dsk should work, it's very usefull for demo or cracked games !!!

**Comment by keirf** [comment]
Yes, I see no reason that shouldn't work. By the way every CPC DSK I've downloaded has been "Extended DSK", I wonder if there are any examples of "normal" ones?

**Comment by Breiztiger** [comment]
as no protected dsk i think for edsk with only 40 track with 9 x 512k sectors, no gaps or fdc errors in st1 or st2

**Comment by keirf** [comment]
This is done as of v0.9.0a. Please raise new issues for any problems with the DSK support.
