### ISSUE TITLE
Firmware update stuck on FF Update Flash [USB]

### ISSUE THREAD

**Issue by Pandorify** [keirf/flashfloppy#905]
Hi, I'm running into an issue with the QD firmware update where it gets to the FF Update Flash screen, then stays there forever (I let it sit for 2 hours). I'm unsure if I'm just supposed to assume it's done and manually restart, or if it's meant to automatically restart like said in the wiki. I don't have any errors on my screen.

**Comment by keirf** [comment]
Try clicking rotary encoder. It should then at least display [USB] or an error message. Updates never take longer than a few seconds.

**Comment by Pandorify** [comment]
It was actually that my USB was exFat and not Fat32, though it didn't give
me an error and just stayed flashing.
