### ISSUE TITLE
MT-100 Pinout different than in documentation

### ISSUE THREAD

**Issue by Pandorify** [keirf/flashfloppy#906]
Hi, it seems the instructions for the QuickDisk wiring on the Roland MT-100 is wildly wrong on the wiki, in a way that could send 5v to data pins and damage the Gotek. I was able to find what I believe to be a proper pinout mapping, which was confirmed as working by other users and seems to be working for me as well, on the torlus forums here: https://torlus.com/floppy/forum/viewtopic.php?p=21542#p21542

![QD Pinout](https://github.com/keirf/flashfloppy/assets/104906482/c8cde737-d6a8-4d67-ac37-5cf4fb2bd7f3)

**Comment by keirf** [comment]
Thanks I will put this in the wiki.

**Comment by keirf** [comment]
Done. Please reopen if you see any issues in the revised documentation.
