### ISSUE TITLE
Acorn ADFS 'S' format not supported

### ISSUE THREAD

**Issue by simoninns** [keirf/FlashFloppy#91]
There is no support in flash floppy for the Acorn ADFS 'S' format which is 40T SSD 160K; attempting to use a 160K .adf image results in *ERR*31*

This format was supported by the Acorn BBC Master 128 ADFS and (to be honest) was barely (if ever) used - but, if possible, should be included for completion.

**Comment by keirf** [comment]
That should be very easy. I will take a look.

**Comment by keirf** [comment]
Please test the following firmware:

[ff_91_1.zip](https://github.com/keirf/FlashFloppy/files/1879473/ff_91_1.zip)

**Comment by simoninns** [comment]
Tested by formatting, verifying, writing files, reading files and creating directories.  Works perfectly  :)

**Comment by keirf** [comment]
Thanks, will be supported in the next release (v0.9.17a).
