### ISSUE TITLE
GOTEK and MSDOS - 1.44MB disks do not work

### ISSUE THREAD

**Issue by arti040** [keirf/flashfloppy#910]
I got config as follows:
S1 jumper - closed,
JC jumper - closed,
J5 jumper - closed (for IBM PS1 2011 model and high destiny drives... but I does not change anything anyway)

FF.cfg:
interface = ibm-pc
host = "unspecified" or "pc-dos"

Problem is, my PC recognizes it only as 5.25/1.2MB and boots only from such images.
Tested on two GOTEKs and few USB drives + did some tests on more standard, 486-class computer - the same effect. Only 5.25 drive works.

**Comment by keirf** [comment]
It's probably a BIOS option to select the attached drive type?

**Comment by arti040** [comment]
On 486 yes - but only 5.25 variant works properly. On IBM PS1 I have no option to change anything. It just discovers such drive - and that's it. However, if I connect GOTEK to the second port on a cable ribbon, it discovers two drives - 5.25/1.2MB and 5.25/360KB... or two 5.25/360KB - depends on cable. I'm not able to force any of my computers to recognize it as 3.5/1.44MB drive. :/

**Comment by keirf** [comment]
There is no more configuration nor identification, however. FF will automatically act as a 1.44M 3.5 drive when used with a 1.44M IMG file.

**Comment by arti040** [comment]
Do you think that reflashing firmware would help?

**Comment by keirf** [comment]
Are you definitely running FlashFloppy already (says 'F-F' or 'FlashFloppy' on display when no USB drive is inserted)?

**Comment by arti040** [comment]
Yup. v. 3.42, I guess.

**Comment by keirf** [comment]
I would concentrate on 486 to start with, as that will be a regular PC with no IBM funniness.

Remove your FF.CFG. You don't need it for regular PCs. Delete any cached config by pressing both buttons while no USB drive is inserted, for several seconds, until the display changes (will say 'RST' or 'Reset Flash' or something like that).

Keep jumpers at S1 and JC. Remove J5.

BIOS configure drive as 3.5/1.44 and try a bootable 1.44 image. It should work.

**Comment by arti040** [comment]
Ok, will try and let you know later. Thanks!

**Comment by arti040** [comment]
OK, I'm coming back with the status:
1. On 486 - it works perfectly fine as 3.5/1.44MB;
2. On IBM PS1 - when J5 is removed - it doesn't work - it tries to read first sector and returns and error - "Not ready drive A", however if I close J5 jumper, it does a few attempts by reading sectors 1.0, 2.0/2.1 and then stops with no errors.

**Comment by keirf** [comment]
IBM PS/1 and PS/2 may use other pins to identify the floppy type. They aren't necessarily well supported.

**Comment by arti040** [comment]
Yay! It works! I had to short 4th line of the ribbon cable to GND and that's it. Here are the details -> https://www.youtube.com/watch?v=XZb9WN_u0YA&t=700s

**Comment by keirf** [comment]
That's great! I think shorting pin 4 is the same as jumpering J5 actually....

**Comment by arti040** [comment]
I got it shorted but if it's open, IBM discovers GOTEK as 3.5/720KB... strange.
