### ISSUE TITLE
emu esi 4000 sampler

### ISSUE THREAD

**Issue by jorgerope** [keirf/flashfloppy#921]
Hi, Someone has the img.cfg and ff.cfg file for emu esi 4000. I have flashfloppy 3.42 installed on floppy gotek but when loading the image it does not load the file in the sampler. When I click on it, it tells me that the sound bank consists of two diskettes. Having said that, I select load and with the first diskette there is no problem, then when it asks me for the second one, it does not load it, I get the message "wrong number". Also, I don't know how images are loaded onto the USB and how files are recorded from the sampler onto the USB. Greetings and I need help!!!

**Comment by keirf** [comment]
General tech support. Not a bug. Forums, Facebook, or Discussions tab here on GitHub, please
