### ISSUE TITLE
PCW8256 Loading issues

### ISSUE THREAD

**Issue by A-little-confused** [keirf/flashfloppy#924]
Hello,
I am trying my hardest to get my Gotek to work on my PCW as drive A:
I have the jumpers on S0 and JA, an adapter to go from the PCW to the back of the Gotek, 5v and ground pins to the Gotek and can see when powered up on the Goteks OLED that DSK files are present. But still cannot get anything to load.

What am I doing wrong or not doing.

Many thanks

**Comment by keirf** [comment]
Do you mean jumper on JA? What firmware is running on your Gotek?

**Comment by A-little-confused** [comment]
Yes, Jumper JA and 4.7a firmware.

**Comment by keirf** [comment]
Do not use the alpha firmware. Stick with 3.42.

Why do you have a jumper at JA? In fact this should stop the Gotek from initialising, as it will look like a button is permanently pressed (and put the Gotek in firmware update mode).

**Comment by A-little-confused** [comment]
Right, I have tge jumpers on S0 and JC. Downgraded to 3.42 following the steps online and can see it briefly flash up when starting the machine that it is now at version 3.42.

Have cycled through the DSK files on the USB and clicked to have it launch, but still no loading, just the beeps (they indicate no disk) as we had before.

Sorry all

**Comment by A-little-confused** [comment]
All this help is appreciated.
Have tried all of the jumper settings. But to no avail.

![20240821_123224](https://github.com/user-attachments/assets/53b6e145-ee04-4854-ba63-83d3b901efd5)
![20240821_123246](https://github.com/user-attachments/assets/a7528581-fc56-4de4-a8c3-a62ca44590d7)

Maybe I don't have the correct CFG or HFE files. 

Thanks

**Comment by keirf** [comment]
Is the adapter the right way round? I would expect pin 1 to pin1, and ribbon stripes matched to pin 1 at both ends as well.

**Comment by keirf** [comment]
Okay, and that is definitely a PCW adapter? There are multiple 26-pin floppy interface layouts. Amstrad themselves used more than one afaik.

**Comment by A-little-confused** [comment]
Right problem solved.

Set jumper to MO
Removed JC
Moved the ribbon and adapter to match 1 on all.

AND BOOM ITS WORKING

Thank you over and over again.
![20240821_142638](https://github.com/user-attachments/assets/88da2783-b5b3-46cc-8b7e-4e3b3c6abb90)
![20240821_143511](https://github.com/user-attachments/assets/1f573a17-ac3e-461f-8a55-d800004c47a6)

**Comment by keirf** [comment]
Trial and error wins again!
