### ISSUE TITLE
Archimedes 3010 and ADFs under 800kB?

### ISSUE THREAD

**Issue by micv2** [keirf/flashfloppy#933]
Hi, 
I have an A3010 with Gotek & latest FlashFloppy. How can I play the game Pack-Mania with an ADF of 795kB? 
I get Error 31. Other ADFs with 800kB works very well 👍

Best Regards,
MiC

**Comment by keirf** [comment]
Easiest would be to pad it to 800kB. On Linux or similar this would be easy: `truncate -s 800K name.adf`

**Comment by micv2** [comment]
Thank you Sir, Windows can't do that? 😉

**Comment by keirf** [comment]
You will have to research it yourself for Windows. Or perhaps use Windows Subsystem for Linux (WSL)?

**Comment by micv2** [comment]
Hi, ok thank you, it can be closed.

Regards,
MiC

**Comment by micv2** [comment]
Hello keirf, 

on Sunday I got about 30 (too small) ADFs to the required 800k using Linux. Now (after work) I sat down at Archimedes (a3010) and wanted to play Pacmania. The game doesn't work. The ADF now has 800k, GOTEK shows no error, but Archimedes shows errors for every converted ADF, why? 

Other 800k or 1600k games work perfectly. 
Sir, it would be nice if you could help me again. I'm attaching the files here. 

Thank you very much 👍

[test.zip](https://github.com/user-attachments/files/17019691/test.zip)

![IMG_4441](https://github.com/user-attachments/assets/80c9d158-1237-4e2a-be13-1770db50c271)

**Comment by keirf** [comment]
I assumed they were simply truncated, but perhaps these smaller ADFs are not so simple to convert to 800kB form. Do they work in full emulation on a PC? Anyway, your best bet is to ask on an Acorn-specific forum such as stardot.org.uk. I am sure someone there will be able to tell you what to do with these image files!

**Comment by keirf** [comment]
Oh, actually now I see that you actually created a completely empty 800kB ADF. It is full of zeroes!

Please try the attached, correctly padded, ADF
[pacmania.zip](https://github.com/user-attachments/files/17019886/pacmania.zip)

**Comment by micv2** [comment]
Ok, I'll try. But is my FF.CFG set correctly? (.zip) I have the jumper on JC&S1.

**Comment by micv2** [comment]
"Oh, actually now I see that you actually created a completely empty 800kB ADF. It is full of zeroes!"

how could this happen? 🤦‍♂️

**Comment by keirf** [comment]
The only non default option you need in FF.CFG is `host = acorn`

**Comment by micv2** [comment]
yes Sir, the game is running 🎈🎈

I used Cygwin under Win10 to convert, it failed..😟

**Comment by keirf** [comment]
All I did on Linux was `truncate -s 800K pacmania.adf` where `pacmania.adf` must be the name of your existing ADF image. Otherwise it will probably create a new empty 800kB file!

**Comment by micv2** [comment]
Ok, thanks Sir, 🙂
