### ISSUE TITLE
SD Card Detected Signal

### ISSUE THREAD

**Issue by SukkoPera** [keirf/flashfloppy#934]
Quoting the _Enhanced Gotek_ wiki page:

> Card Detect should float when a card is inserted, and be driven low when no card is present. For simplest connection, this will require a card-detection switch which is open when a card is inserted, and closed when ejected. A switch with the opposite sense will require extra circuitry (eg. pull-up resistor and an open-drain MOSFET to invert the switch signal).

Is this a hardware limitation or could that be made configurable in the software?

**Comment by keirf** [comment]
It could be configurable but it is quite easy to fix up in hardware so...

**Comment by SukkoPera** [comment]
I see, but then I think the only supported behavior should be the other one. The vast majority (meaning actually all of them) of the SD slots I've seen short two pins when the card is _inserted_, and that makes it impossible to achieve the currently expected behavior without extra components.

**Comment by keirf** [comment]
But I can't now change the default behaviour. Perhaps we could allocate a new identifier in pins PC15:12

**Comment by SukkoPera** [comment]
OK, never mind. Can you just tell me if the following circuit is correct?

<img width="1088" alt="image" src="https://github.com/user-attachments/assets/305f4db1-cb10-49d1-913e-dec852a83146">

JP1 is a jumper that allows selecting the normal or inverted behavior.

**Comment by keirf** [comment]
Looks about right to me.
