### ISSUE TITLE
Improve support/docs for akai s950 and s3000xl and roland mc-500

### ISSUE THREAD

**Issue by fbohmann** [keirf/FlashFloppy#97]
things for improving ff and the documentation for use with akai samplers:

for akai sd images: 
img.c: akai sd type like hd with only 5 sectors

s950:
jumpers: just s0
ff.cfg: interface = shugart, host = akai
floppy.c: [FINTF_SHUGART] [outp_dskchg] = pin_unset, [outp_hden]   = pin_02 
800k and 1600k raw images and hfe work fine then

s3000xl:
jumpers: just s0
ff.cfg: interface = ibmpc-hdout, host = akai
800k and 1600k raw images and hfe work fine then

what also works for me:
roland mc-500 sequencer:
jumpers: just s0
ff.cfg: interface = jc (shugart)

**Comment by keirf** [comment]
Support is in master and will roll into v0.9.17a.
